"""Customer journey, product demonstrations and help content for the review site."""
from pathlib import Path
from html import escape as E

X = {
'en': {
 'nav':['Products','How we work','Guides & downloads','About','Pricing','Contact'],
 'mrpKicker':'01 / HAMVARA MRP II', 'mrpTitle':'Know your stock. Plan your next move.',
 'mrpLead':'Connect inventory, material requirements and production in one operational workflow. Watch the MRP tour, then follow the steps below.',
 'tourNote':'Illustrative MRP tour · Sample data · English interface', 'pause':'Pause tour','play':'Play tour',
 'flowTitle':'What happens, step by step',
 'mrpFlow':[['Receive & record','Register materials and warehouse stock.'],['Check & plan','Compare orders with BOMs and available materials.'],['Produce & track','Follow production, consumption and output.'],['Prepare delivery','Review finished goods and shipment readiness.']],
 'skuKicker':'02 / SKU BRIDGE','skuTitle':'Messy product files. A clearer next step.',
 'skuLead':'Turn scattered Excel and CSV product data into a file you can review, correct and prepare for import.',
 'skuFlow':[['Bring your file','Start with an Excel or CSV product list.'],['Match columns','Map source columns to the right product fields.'],['Review & approve','Resolve duplicates and missing information.'],['Export clean data','Check the output against your destination template.']],
 'videoNote':'24-second product introduction · Illustrative launch workflow · No audio', 'transcript':'Read the video transcript',
 'videoText':'SKU Bridge: from messy product files to a reviewed export. 1. Bring your Excel or CSV file. 2. Match columns and find exceptions. 3. Review issues and approve the rows you trust. 4. Export a new file, then check it against your destination system’s template. The original file remains unchanged. This is an illustrative launch workflow; the public beta may differ.',
 'serviceKicker':'HOW WE WORK WITH YOU','serviceTitle':'From your first request to a working solution.',
 'serviceLead':'Four clear stages, with guidance throughout.',
 'service':[['Your request','Tell us about your business, current workflow and the problem you want to solve.'],['Consultation & proposal','We review your needs and agree the scope, price and delivery plan with you.'],['Build & validate','We configure or develop the agreed solution and review it with representative data.'],['Delivery & support','We hand over the solution, explain how to use it and confirm the agreed support arrangements.']],
 'serviceCta':'Discuss your needs',
 'guideKicker':'GUIDES & DOWNLOADS','guideTitle':'A clear place to start. Help when you need it.',
 'guideLead':'Learn how to use the website, take your first steps in MRP and prepare a product file with SKU Bridge.',
 'guides':[['website','Using this website','Find a product, watch its introduction and choose your next step.'],['mrp','MRP getting started','Set up master data, review stock and work through a production scenario.'],['sku','SKU Bridge getting started','Prepare a sample, review exceptions and check your export.']],
 'readGuide':'Read guide','downloadGuide':'Download offline guide (HTML)','sample':'Download sample product file (CSV)',
 'downloadNote':'Start with the sample file. Offline guides open in your browser and can be printed or saved as PDF. For a supported software installer, request the correct version from Hamvara.',
 'installer':'Request a software version','aiTitle':'Advanced help with AI','aiText':'Prepare a question with the relevant guide and continue in ChatGPT. This opens a separate service; there is no embedded AI chat on this website. Check advice against your software version before changing real records.',
 'aiLabel':'Choose a topic','aiPrepare':'Prepare my question','aiCopy':'Copy question','aiOpen':'Open ChatGPT','aiCopied':'Question copied. Open ChatGPT and paste it.','aiFallback':'Select and copy the question below.','aiPrompt':'Use the following Hamvara getting-started guide to help me step by step. Ask which software version I use and what I want to achieve. Explain one step at a time. Do not invent buttons or capabilities, and ask before recommending changes to real data. Do not request passwords or sensitive business data. Guide: ',
 'aboutKicker':'ABOUT HAMVARA','aboutTitle':'Manufacturing experience meets software expertise.',
 'aboutLead':'Hamvara builds practical software to help businesses manage inventory, production, purchasing and daily operations with greater clarity and control.',
 'aboutExperience':'Our approach draws on more than two decades of hands-on experience in production planning, warehouse management and manufacturing operations in Iran and at international companies. We bring that operational knowledge into software development, building tools around the needs of the people who use them.',
 'aboutMore':'Read our story', 'aboutSections':[
 ['Why Hamvara exists','Running a manufacturing business means making decisions under pressure. Stock records do not always match reality. Materials arrive late. Production priorities change. Important information gets scattered across spreadsheets, messages and paperwork.','We understand these challenges. Our purpose is to help businesses organize their operational information, reduce repetitive work and make better-informed decisions—from receiving materials to delivering finished goods.'],
 ['From MRP II toward ERP','Hamvara MRP II—Manufacturing Resource Planning—is the foundation of our manufacturing software. Alongside it, focused tools such as SKU Bridge help businesses prepare and organize the data their operations depend on.','Our roadmap includes Hamvara ERP, expanding this foundation toward broader, integrated business management. We are taking that next step progressively, guided by real workflows and practical business needs.'],
 ['How we work','We start by understanding how work happens: where information gets lost, which tasks consume unnecessary time and what people need to make sound decisions.','That understanding guides our development. We focus on clear information, straightforward workflows and controls that support everyday work.','Our aim is simple: software that helps people spend less time reconciling information and more time managing their business.'],
 ['Let’s talk about your operations','Based in Istanbul, Türkiye, Hamvara welcomes conversations with businesses looking for a clearer, more organized way to manage their operations.','Tell us about your workflow and the challenges you want to solve.']],
 'priceSummary':'Plans & launch pricing','toolsSummary':'Need another tool? Explore the Hamvara toolbox.',
 'guideSteps':{
 'website':[['Choose your starting point','Use MRP for manufacturing operations or SKU Bridge for preparing product files. Watch the introduction and read the process below it.'],['Explore safely','The tour uses sample data. Product buttons open the current public applications, which may differ from the launch preview. Begin with sample data.'],['Review the plan','Open the pricing section for proposed launch prices. Checkout is not enabled in this review website.'],['Ask for help','Use Guides & downloads for instructions, or contact Hamvara by email or WhatsApp. For a tailored solution, follow the four stages in How we work.']],
 'mrp':[['Confirm your version and workspace','Open MRP and confirm whether you are using a demo, SaaS workspace or portable installation. Use a demo or a backup copy for practice.'],['Prepare your master data','Create or review product codes, units of measure and warehouses. Avoid changing existing codes without checking their movement history.'],['Check stock and BOMs','Enter or import opening balances using the template supplied in your version. Review BOM quantities and units, then compare physical stock with the records.'],['Work through one order','Enter a small sample order, review material requirements and shortages, then follow the production workflow available in your version.'],['Review before posting','Check quantities, warehouse selections and approvals before posting. Review finished goods, movements and delivery records. Export or back up your work using the controls provided in your version.']],
 'sku':[['Prepare a copy','Keep the original file. Start with the downloadable CSV sample and make sure product codes and barcodes are treated as text.'],['Open and map','Open the public beta, load a supported file and review the available column mappings. The public beta may differ from the launch workflow shown in the video.'],['Inspect exceptions','Review duplicate product codes, missing values, units and decimal separators. Do not assume a duplicate is safe to delete.'],['Review the output','Use the review and export controls available in your version. Check leading zeros, quantities and required fields in the exported file.'],['Test the destination','Compare the export with the destination ERP import template. Try a small batch in a test workspace before importing live data.']]},
 'print':'Print / save as PDF','back':'Back to guides','guideVersion':'Getting-started guide · 08 October 2026 · Check controls against your installed version.'
},
'fa': {
 'nav':['محصولات','روش همکاری','راهنما و دانلود','درباره ما','قیمت‌ها','تماس'],
 'mrpKicker':'۰۱ / HAMVARA MRP II','mrpTitle':'موجودی را بدانید؛ تولید را با اطمینان برنامه‌ریزی کنید.',
 'mrpLead':'موجودی، نیاز مواد و تولید را در یک روند عملیاتی دنبال کنید. نمایش MRP را ببینید و مراحل زیر آن را مرور کنید.',
 'tourNote':'نمایش نمونهٔ MRP · اطلاعات آزمایشی · رابط انگلیسی','pause':'توقف نمایش','play':'پخش نمایش','flowTitle':'این محصول چه کاری انجام می‌دهد؟',
 'mrpFlow':[['دریافت و ثبت','مواد و موجودی انبار را ثبت کنید.'],['کنترل و برنامه‌ریزی','سفارش را با BOM و مواد موجود مقایسه کنید.'],['تولید و پیگیری','مصرف مواد، پیشرفت تولید و خروجی را دنبال کنید.'],['آماده‌سازی تحویل','محصول نهایی و آمادگی ارسال را بررسی کنید.']],
 'skuKicker':'۰۲ / SKU BRIDGE','skuTitle':'از فایل‌های پراکنده به اطلاعات قابل بررسی.',
 'skuLead':'داده‌های محصول در اکسل و CSV را برای بررسی، اصلاح و ورود به نرم‌افزار مقصد آماده کنید.',
 'skuFlow':[['ورود فایل','فهرست محصولات اکسل یا CSV را انتخاب کنید.'],['تطبیق ستون‌ها','ستون‌های فایل را به فیلدهای محصول متصل کنید.'],['بررسی و تأیید','کدهای تکراری و اطلاعات ناقص را بررسی کنید.'],['خروجی پاک‌سازی‌شده','خروجی را با قالب نرم‌افزار مقصد تطبیق دهید.']],
 'videoNote':'معرفی ۲۴ ثانیه‌ای محصول · روند نمونهٔ نسخهٔ عرضه · بدون صدا','transcript':'متن ویدیو را بخوانید',
 'videoText':'SKU Bridge: از فایل‌های نامرتب محصول به خروجی بررسی‌شده. ۱. فایل اکسل یا CSV را وارد کنید. ۲. ستون‌ها را تطبیق دهید و خطاها را پیدا کنید. ۳. موارد نیازمند بررسی را اصلاح و ردیف‌های مناسب را تأیید کنید. ۴. خروجی جدید بگیرید و آن را با قالب نرم‌افزار مقصد مقایسه کنید. فایل اصلی تغییر نمی‌کند. این یک روند نمایشی برای نسخهٔ عرضه است؛ نسخهٔ بتای عمومی ممکن است متفاوت باشد.',
 'serviceKicker':'روش همکاری با شما','serviceTitle':'از درخواست شما تا تحویل راهکار کاربردی.',
 'serviceLead':'چهار مرحلهٔ روشن، همراه با راهنمایی در طول مسیر.',
 'service':[['درخواست مشتری','کسب‌وکار، روش فعلی کار و مسئله‌ای را که می‌خواهید حل کنید توضیح دهید.'],['مشاوره و پیشنهاد','نیازها را بررسی می‌کنیم و دامنهٔ کار، قیمت و زمان تحویل را با شما مشخص می‌کنیم.'],['ساخت و بررسی','راهکار توافق‌شده را توسعه یا تنظیم می‌کنیم و با دادهٔ نمونه همراه شما بررسی می‌کنیم.'],['تحویل، آموزش و پشتیبانی','راهکار را تحویل می‌دهیم، روش استفاده را توضیح می‌دهیم و شرایط پشتیبانی توافق‌شده را مشخص می‌کنیم.']],
 'serviceCta':'دربارهٔ نیازتان صحبت کنیم',
 'guideKicker':'راهنما و دانلود','guideTitle':'شروع روشن؛ راهنمایی در زمان نیاز.',
 'guideLead':'روش استفاده از سایت، شروع کار با MRP و آماده‌سازی فایل محصول با SKU Bridge را یاد بگیرید.',
 'guides':[['website','راهنمای استفاده از سایت','محصول را پیدا کنید، معرفی آن را ببینید و قدم بعدی را انتخاب کنید.'],['mrp','شروع کار با MRP','داده‌های پایه و موجودی را آماده کنید و یک سناریوی تولید را مرور کنید.'],['sku','شروع کار با SKU Bridge','با فایل نمونه شروع کنید، خطاها را بررسی و خروجی را کنترل کنید.']],
 'readGuide':'مطالعهٔ راهنما','downloadGuide':'دانلود راهنمای آفلاین (HTML)','sample':'دانلود فایل نمونهٔ محصول (CSV)',
 'downloadNote':'ابتدا با فایل نمونه تمرین کنید. راهنمای آفلاین در مرورگر باز می‌شود و قابل چاپ یا ذخیره به PDF است. برای دریافت نسخهٔ مناسب نرم‌افزار، با هموارا تماس بگیرید.',
 'installer':'درخواست نسخهٔ نرم‌افزار','aiTitle':'راهنمایی پیشرفته با هوش مصنوعی','aiText':'پرسش خود را همراه با راهنمای مرتبط آماده کنید و در ChatGPT ادامه دهید. این دکمه سرویس جداگانه‌ای را باز می‌کند؛ چت هوش مصنوعی داخلی در این سایت فعال نیست. پیش از تغییر اطلاعات واقعی، پاسخ را با نسخهٔ نرم‌افزار خود تطبیق دهید.',
 'aiLabel':'موضوع را انتخاب کنید','aiPrepare':'آماده‌سازی پرسش','aiCopy':'کپی پرسش','aiOpen':'بازکردن ChatGPT','aiCopied':'پرسش کپی شد؛ ChatGPT را باز کنید و آن را وارد کنید.','aiFallback':'متن زیر را انتخاب و کپی کنید.','aiPrompt':'با استفاده از راهنمای زیر برای هموارا، به فارسی و مرحله‌به‌مرحله کمکم کن. ابتدا نسخهٔ نرم‌افزار و هدفم را بپرس. هر بار یک مرحله را توضیح بده. دکمه یا قابلیت ناموجود اختراع نکن و پیش از پیشنهاد تغییر اطلاعات واقعی از من بپرس. رمز عبور یا اطلاعات حساس کسب‌وکار درخواست نکن. راهنما: ',
 'aboutKicker':'دربارهٔ هموارا','aboutTitle':'تجربهٔ تولید در کنار تخصص نرم‌افزار.',
 'aboutLead':'هموارا نرم‌افزارهای کاربردی می‌سازد تا کسب‌وکارها موجودی، تولید، خرید و عملیات روزانه را با شفافیت و کنترل بیشتری مدیریت کنند.',
 'aboutExperience':'رویکرد ما بر بیش از دو دهه تجربهٔ عملی در برنامه‌ریزی تولید، مدیریت انبار و عملیات صنعتی در ایران و شرکت‌های بین‌المللی تکیه دارد. این شناخت عملیاتی را وارد توسعهٔ نرم‌افزار می‌کنیم تا ابزارها بر اساس نیاز استفاده‌کنندگان ساخته شوند.',
 'aboutMore':'داستان هموارا را بخوانید','aboutSections':[
 ['چرا هموارا شکل گرفت؟','مدیریت تولید یعنی تصمیم‌گیری زیر فشار. موجودی ثبت‌شده همیشه با واقعیت برابر نیست؛ مواد دیر می‌رسند، اولویت‌های تولید تغییر می‌کنند و اطلاعات میان اکسل، پیام‌ها و اسناد پراکنده می‌شود.','هدف ما کمک به سازمان‌دهی اطلاعات عملیاتی، کاهش کار تکراری و تصمیم‌گیری آگاهانه‌تر است؛ از دریافت مواد تا تحویل محصول.'],
 ['از MRP II به سوی ERP','Hamvara MRP II، برنامه‌ریزی منابع تولید، پایهٔ نرم‌افزار تولید ماست. ابزارهای متمرکزی مانند SKU Bridge نیز به آماده‌سازی و نظم‌دهی داده‌های مورد نیاز عملیات کمک می‌کنند.','ساخت Hamvara ERP در برنامهٔ توسعهٔ ما قرار دارد تا این پایه به مدیریت یکپارچه‌تر کسب‌وکار گسترش یابد. این مسیر را مرحله‌به‌مرحله و بر اساس نیازهای واقعی دنبال می‌کنیم.'],
 ['روش کار ما','از شناخت روند واقعی کار شروع می‌کنیم: اطلاعات کجا گم می‌شود، چه کارهایی زمان غیرضروری می‌گیرد و تصمیم‌ها به چه اطلاعاتی نیاز دارند.','اطلاعات روشن، روندهای ساده و کنترل‌های کاربردی راهنمای توسعهٔ ما هستند.','هدف ما نرم‌افزاری است که زمان تطبیق اطلاعات را کمتر و فرصت مدیریت کسب‌وکار را بیشتر کند.'],
 ['دربارهٔ عملیات شما صحبت کنیم','هموارا مستقر در استانبول ترکیه است و از گفت‌وگو با کسب‌وکارهایی که به‌دنبال مدیریت منظم‌تر عملیات هستند استقبال می‌کند.','روند کار و مسئله‌ای را که می‌خواهید حل کنید با ما در میان بگذارید.']],
 'priceSummary':'طرح‌ها و قیمت‌های پیشنهادی عرضه','toolsSummary':'ابزار دیگری نیاز دارید؟ جعبه‌ابزار هموارا را ببینید.',
 'guideSteps':{
 'website':[['نقطهٔ شروع را انتخاب کنید','برای عملیات تولید سراغ MRP و برای آماده‌سازی فایل محصول سراغ SKU Bridge بروید. معرفی و روند زیر هر محصول را مرور کنید.'],['با نمونه شروع کنید','نمایش‌ها از اطلاعات آزمایشی استفاده می‌کنند. دکمهٔ محصول نسخهٔ عمومی فعلی را باز می‌کند که ممکن است با پیش‌نمایش عرضه متفاوت باشد.'],['طرح را بررسی کنید','بخش قیمت‌ها را برای مشاهدهٔ قیمت‌های پیشنهادی باز کنید. پرداخت در این نسخهٔ پیش‌نمایش فعال نیست.'],['راهنمایی بگیرید','از راهنما و دانلود استفاده کنید یا با ایمیل و واتس‌اپ تماس بگیرید. برای راهکار اختصاصی، چهار مرحلهٔ روش همکاری را دنبال کنید.']],
 'mrp':[['نسخه و محیط کار را مشخص کنید','ابتدا مشخص کنید در محیط دمو، SaaS یا نسخهٔ پرتابل هستید. تمرین را در دمو یا روی نسخهٔ پشتیبان انجام دهید.'],['داده‌های پایه را آماده کنید','کد محصول، واحد اندازه‌گیری و انبارها را ثبت یا بررسی کنید. پیش از تغییر کدهای موجود، سابقهٔ گردش آنها را بررسی کنید.'],['موجودی و BOM را کنترل کنید','موجودی اولیه را با قالب همان نسخه وارد کنید. مقدار و واحد مواد در BOM و تطابق موجودی واقعی با ثبت‌شده را بررسی کنید.'],['یک سفارش نمونه را مرور کنید','سفارش کوچک آزمایشی وارد کنید، نیاز مواد و کسری را ببینید و روند تولید موجود در نسخهٔ خود را دنبال کنید.'],['پیش از ثبت نهایی کنترل کنید','مقدار، انبار و تأییدهای لازم را پیش از ثبت نهایی بررسی کنید. محصول نهایی، گردش‌ها و اطلاعات تحویل را کنترل و با امکانات همان نسخه پشتیبان تهیه کنید.']],
 'sku':[['یک کپی آماده کنید','فایل اصلی را نگه دارید. با CSV نمونه تمرین کنید و کد محصول و بارکد را به‌صورت متن نگه دارید.'],['فایل و ستون‌ها را بررسی کنید','نسخهٔ بتا را باز کنید، فایل پشتیبانی‌شده را انتخاب و تطبیق ستون‌ها را بررسی کنید. نسخهٔ عمومی ممکن است با ویدیوی معرفی متفاوت باشد.'],['استثناها را کنترل کنید','کد تکراری، مقدار خالی، واحد و جداکنندهٔ اعشار را بررسی کنید. تکراری بودن به‌تنهایی دلیل حذف ردیف نیست.'],['خروجی را بررسی کنید','از امکانات بررسی و خروجی نسخهٔ خود استفاده کنید. صفرهای ابتدای کد، مقدارها و فیلدهای ضروری را در خروجی کنترل کنید.'],['مقصد را آزمایش کنید','خروجی را با قالب ورود اطلاعات ERP مقصد مقایسه کنید. پیش از ورود واقعی، چند ردیف را در محیط آزمایشی امتحان کنید.']]},
 'print':'چاپ / ذخیره به PDF','back':'بازگشت به راهنماها','guideVersion':'راهنمای شروع · ۸ اکتبر ۲۰۲۶ · کنترل‌ها را با نسخهٔ نصب‌شده تطبیق دهید.'
},
 'tr': {
 'nav':['Ürünler','Çalışma şeklimiz','Rehber ve indirmeler','Hakkımızda','Fiyatlar','İletişim'],
 'mrpKicker':'01 / HAMVARA MRP II','mrpTitle':'Stoğunuzu görün. Üretiminizi planlayın.',
 'mrpLead':'Stok, malzeme ihtiyacı ve üretimi tek bir operasyon akışında takip edin. MRP turunu izleyin, ardından aşağıdaki adımları inceleyin.',
 'tourNote':'Örnek MRP turu · Temsili veriler · İngilizce arayüz','pause':'Turu duraklat','play':'Turu oynat','flowTitle':'Adım adım nasıl çalışır?',
 'mrpFlow':[['Kabul ve kayıt','Malzemeleri ve depo stoklarını kaydedin.'],['Kontrol ve planlama','Siparişleri ürün reçetesi ve mevcut malzemelerle karşılaştırın.'],['Üretim ve takip','Üretimi, tüketimi ve çıktıyı takip edin.'],['Teslimata hazırlık','Mamul stokunu ve sevkiyata hazırlığı kontrol edin.']],
 'skuKicker':'02 / SKU BRIDGE','skuTitle':'Dağınık ürün dosyalarından net bir sonraki adıma.',
 'skuLead':'Excel ve CSV ürün verilerini inceleme, düzeltme ve hedef sisteme aktarma için hazırlayın.',
 'skuFlow':[['Dosyanızı seçin','Excel veya CSV ürün listenizle başlayın.'],['Sütunları eşleştirin','Sütunları doğru ürün alanlarına bağlayın.'],['İnceleyin ve onaylayın','Yinelenen kodları ve eksik bilgileri kontrol edin.'],['Verileri dışa aktarın','Çıktıyı hedef sistemin şablonuyla karşılaştırın.']],
 'videoNote':'24 saniyelik ürün tanıtımı · Temsili lansman akışı · Sessiz','transcript':'Video metnini okuyun',
 'videoText':'SKU Bridge: dağınık ürün dosyalarından incelenmiş çıktıya. 1. Excel veya CSV dosyanızı seçin. 2. Sütunları eşleştirin ve sorunları bulun. 3. Sorunları inceleyin ve uygun satırları onaylayın. 4. Yeni bir dosya dışa aktarın ve hedef sistemin şablonuyla karşılaştırın. Orijinal dosyanız değişmez. Bu temsili bir lansman akışıdır; mevcut beta farklı olabilir.',
 'serviceKicker':'SİZİNLE NASIL ÇALIŞIYORUZ?','serviceTitle':'İlk talebinizden çalışan bir çözüme.',
 'serviceLead':'Yol boyunca rehberlik sunan dört açık adım.',
 'service':[['Talebiniz','İşletmenizi, mevcut iş akışınızı ve çözmek istediğiniz sorunu anlatın.'],['Danışmanlık ve teklif','İhtiyaçları inceler; kapsam, fiyat ve teslimat planını sizinle netleştiririz.'],['Geliştirme ve kontrol','Anlaşılan çözümü geliştirir veya yapılandırır, temsili verilerle birlikte inceleriz.'],['Teslimat ve destek','Çözümü teslim eder, kullanımını açıklar ve üzerinde anlaşılan destek koşullarını netleştiririz.']],
 'serviceCta':'İhtiyacınızı konuşalım',
 'guideKicker':'REHBER VE İNDİRMELER','guideTitle':'Net bir başlangıç. Gerektiğinde yardım.',
 'guideLead':'Siteyi kullanmayı, MRP ile başlamayı ve SKU Bridge ile ürün dosyası hazırlamayı öğrenin.',
 'guides':[['website','Web sitesi rehberi','Ürün bulun, tanıtımını izleyin ve sonraki adımı seçin.'],['mrp','MRP başlangıç rehberi','Ana verileri ve stokları hazırlayıp bir üretim senaryosunu inceleyin.'],['sku','SKU Bridge başlangıç rehberi','Örnek dosyayla başlayın, sorunları inceleyin ve çıktıyı kontrol edin.']],
 'readGuide':'Rehberi okuyun','downloadGuide':'Çevrimdışı rehber (HTML)','sample':'Örnek ürün dosyası (CSV)',
 'downloadNote':'Örnek dosyayla başlayın. Çevrimdışı rehber tarayıcıda açılır; yazdırılabilir veya PDF olarak kaydedilebilir. Uygun yazılım kurulumu için Hamvara ile iletişime geçin.',
 'installer':'Yazılım sürümü isteyin','aiTitle':'Yapay zekâ ile ileri düzey rehberlik','aiText':'İlgili rehberle bir soru hazırlayın ve ChatGPT’de devam edin. Ayrı bir hizmet açılır; bu sitede yerleşik yapay zekâ sohbeti yoktur. Gerçek kayıtları değiştirmeden önce önerileri yazılım sürümünüzle karşılaştırın.',
 'aiLabel':'Konu seçin','aiPrepare':'Sorumu hazırla','aiCopy':'Soruyu kopyala','aiOpen':'ChatGPT’yi aç','aiCopied':'Soru kopyalandı. ChatGPT’yi açıp yapıştırın.','aiFallback':'Aşağıdaki soruyu seçip kopyalayın.','aiPrompt':'Aşağıdaki Hamvara başlangıç rehberini kullanarak bana Türkçe, adım adım yardımcı ol. Önce yazılım sürümümü ve hedefimi sor. Her seferinde bir adımı açıkla. Mevcut olmayan düğmeler veya özellikler uydurma. Gerçek verileri değiştirmeden önce sor. Parola veya hassas iş verileri isteme. Rehber: ',
 'aboutKicker':'HAMVARA HAKKINDA','aboutTitle':'Üretim deneyimi, yazılım uzmanlığıyla buluşuyor.',
 'aboutLead':'Hamvara, işletmelerin stok, üretim, satın alma ve günlük operasyonlarını daha net ve kontrollü yönetmesine yardımcı olan pratik yazılımlar geliştirir.',
 'aboutExperience':'Yaklaşımımız; İran’da ve uluslararası şirketlerde üretim planlama, depo yönetimi ve üretim operasyonlarında yirmi yılı aşkın uygulamalı deneyime dayanır. Bu operasyon bilgisini, kullanıcıların gerçek ihtiyaçlarına yönelik yazılım geliştirmeye taşıyoruz.',
 'aboutMore':'Hikâyemizi okuyun','aboutSections':[
 ['Hamvara neden var?','Üretim yönetimi baskı altında karar vermeyi gerektirir. Stok kayıtları gerçekle uyuşmayabilir; malzemeler gecikir, öncelikler değişir ve bilgiler dosyalarla mesajlar arasında dağılır.','Amacımız; malzeme kabulünden mamul teslimatına kadar bilgileri düzenlemek, tekrarlı işleri azaltmak ve daha bilinçli kararları desteklemektir.'],
 ['MRP II’den ERP’ye','Üretim Kaynak Planlaması olan Hamvara MRP II, üretim yazılımımızın temelidir. SKU Bridge gibi odaklı araçlar da operasyonların dayandığı verileri hazırlamaya yardımcı olur.','Yol haritamızda bu temeli daha kapsamlı ve bütünleşik işletme yönetimine taşıyacak Hamvara ERP yer alır. Gerçek iş akışları doğrultusunda adım adım ilerliyoruz.'],
 ['Nasıl çalışıyoruz?','Önce işin nasıl yapıldığını, bilginin nerede kaybolduğunu ve hangi kararların daha iyi desteğe ihtiyaç duyduğunu anlarız.','Net bilgi, anlaşılır iş akışları ve pratik kontroller geliştirmemize yön verir.','Amacımız, bilgileri uzlaştırmaya daha az; işletmeyi yönetmeye daha çok zaman ayırmanızı sağlamaktır.'],
 ['Operasyonlarınızı konuşalım','İstanbul, Türkiye merkezli Hamvara, operasyonlarını daha düzenli yönetmek isteyen işletmelerle görüşmekten memnuniyet duyar.','İş akışınızı ve çözmek istediğiniz sorunları bizimle paylaşın.']],
 'priceSummary':'Planlar ve önerilen lansman fiyatları','toolsSummary':'Başka bir araç mı gerekiyor? Hamvara araçlarını keşfedin.',
 'guideSteps':{
 'website':[['Başlangıç noktanızı seçin','Üretim için MRP, ürün dosyaları için SKU Bridge’i seçin. Tanıtımı ve ürünün altındaki süreci inceleyin.'],['Örneklerle başlayın','Tur temsili veriler kullanır. Ürün bağlantıları mevcut uygulamaları açar; bunlar lansman önizlemesinden farklı olabilir.'],['Planı inceleyin','Önerilen lansman fiyatları için fiyat bölümünü açın. Bu önizlemede ödeme etkin değildir.'],['Yardım alın','Rehberleri kullanın veya e-posta ve WhatsApp ile iletişime geçin. Özel çözüm için dört işbirliği adımını takip edin.']],
 'mrp':[['Sürüm ve ortamı doğrulayın','Demo, SaaS veya taşınabilir sürüm kullandığınızı belirleyin. Denemeleri demo veya yedek kopya üzerinde yapın.'],['Ana verileri hazırlayın','Ürün kodlarını, ölçü birimlerini ve depoları kontrol edin. Mevcut kodları değiştirmeden önce hareket geçmişini inceleyin.'],['Stok ve reçeteleri kontrol edin','Açılış stoklarını sürümünüzün şablonuyla girin. Reçete miktarlarını, birimleri ve fiziksel stok uyumunu kontrol edin.'],['Örnek siparişle ilerleyin','Küçük bir deneme siparişi girin; malzeme ihtiyaçlarını ve eksikleri kontrol edip mevcut üretim akışını takip edin.'],['Kesinleştirmeden önce inceleyin','Miktarları, depoları ve onayları kontrol edin. Mamulleri, hareketleri ve teslimat kayıtlarını inceleyip mevcut yedekleme kontrollerini kullanın.']],
 'sku':[['Bir kopya hazırlayın','Orijinali saklayın. Örnek CSV ile başlayın; ürün kodlarını ve barkodları metin olarak tutun.'],['Dosyayı eşleştirin','Betayı açın, desteklenen bir dosya seçin ve sütun eşleşmelerini kontrol edin. Mevcut beta tanıtım videosundan farklı olabilir.'],['Sorunları inceleyin','Yinelenen kodları, boş değerleri, birimleri ve ondalık ayırıcılarını inceleyin. Her yinelenen satır silinmemelidir.'],['Çıktıyı kontrol edin','Sürümünüzdeki inceleme ve dışa aktarma işlevlerini kullanın. Baştaki sıfırları, miktarları ve gerekli alanları doğrulayın.'],['Hedef sistemi deneyin','Çıktıyı hedef ERP şablonuyla karşılaştırın. Canlı aktarımdan önce küçük bir grubu test ortamında deneyin.']]},
 'print':'Yazdır / PDF olarak kaydet','back':'Rehberlere dön','guideVersion':'Başlangıç rehberi · 8 Ekim 2026 · Kontrolleri kurulu sürümünüzle karşılaştırın.'
 }
}

def process(steps, title, kind='product'):
    items=''.join(f'<li><span class="process-num">0{i+1}</span><h3>{E(s[0])}</h3><p>{E(s[1])}</p></li>' for i,s in enumerate(steps))
    return f'<div class="process {kind}"><p class="process-label">{E(title)}</p><ol class="process-steps">{items}</ol></div>'

def guide_body(lang, key):
    x=X[lang]
    return '<ol class="guide-instructions">'+''.join(f'<li><h3>{E(t)}</h3><p>{E(p)}</p></li>' for t,p in x['guideSteps'][key])+'</ol>'

def guide_cards(lang, base, full=False):
    x=X[lang]; cards=''
    for key,title,desc in x['guides']:
        body=guide_body(lang,key) if full else f'<p>{E(desc)}</p>'
        manual_url='/guides/'+('' if lang=='en' else lang+'/')+('mrp-saas.html' if key=='mrp' else 'sku-bridge.html')
        action=(f'<a class="text-link" href="{manual_url}">{E(x["readGuide"])} →</a>' if key in ['mrp','sku'] else ('' if full else f'<a class="text-link" href="{base}guides.html#{key}">{E(x["readGuide"])} →</a>'))
        download_url=(f'/guides/downloads/{"mrp-saas" if key=="mrp" else "sku-bridge"}-{lang}.html' if key in ['mrp','sku'] else f'/site-preview/downloads/hamvara-{key}-guide-{lang}.html')
        cards+=f'<article class="guide-card" id="{key if full else "guide-"+key}"><span class="guide-icon" aria-hidden="true">↗</span><h{2 if full else 3}>{E(title)}</h{2 if full else 3}>{body}<div class="guide-actions">{action}<a href="{download_url}" download>{E(x["downloadGuide"])}</a></div></article>'
    return f'<div class="{"guide-full" if full else "guide-grid"}">{cards}</div>'

def ai_help(lang):
    x=X[lang]
    opts=''.join(f'<option value="{key}">{E(title)}</option>' for key,title,_ in x['guides'])
    prompts=''.join(f'<template data-guide-prompt="{key}">{E(x["aiPrompt"]+title+"\n"+"\n".join(f"{a}: {b}" for a,b in x['guideSteps'][key]))}</template>' for key,title,_ in x['guides'])
    return f'''<section class="ai-help" id="ai-help"><div><span class="eyebrow">AI + GUIDANCE</span><h2>{E(x['aiTitle'])}</h2><p>{E(x['aiText'])}</p></div><div class="ai-controls"><label for="guide-topic">{E(x['aiLabel'])}</label><select id="guide-topic">{opts}</select><button class="button" type="button" data-prepare-question>{E(x['aiPrepare'])}</button><div data-ai-question hidden><label class="sr-only" for="guide-question">{E(x['aiCopy'])}</label><textarea id="guide-question" readonly rows="8"></textarea><div class="guide-actions"><button class="button outline" type="button" data-copy-question data-success="{E(x['aiCopied'])}" data-fallback="{E(x['aiFallback'])}">{E(x['aiCopy'])}</button><a class="button" href="https://chatgpt.com/" target="_blank" rel="noopener noreferrer">{E(x['aiOpen'])} ↗</a></div><p data-copy-status role="status"></p></div>{prompts}<noscript><p>{E(x['aiFallback'])}</p><a href="https://chatgpt.com/">ChatGPT ↗</a></noscript></div></section>'''

def offline_guide(lang,key,title):
    x=X[lang]
    return f'''<!doctype html><html lang="{lang}" dir="{'rtl' if lang=='fa' else 'ltr'}"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{E(title)} — Hamvara</title><style>body{{font:17px/1.9 system-ui,sans-serif;color:#102b3b;max-width:800px;margin:40px auto;padding:24px}}h1{{line-height:1.4}}li{{margin-bottom:28px}}h3{{margin-bottom:4px}}p{{margin-top:4px}}a{{color:#087f8c}}footer{{border-top:1px solid #ddd;padding-top:20px;font-size:14px}}@media print{{body{{margin:0}}li{{break-inside:avoid}}}}</style><header>HAMVARA / GUIDES<h1>{E(title)}</h1><p>{E(x['guideVersion'])}</p></header><main>{guide_body(lang,key)}</main><footer><p>{E(x['downloadNote'])}</p><a href="https://hamvara.com/site-preview/{'' if lang=='en' else lang+'/'}guides.html">{E(x['back'])}</a><p>info@hamvara.com · <bdi>+90 536 924 73 71</bdi></p></footer></html>'''
