import {request,renderMessages} from './common.js';
const $=id=>document.getElementById(id),api=window.HAMVARA_SUPPORT_CONFIG.apiBase;let key='',lang='en',selected=null,timer=null,lastSeen=0,busy=false,retry=null,generation=0;
const copy=()=>window.HAMVARA_SUPPORT_COPY[lang];
function translate(){document.documentElement.lang=lang;document.documentElement.dir=lang==='fa'?'rtl':'ltr';document.querySelectorAll('[data-copy]').forEach(n=>n.textContent=copy()[n.dataset.copy]);}
function error(text){$('error').hidden=!text;$('error').textContent=text||'';}
const call=(path,method='GET',body)=>request('/admin/'+path,{api,token:key,method,body});
function show(d){$('thread').hidden=false;$('status').textContent=d.mode+(d.owner?' · '+d.owner:'');renderMessages($('messages'),d.messages,copy());$('reply').hidden=d.mode!=='human';$('claim').disabled=d.mode==='closed';}
async function select(id){if(busy)return;selected=id;retry=null;$('text').value='';$('messages').dataset.last='';const g=generation;try{const d=await call('conversations/'+id);if(g===generation&&selected===id)show(d);}catch{error(copy().error);}}
async function refresh(){clearTimeout(timer);if(!key)return;const g=generation;try{const data=await call('conversations');if(g!==generation)return;$('operator').textContent=data.operator;$('threads').replaceChildren();let newest=lastSeen;for(const c of data.conversations){newest=Math.max(newest,c.updated);const b=document.createElement('button');b.textContent=c.lang.toUpperCase()+' · '+c.mode+' · '+c.id.slice(0,8)+'\n'+new Date(c.updated).toLocaleString();b.setAttribute('aria-pressed',String(c.id===selected));b.onclick=()=>select(c.id);$('threads').append(b);}if(!data.conversations.length)$('threads').textContent=copy().empty;
 if(lastSeen&&newest>lastSeen&&document.hidden&&'Notification'in window&&Notification.permission==='granted')new Notification('Hamvara',{body:copy().newReply});lastSeen=newest;
 if(selected&&!busy){const id=selected,d=await call('conversations/'+id);if(g===generation&&id===selected)show(d);}if($('available').checked)await call('presence','POST',{online:true});
 }catch(e){if(e.status===401){logout(false);error(copy().authError);}else error(copy().error);}if(key&&g===generation)timer=setTimeout(refresh,5000);}
async function logout(send=true){const old=key;generation++;key='';selected=null;retry=null;clearTimeout(timer);$('key').value='';$('text').value='';$('messages').replaceChildren();$('threads').replaceChildren();$('desk').hidden=true;$('thread').hidden=true;$('login').hidden=false;$('available').checked=false;lastSeen=0;if(send&&old)try{await request('/admin/presence',{api,token:old,method:'POST',body:{online:false}});}catch{}}
$('login').onsubmit=async e=>{e.preventDefault();key=$('key').value.trim();error('');try{await call('conversations');$('key').value='';$('login').hidden=true;$('desk').hidden=false;refresh();}catch{key='';error(copy().authError);}};
$('language').onchange=()=>{lang=$('language').value;translate();$('messages').dataset.last='';if(key)refresh();};
$('available').onchange=async()=>{try{await call('presence','POST',{online:$('available').checked});}catch{$('available').checked=false;error(copy().error);}};
for(const action of ['claim','release','close'])$(action).onclick=async()=>{if(!selected||busy)return;try{show(await call('conversations/'+selected+'/'+action,'POST',{}));error('');}catch{error(copy().error);}};
$('reply').onsubmit=async e=>{e.preventDefault();if(!selected||busy)return;const text=$('text').value.trim();if(!text)return;if(!retry||retry.text!==text)retry={text,messageId:crypto.randomUUID()};busy=true;const id=selected,g=generation;try{const d=await call('conversations/'+id+'/reply','POST',retry);if(g===generation&&selected===id){show(d);$('text').value='';retry=null;error('');}}catch{error(copy().failure);}finally{busy=false;}};
$('refresh').onclick=refresh;$('logout').onclick=()=>logout();$('notify').onclick=async()=>{if(!('Notification'in window)||await Notification.requestPermission()!=='granted')error(copy().notifyDenied);};translate();
