// Public, actionable errors only. Never expose server internals or credentials.
const text={
 fa:{limit:'محدودیت تعداد درخواست یا ساخت گفت‌وگو فعال شده است. پی‌درپی تلاش نکنید؛ از گفت‌وگوی قبلی یا ایمیل و واتس‌اپ استفاده کنید.',verify:'تأیید امنیتی در سرور پذیرفته نشد. پس از تأیید دوباره، یک بار تلاش کنید؛ اگر تکرار شد با پشتیبانی تماس بگیرید.',verifyDown:'سرویس بررسی امنیتی فعلاً پاسخ نمی‌دهد. کمی بعد دوباره تلاش کنید یا از ایمیل و واتس‌اپ استفاده کنید.',paused:'شروع گفت‌وگوی جدید موقتاً متوقف شده است. ایمیل و واتس‌اپ در دسترس‌اند.',capacity:'ظرفیت گفت‌وگوهای پشتیبانی تکمیل است. لطفاً از ایمیل یا واتس‌اپ استفاده کنید.',network:'نتیجهٔ شروع گفتگو مشخص نشد؛ اتصال قطع شد یا پاسخ دیر رسید. صفحه را تازه‌سازی کنید؛ اگر گفتگو باز نشد، دوباره تلاش کنید.',other:'گفتگو باز نشد. برای بررسی، کد خطای زیر را به پشتیبانی بگویید.',starting:'در حال شروع گفتگو…'},
 en:{limit:'The request or new-conversation limit has been reached. Avoid repeated attempts; use an existing conversation, email or WhatsApp.',verify:'The server did not accept the security check. Complete it again and retry once; contact support if this repeats.',verifyDown:'Security verification is temporarily unavailable. Try later or use email or WhatsApp.',paused:'New conversations are temporarily paused. Email and WhatsApp remain available.',capacity:'Support conversation capacity has been reached. Please use email or WhatsApp.',network:'The start result could not be confirmed because the connection failed or timed out. Refresh; if no conversation opens, try again.',other:'The conversation could not open. Share the error code below with support.',starting:'Starting conversation…'},
 tr:{limit:'İstek veya yeni görüşme sınırına ulaşıldı. Art arda denemeyin; mevcut görüşmeyi, e-postayı veya WhatsApp’ı kullanın.',verify:'Sunucu güvenlik kontrolünü kabul etmedi. Kontrolü tamamlayıp bir kez tekrar deneyin; sürerse destekle iletişime geçin.',verifyDown:'Güvenlik doğrulaması şu anda kullanılamıyor. Daha sonra deneyin veya e-posta ya da WhatsApp kullanın.',paused:'Yeni görüşmeler geçici olarak durduruldu. E-posta ve WhatsApp kullanılabilir.',capacity:'Destek görüşmesi kapasitesi doldu. E-posta veya WhatsApp kullanın.',network:'Bağlantı kesildiği veya zaman aşımına uğradığı için sonuç doğrulanamadı. Sayfayı yenileyin; görüşme açılmazsa tekrar deneyin.',other:'Görüşme açılamadı. Aşağıdaki hata kodunu destek ekibine iletin.',starting:'Görüşme başlatılıyor…'}
};
export function startingText(lang){return (text[lang]||text.en).starting;}
export function startError(error,lang){
 const words=text[lang]||text.en,known=['rate_limited','verification_required','verification_failed','verification_unavailable','new_sessions_paused','capacity_reached','operators_not_configured','service_error','service_unavailable'];
 const code=known.includes(error?.message)?error.message:(error?.status?'http_'+error.status:'connection_or_client_error');
 const kind=error?.status===429?'limit':['verification_required','verification_failed'].includes(code)?'verify':code==='verification_unavailable'?'verifyDown':code==='new_sessions_paused'?'paused':code==='capacity_reached'?'capacity':!error?.status?'network':'other';
 return words[kind]+' ['+code+']';
}
