const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'app.js'),'utf8');
const catalog=[{key:'skuMonthly',product:'sku',name:'SKU',description:'Data',scope:'user',limits:{users:1},priceId:'pri_'+ '1'.repeat(26),amount:1200,interval:'month',eligible:true},{key:'mrpAnnual',product:'mrp',name:'MRP',description:'Production',scope:'company',limits:{users:5},priceId:'pri_'+ '2'.repeat(26),amount:59000,interval:'year',eligible:true},{key:'proofMonthly',product:'proof',name:'Proof',description:'Synthetic',scope:'user',limits:{users:2},priceId:'pri_'+ '3'.repeat(26),amount:100,interval:'month',eligible:true}];
const flush=()=>new Promise(r=>setImmediate(r));
function fixture({token='test_'+ 'a'.repeat(27),signedIn=true,eligible=true,preview}={}){
 const nodes=new Map(),calls={checkout:[],server:[],previews:[]};let user='mrp-owner',authenticated=signedIn;
 function element(){return {value:'',textContent:'',disabled:false,children:[],listeners:{},append(n){this.children.push(n);},replaceChildren(){this.children=[];},addEventListener(e,f){this.listeners[e]=f;}};}
 const get=id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);};
 const Paddle={Environment:{set:v=>calls.environment=v},Initialize:o=>calls.initialize=o,Checkout:{open:o=>calls.checkout.push(o)},PricePreview:async req=>{calls.previews.push(req);if(preview)return preview(req);const p=catalog.find(p=>p.priceId===req.items[0].priceId);return {data:{currencyCode:'USD',details:{lineItems:[{price:{id:p.priceId},quantity:1,totals:{subtotal:String(p.amount),discount:'0'},formattedTotals:{subtotal:'USD '+p.amount/100,tax:'USD 0',total:'USD '+p.amount/100}}]}}};}};
 const fetch=async(url,options={})=>{
  const body=options.body?JSON.parse(options.body):null;
  if(url.endsWith('/login')){authenticated=true;user=body.username;}
  if(url.endsWith('/logout'))authenticated=false;
  if(url.endsWith('/session'))return {ok:authenticated,json:async()=>({user:{id:user,username:user,kind:'mrp'},csrf:'test',checkoutConfigured:true,webhookConfigured:true})};
  if(url.endsWith('/catalog'))return {ok:true,json:async()=>({plans:catalog.map(p=>({...p,eligible:p.scope==='company'?eligible:true}))})};
  if(url.endsWith('/checkout')){calls.server.push(body);return {ok:true,json:async()=>({transactionId:'txn_'+String(calls.server.length).padStart(26,'0')})};}
  return {ok:true,json:async()=>({entitlements:[]})};
 };
 vm.runInNewContext(source,{window:{Paddle,HAMVARA_PADDLE_SANDBOX:{clientSideToken:token}},document:{getElementById:get,createElement:element},fetch,crypto:require('node:crypto'),setTimeout,clearTimeout});
 const button=key=>get('product-cards').children[catalog.findIndex(p=>p.key===key)]?.children.at(-1);
 return {get,calls,button,click:async key=>button(key).listeners.click(),event:name=>calls.initialize.eventCallback({name}),login:async name=>{get('test-username').value=name;get('test-password').value='synthetic';await get('login-form').listeners.submit({preventDefault(){}});}};
}
test('all products including a synthetic third plan render from the server catalog',async()=>{const f=fixture();await flush();assert.equal(f.get('product-cards').children.length,3);assert.equal(f.calls.previews.length,3);assert.equal(f.button('skuMonthly').disabled,false);assert.equal(f.button('mrpAnnual').disabled,false);assert.equal(f.button('proofMonthly').disabled,false);});
test('checkout passes only a server transaction ID and completion never grants access',async()=>{const f=fixture();await flush();await f.click('skuMonthly');assert.equal(f.calls.checkout[0].items,undefined);assert.match(f.calls.checkout[0].transactionId,/^txn_/);f.event('checkout.loaded');f.event('checkout.completed');f.event('checkout.closed');assert.match(f.get('status').textContent,/does not grant access/);assert.deepEqual(Object.keys(f.calls.server[0]).sort(),['plan','requestKey']);});
test('same-account retries reuse request keys and switching accounts resets them',async()=>{const f=fixture();await flush();await f.click('skuMonthly');f.event('checkout.loaded');f.event('checkout.closed');await f.click('skuMonthly');f.event('checkout.loaded');f.event('checkout.closed');assert.equal(f.calls.server[0].requestKey,f.calls.server[1].requestKey);await f.login('sku-bob');await f.click('skuMonthly');f.event('checkout.loaded');f.event('checkout.closed');assert.notEqual(f.calls.server[2].requestKey,f.calls.server[0].requestKey);});
test('company eligibility disables only company checkout',async()=>{const f=fixture({eligible:false});await flush();assert.equal(f.button('mrpAnnual').disabled,true);assert.equal(f.button('skuMonthly').disabled,false);await f.click('mrpAnnual');assert.equal(f.calls.server.length,0);});
test('missing/live tokens and unauthenticated sessions cannot buy',async()=>{for(const options of [{token:''},{token:'live_'+ 'a'.repeat(27)},{signedIn:false}]){const f=fixture(options);await flush();if(f.button('skuMonthly')){assert.equal(f.button('skuMonthly').disabled,true);await f.click('skuMonthly');}assert.equal(f.calls.server.length,0);}});
test('failed and invalid price previews block purchases',async()=>{for(const preview of [()=>Promise.reject(Error('network')),()=>({data:{currencyCode:'EUR',details:{lineItems:[]}}})]){const f=fixture({preview});await flush();assert.equal(f.button('skuMonthly').disabled,true);assert.equal(f.button('mrpAnnual').disabled,true);}});
test('late previews cannot restore estimates after a location change',async()=>{const pending=[];const f=fixture({preview:req=>new Promise(resolve=>pending.push(()=>resolve({data:{currencyCode:'USD',details:{lineItems:[{price:{id:req.items[0].priceId},quantity:1,totals:{subtotal:String(catalog.find(p=>p.priceId===req.items[0].priceId).amount),discount:'0'},formattedTotals:{subtotal:'USD 12',tax:'USD 0',total:'USD 12'}}]}}})))});await flush();f.get('country').value='TR';f.get('country').listeners.input();pending.forEach(r=>r());await flush();assert.equal(f.button('skuMonthly').disabled,true);});
