(function(){'use strict';
const E=window.SpecPackEngine,$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const apiBase=String((window.HAMVARA_GROWTH_CONFIG||{}).apiBase||'').replace(/\/$/,'');let files=[],attributes=[],analysisMeta=null,revisions=0;
const toast=t=>{const n=$('toast');n.textContent=t;n.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.add('hidden'),2400)};
function showStep(n){document.querySelectorAll('.steps button').forEach((b,i)=>b.classList.toggle('active',i===n-1));for(let i=1;i<=3;i++)$('step'+i).classList.toggle('hidden',i!==n)}
function listFiles(){ $('fileList').innerHTML=files.length?files.map((f,i)=>`<span>${esc(f.name)} · ${(f.size/1024/1024).toFixed(2)} MB <button aria-label="Remove file" data-remove="${i}">×</button></span>`).join(''):'<span>No files selected</span>';document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{files.splice(Number(b.dataset.remove),1);listFiles()})}
function addFiles(incoming){for(const f of incoming){if(!/^(image\/(jpeg|png|webp)|application\/pdf)$/.test(f.type)){toast(`${f.name}: unsupported type`);continue}if(files.length>=5){toast('Maximum 5 files');break}if(!files.some(x=>x.name===f.name&&x.size===f.size))files.push(f)}if(files.reduce((s,f)=>s+f.size,0)>12*1024*1024){files.pop();toast('Combined file size must stay below 12 MB')}listFiles()}
function parseManual(){return $('known').value.split(/\n+/).map((line,i)=>{const p=line.split(/[:=]/),name=(p.shift()||'').trim(),value=p.join(':').trim();return name&&value?E.normalizeAttribute({id:`M-${i+1}`,name,value,source:'Manual',confidence:1,evidence:'Entered directly by the user',evidenceVerified:true,verifierAgreement:true}):null}).filter(Boolean)}
const readFile=f=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve({fileName:f.name,mimeType:f.type,dataBase64:String(r.result).split(',')[1]});r.onerror=reject;r.readAsDataURL(f)});
function setAttributes(rows,meta){attributes=rows.map((x,i)=>E.normalizeAttribute({...x,id:x.id||`A-${i+1}`}));analysisMeta=meta;revisions=0;renderReview();showStep(2)}
function renderReview(){const q=E.quality(attributes),conf=E.conflicts(attributes);attributes=q.rows;$('score').textContent=q.score+'/100';$('rows').innerHTML=attributes.map((a,i)=>`<tr><td><input type="checkbox" data-approve="${i}" ${a.approved?'checked':''} ${a.status==='INSUFFICIENT_EVIDENCE'?'disabled':''}></td><td><input data-i="${i}" data-k="name" value="${esc(a.name)}"></td><td><input data-i="${i}" data-k="value" value="${esc(a.value)}"></td><td><input data-i="${i}" data-k="unit" value="${esc(a.unit)}"></td><td>${esc(a.source)}<br><small>${esc(a.sourceFile)}</small></td><td class="confidence">${Math.round(a.confidence*100)}%</td><td class="evidence">${esc(a.evidence||'No source evidence supplied')}</td><td><span class="status ${a.status==='READY_TO_APPROVE'||a.status==='APPROVED'?'ready':a.status==='REVIEW_REQUIRED'?'review':'blocked'}">${a.status.replaceAll('_',' ')}</span></td></tr>`).join('')||'<tr><td colspan="8">No attributes found. Add manual facts or improve the source files.</td></tr>';
  document.querySelectorAll('[data-approve]').forEach(c=>c.onchange=()=>{attributes[Number(c.dataset.approve)].approved=c.checked;revisions++;renderReview()});document.querySelectorAll('[data-i][data-k]').forEach(inp=>inp.onchange=()=>{const a=attributes[Number(inp.dataset.i)];a[inp.dataset.k]=inp.value.trim();a.source='Manual';a.confidence=1;a.evidence='Corrected and confirmed by user';a.evidenceVerified=true;a.verifierAgreement=true;a.edited=true;a.approved=false;revisions++;renderReview()});
  $('conflicts').innerHTML=conf.map(c=>`<div class="alert"><b>Conflicting ${esc(c.name)} values:</b> ${c.values.map(x=>esc(x.value+(x.unit?' '+x.unit:''))).join(' / ')}. Keep one approved value.</div>`).join('');
  const pending=q.review.length+q.insufficient.length,dupes=conf.length;$('gate').textContent=pending||dupes?`${pending} uncertain row(s) and ${dupes} conflict(s) must be resolved.`:`${q.approved.length} approved · ${q.ready.length} ready to approve`;$('generate').disabled=!q.canGenerate||dupes>0;
}
function demo(){
  $('category').value='Industrial parts';$('product').value='6204-2RS sealed ball bearing';$('market').value='United States';$('use').value='Replacement part for light industrial electric motors';$('known').value='Required quantity: 2000 pieces\nBearing designation: 6204-2RS\nInner diameter: 20 mm';
  setAttributes([{name:'Bearing designation',value:'6204-2RS',source:'PDF',sourceFile:'supplier-datasheet.pdf',evidence:'Designation: 6204-2RS',confidence:.98,evidenceVerified:true,verifierAgreement:true},{name:'Inner diameter',value:'20',unit:'mm',source:'PDF',sourceFile:'supplier-datasheet.pdf',evidence:'Bore diameter d = 20 mm',confidence:.98,evidenceVerified:true,verifierAgreement:true},{name:'Outer diameter',value:'47',unit:'mm',source:'PDF',sourceFile:'supplier-datasheet.pdf',evidence:'Outside diameter D = 47 mm',confidence:.97,evidenceVerified:true,verifierAgreement:true},{name:'Width',value:'14',unit:'mm',source:'PDF',sourceFile:'supplier-datasheet.pdf',evidence:'Width B = 14 mm',confidence:.97,evidenceVerified:true,verifierAgreement:true},{name:'Seal type',value:'Rubber seals on both sides',source:'PDF',sourceFile:'supplier-datasheet.pdf',evidence:'2RS — rubber seals on both sides',confidence:.95,evidenceVerified:true,verifierAgreement:true},{name:'Material',value:'Chrome steel',source:'AI inference',sourceFile:'product-photo.jpg',evidence:'Metallic bearing appearance; no grade marking visible',confidence:.58,evidenceVerified:false,verifierAgreement:false},...parseManual()],{method:'Built-in evidence-control demonstration',model:'No model call',files:['supplier-datasheet.pdf','product-photo.jpg']});toast('Demo loaded. Notice that visual material inference is blocked.')
}
async function analyze(){const manual=parseManual();if(!files.length){if(!manual.length)return toast('Add at least one known fact or source file');setAttributes(manual,{method:'Manual web entry',model:'None',files:[]});return}if(!apiBase)return toast('AI service is not configured');const btn=$('analyze');btn.disabled=true;$('aiStatus').textContent='Reading evidence, extracting facts and running independent verification…';try{const docs=await Promise.all(files.map(readFile)),res=await fetch(apiBase+'/api/specpack/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({category:$('category').value,product:$('product').value,market:$('market').value,intendedUse:$('use').value,knownFacts:manual,documents:docs})}),body=await res.json();if(!res.ok)throw Error(body.error||'Analysis failed');setAttributes([...(body.attributes||[]),...manual],body);toast('Two-pass analysis complete. Review every result.')}catch(e){$('aiStatus').textContent=e.message;toast(e.message)}finally{btn.disabled=false}}
function generate(){const q=E.quality(attributes);if(!q.canGenerate)return toast('Resolve every uncertain row first');const approved=q.approved,product=$('product').value.trim()||'Product',qty=approved.find(x=>/quantity/i.test(x.name));$('spec').innerHTML=`<div class="spec-row"><span>Product</span><b>${esc(product)}</b></div><div class="spec-row"><span>Category</span><b>${esc($('category').value)}</b></div><div class="spec-row"><span>Target market</span><b>${esc($('market').value||'Not specified')}</b></div>`+approved.map(a=>`<div class="spec-row"><span>${esc(a.name)}</span><b>${esc(a.value)}${a.unit?' '+esc(a.unit):''}</b></div>`).join('');const lines=approved.map(a=>`- ${a.name}: ${a.value}${a.unit?' '+a.unit:''}`).join('\n'),subject=`RFQ — ${product}${qty?' — '+qty.value+' '+qty.unit:''}`;$('emailText').value=`Subject: ${subject}\n\nHello,\n\nPlease quote the product below based strictly on the approved specification:\n\n${lines}\n\nPlease confirm unit price, MOQ, lead time, Incoterm, payment terms, packaging and specification compliance. Clearly list any deviation before quoting.\n\nBest regards`;$('whatsappText').value=`Hello, please quote ${product}. Approved requirements:\n${lines}\nPlease confirm price, MOQ, lead time, Incoterm and any deviation.`;const id=`SP-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;$('audit').textContent=`REPORT ${id} · STATUS HUMAN REVIEWED · METHOD ${analysisMeta?.method||'Manual web entry'} · SOURCE FILES ${(analysisMeta?.files||[]).join(', ')||'None'} · MODEL ${analysisMeta?.model||'None'} · APPROVED ATTRIBUTES ${approved.length} · REVISIONS ${revisions} · GENERATED ${new Date().toISOString()}`;showStep(3)}
function download(){const q=E.quality(attributes),rows=[['attribute','value','unit','source','source_file','confidence','evidence','approved'],...q.approved.map(a=>[a.name,a.value,a.unit,a.source,a.sourceFile,a.confidence,a.evidence,'YES'])],csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='Hamvara-SpecPack-approved.csv';a.click();URL.revokeObjectURL(a.href)}
function addManual(){attributes.push(E.normalizeAttribute({name:'New attribute',value:'Enter confirmed value',source:'Manual'}));revisions++;renderReview()}
$('files').onchange=e=>addFiles(e.target.files);$('camera').onchange=e=>addFiles(e.target.files);const drop=$('drop');['dragenter','dragover'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>addFiles(e.dataTransfer.files));$('demo').onclick=demo;$('analyze').onclick=analyze;$('addFact').onclick=addManual;$('generate').onclick=generate;$('csv').onclick=download;$('print').onclick=()=>window.print();document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText($(b.dataset.copy).value);toast('Copied')});document.querySelectorAll('.steps button').forEach((b,i)=>b.onclick=()=>{if(i===0)showStep(1);else if(i===1&&attributes.length)showStep(2);else if(i===2&&!$('spec').innerHTML)toast('Generate an approved output first');else showStep(i+1)});listFiles();
})();
