import {COLUMNS,LIMITS,parseDelimited,guessDelimiter,tableFromRecords,suggestMapping,mapRows,parseNumber,reviewRows,safeFixes,exportRows,serializeCsv} from './core.mjs';
import {tr,fields,issues,errors} from './i18n.mjs';
const $=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaults=new Map([...document.querySelectorAll('[data-i18n]')].map(el=>[el.dataset.i18n,el.textContent]));
let lang='en', source=null, table=null, working=[], previous=null, format='auto', page=0, filter='all', editing=null, proposal=null, busy=false, resetAction=null, readerPromise=null, importedCount=0;
const PAGE_SIZE=40, MAP_KEY='hamvara.sku.mapping.v5';
const L=(en,turkish)=>lang==='tr'?turkish:en;
const field=k=>fields[lang][k]||k;
const issueText=i=>`${field(i.field)}: ${issues[lang][i.code]||i.code}`;
const setText=(id,text)=>{$(id).textContent=text;};
function notice(message='',kind=''){setText('notice',message);$('notice').className='notice '+kind;}
function showError(error){notice(errors[error.message]?.[lang==='tr'?1:0]||L('Could not complete this step. Your current file is still available.','Bu adım tamamlanamadı. Mevcut dosyanız hâlâ kullanılabilir.'),'error');$('notice').scrollIntoView({block:'nearest'});}
function step(n){document.querySelectorAll('[data-step]').forEach(el=>{el.classList.toggle('active',Number(el.dataset.step)<=n);if(Number(el.dataset.step)===n)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');});}
function snapshot(){previous=structuredClone(working);$('undo').disabled=false;}
function changed(){working=reviewRows(working,format);setText('sku-export-message','');renderReview();}
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function clearReview(){working=[];previous=null;page=0;filter='all';$('search').value='';$('undo').disabled=true;$('review-section').hidden=true;setText('sku-export-message','');}
function resetThen(action){if(working.length){resetAction=action;$('reset-dialog').showModal();}else action();}
$('confirm-reset').onclick=()=>{$('reset-dialog').close();const action=resetAction;resetAction=null;action?.();};
document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>$(button.dataset.close).close());
$('choose-file').onclick=()=>$('file').click();
$('file').onchange=()=>{const file=$('file').files[0];$('file').value='';if(file)resetThen(()=>loadFile(file));};
for(const event of ['dragenter','dragover'])$('dropzone').addEventListener(event,e=>{e.preventDefault();$('dropzone').classList.add('over');});
for(const event of ['dragleave','drop'])$('dropzone').addEventListener(event,e=>{e.preventDefault();$('dropzone').classList.remove('over');});
$('dropzone').addEventListener('drop',e=>{if(!busy&&e.dataTransfer.files[0])resetThen(()=>loadFile(e.dataTransfer.files[0]));});
function reader(){if(window.XLSX?.version==='0.20.3')return Promise.resolve(window.XLSX);if(readerPromise)return readerPromise;
  readerPromise=new Promise((resolve,reject)=>{const script=document.createElement('script');let done=false;const finish=error=>{if(done)return;done=true;clearTimeout(timer);if(error){script.remove();readerPromise=null;reject(Error('excel_reader'));}else resolve(window.XLSX);};const timer=setTimeout(()=>finish(true),15000);script.src='https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js';script.onload=()=>finish(window.XLSX?.version!=='0.20.3');script.onerror=()=>finish(true);document.head.append(script);});return readerPromise;}
function workbookRecords(workbook,sheetName){const X=window.XLSX, sheet=workbook.Sheets[sheetName];if(!sheet)return [];
  const range=X.utils.decode_range(sheet['!fullref']||sheet['!ref']||'A1');if(range.e.r+1>LIMITS.rows+100)throw Error('too_many_rows');if(range.e.c+1>LIMITS.columns)throw Error('too_many_columns');
  if(sheet['!merges']?.length)throw Error('excel_merged');
  for(const [key,cell] of Object.entries(sheet)){if(key.startsWith('!'))continue;if(cell.f||cell.F)throw Error('excel_formula');if(cell.t==='n'&&Math.abs(cell.v)>=1e15)throw Error('excel_precision');}
  // Preserve rendered identifier padding; raw numbers are handled explicitly after mapping.
  return Array.from({length:range.e.r+1},(_,r)=>({line:r+1,numericCells:Object.fromEntries(Array.from({length:range.e.c+1},(_,c)=>{const cell=sheet[X.utils.encode_cell({r,c})];return cell?.t==='n'?[c,String(cell.v)]:null;}).filter(Boolean)),cells:Array.from({length:range.e.c+1},(_,c)=>{
    const cell=sheet[X.utils.encode_cell({r,c})];if(!cell)return '';const value=String(cell.w??cell.v??'');if(value.length>LIMITS.cell)throw Error('cell_too_long');return value;
  })}));
}
async function loadFile(file){if(busy)return;busy=true;$('choose-file').disabled=true;$('sample').disabled=true;notice(L('Reading your file…','Dosyanız okunuyor…'));
  try{if(file.size>LIMITS.bytes)throw Error('file_too_large');const ext=file.name.split('.').pop().toLowerCase();if(!['csv','tsv','txt','xlsx','xls'].includes(ext))throw Error('file_type');
    const bytes=await file.arrayBuffer();let next;
    if(['xlsx','xls'].includes(ext)){const X=await reader();let workbook;try{workbook=X.read(bytes,{type:'array',sheetRows:LIMITS.rows+102,cellFormula:true,cellNF:true,cellText:true});}catch{throw Error('excel_invalid');}if(!workbook.SheetNames?.length)throw Error('excel_invalid');next={name:file.name,workbook,sheetName:workbook.SheetNames[0],text:null};next.records=[];}
    else{const b=new Uint8Array(bytes);let text;try{text=new TextDecoder(b[0]===255&&b[1]===254?'utf-16le':b[0]===254&&b[1]===255?'utf-16be':'utf-8',{fatal:true}).decode(bytes);}catch{throw Error('file_encoding');}const delimiter=ext==='tsv'?'\t':guessDelimiter(text);next={name:file.name,text,delimiter,records:parseDelimited(text,delimiter).records};}
    // Validate before replacing a prior working file; header may be changed next.
    if(!next.workbook&&!next.records.length)throw Error('no_rows');source=next;clearReview();$('header-row').value='1';$('delimiter').value=next.delimiter==='\t'?'tab':next.delimiter||'auto';$('number-format').value='auto';
    $('sheet').innerHTML=source.workbook?source.workbook.SheetNames.map(n=>`<option>${esc(n)}</option>`).join(''):'<option>CSV / TSV</option>';
    $('sheet').disabled=!source.workbook;$('delimiter').disabled=Boolean(source.workbook);$('import-panel').hidden=true;$('mapping-panel').hidden=false;setText('filename',source.name);table=null;$('analyze').disabled=true;$('mapping').innerHTML='';setText('file-summary','');if(source.workbook)source.records=workbookRecords(source.workbook,source.sheetName);rebuildTable();
  }catch(error){showError(error);}finally{busy=false;$('choose-file').disabled=false;$('sample').disabled=false;}}
function rebuildTable(){try{table=null;$('analyze').disabled=true;const index=Number($('header-row').value)-1;if(!Number.isInteger(index)||index<0||index>99)throw Error('header_missing');const next=tableFromRecords(source.records,index);table=next;renderMapping(suggestMapping(table.headers));setText('file-summary',L(`${table.rows.length.toLocaleString()} data rows · ${table.headers.length} columns · ${table.skipped} blank rows skipped`,`${table.rows.length.toLocaleString()} veri satırı · ${table.headers.length} sütun · ${table.skipped} boş satır atlandı`));$('analyze').disabled=!table.rows.length;notice();step(2);}catch(error){showError(error);}}
function renderMapping(map){$('mapping').innerHTML=COLUMNS.map(k=>`<label>${esc(field(k))}${['sku','price'].includes(k)?' *':''}<select data-map="${k}" aria-label="${esc(field(k))}"><option value="-1">${L('Not mapped','Eşleştirilmedi')}</option>${table.headers.map((h,i)=>`<option value="${i}" ${map[k]===i?'selected':''}>${i+1}. ${esc(h||L('(blank header)','(boş başlık)'))}</option>`).join('')}</select><span class="fieldhint" data-example="${k}"></span></label>`).join('');document.querySelectorAll('[data-map]').forEach(el=>el.onchange=updateExamples);updateExamples();}
function mapping(){return Object.fromEntries([...document.querySelectorAll('[data-map]')].map(el=>[el.dataset.map,Number(el.value)]));}
function updateExamples(){const map=mapping();document.querySelectorAll('[data-example]').forEach(el=>{const value=map[el.dataset.example]>=0?table.rows[0]?.cells[map[el.dataset.example]]:'';el.textContent=L('Example: ','Örnek: ')+(value||'—');el.title=el.textContent;});}
$('header-row').onchange=rebuildTable;
$('sheet').onchange=()=>{try{const records=workbookRecords(source.workbook,$('sheet').value);source.records=records;source.sheetName=$('sheet').value;rebuildTable();}catch(error){source.records=[];table=null;$('analyze').disabled=true;showError(error);}};
$('delimiter').onchange=()=>{try{const d=$('delimiter').value;source.records=parseDelimited(source.text,d==='auto'?guessDelimiter(source.text):d==='tab'?'\t':d).records;rebuildTable();}catch(error){source.records=[];table=null;$('analyze').disabled=true;showError(error);}};
$('save-mapping').onclick=()=>{if(!table)return;try{localStorage.setItem(MAP_KEY,JSON.stringify({version:5,headers:table.headers,mapping:mapping(),format:$('number-format').value}));notice(L('Mapping saved on this device. No product rows were saved.','Eşleştirme bu cihazda kaydedildi. Ürün satırları kaydedilmedi.'),'success');}catch{notice(L('Browser storage is unavailable. You can still continue.','Tarayıcı depolaması kullanılamıyor. Devam edebilirsiniz.'));}};
$('load-mapping').onclick=()=>{if(!table)return;try{const saved=JSON.parse(localStorage.getItem(MAP_KEY)||'null');if(!saved||saved.version!==5||JSON.stringify(saved.headers)!==JSON.stringify(table.headers))throw Error();if(COLUMNS.some(k=>!Number.isInteger(saved.mapping[k])||saved.mapping[k]<-1||saved.mapping[k]>=table.headers.length))throw Error();renderMapping(saved.mapping);$('number-format').value=['auto','dot','comma'].includes(saved.format)?saved.format:'auto';notice(L('Saved mapping applied. Check the examples before continuing.','Kayıtlı eşleştirme uygulandı. Devam etmeden örnekleri kontrol edin.'),'success');}catch{notice(L('No saved mapping matches these exact headers. Map the columns and save again.','Bu başlıklarla eşleşen kayıt yok. Sütunları eşleştirip tekrar kaydedin.'));}};
$('forget-mapping').onclick=()=>{try{localStorage.removeItem(MAP_KEY);notice(L('Saved mapping removed.','Kayıtlı eşleştirme kaldırıldı.'),'success');}catch{notice(L('Browser storage is unavailable.','Tarayıcı depolaması kullanılamıyor.'));}};
$('analyze').onclick=async()=>{if(!table||busy)return;busy=true;$('analyze').disabled=true;
 try{const all=mapRows(table.rows,mapping());if(!all.length)throw Error('no_rows');await window.SkuSandbox?.refresh();const selected=window.SkuSandbox?window.SkuSandbox.preview(all):all.slice(0,200);format=$('number-format').value;working=reviewRows(selected,format);importedCount=all.length;previous=null;page=0;filter='all';$('undo').disabled=true;$('review-section').hidden=false;$('mapping-panel').hidden=true;notice();renderReview();step(3);$('review-section').scrollIntoView({block:'start',behavior:'smooth'});
 }catch(error){showError(error);}finally{busy=false;$('analyze').disabled=false;}};
function counts(){return {total:working.length,review:working.filter(r=>r.status==='REVIEW').length,ready:working.filter(r=>r.status==='READY'&&!r.approved).length,approved:working.filter(r=>r.approved).length,excluded:working.filter(r=>r.excluded).length};}
function summary(){const c=counts(),unseen=importedCount-c.total;return L(`${c.approved} approved · ${c.ready} ready but not approved · ${c.review} need attention · ${c.excluded} excluded${unseen?` · ${unseen} outside this preview`:''}.`,`${c.approved} onaylı · ${c.ready} hazır ama onaysız · ${c.review} incelenmeli · ${c.excluded} hariç${unseen?` · ${unseen} önizleme dışında`:''}.`);}
function renderReview(){const c=counts();for(const k of ['total','review','ready','approved'])setText('count-'+k,c[k].toLocaleString());
  setText('review-summary',L(`${source.name} · Source row numbers are preserved. ${importedCount>working.length?`Previewing ${working.length} of ${importedCount} rows. After access is enabled, return to mapping and review again.`:''}`,`${source.name} · Kaynak satır numaraları korunur. ${importedCount>working.length?`${importedCount} satırdan ${working.length} önizleniyor. Erişim açıldıktan sonra eşleştirmeye dönüp tekrar inceleyin.`:''}`));
  setText('export-summary',summary());$('export').disabled=!c.approved||busy;$('approve-ready').disabled=!c.ready;$('issues-report').disabled=!c.review;
  const q=$('search').value.toLowerCase().trim();const filtered=working.filter(r=>(filter==='all'||filter==='approved'?filter==='all'||r.approved:r.status===filter)&&(!q||[r.sku,r.description,r.barcode].some(v=>v.toLowerCase().includes(q))));
  const pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));page=Math.min(page,pages-1);const visible=filtered.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE);
  $('rows').innerHTML=visible.length?visible.map(r=>`<tr data-row="${r.id}"><td><input type="checkbox" data-approve="${r.id}" aria-label="${esc(L('Approve row ','Satırı onayla ')+r.sourceRow)}" ${r.approved?'checked':''} ${r.status!=='READY'?'disabled':''}></td><td class="ident"><strong>${esc(r.sku||'—')}</strong><small>${esc(r.description||'—')}</small><small class="rownum">${L('Source row','Kaynak satır')} ${r.sourceRow}</small></td><td class="mono">${esc(r.barcode||'—')}</td><td class="mono">${esc(r.price||'—')} <small>${esc(r.currency)}</small></td><td class="mono">${esc(r.stock||'—')} <small>${esc(r.uom)}</small></td><td><span class="badge ${r.status}">${r.approved?L('APPROVED','ONAYLI'):({READY:L('READY','HAZIR'),REVIEW:L('NEEDS REVIEW','İNCELENMELİ'),EXCLUDED:L('EXCLUDED','HARİÇ')})[r.status]}</span>${r.status==='REVIEW'?`<div class="issue"><ul>${r.issues.map(i=>`<li>${esc(issueText(i))}</li>`).join('')}</ul></div>`:''}</td><td><div class="row"><button class="small" data-edit="${r.id}">${L('Edit','Düzenle')}</button><button class="small quiet" data-exclude="${r.id}">${r.excluded?L('Restore','Geri getir'):L('Exclude','Hariç tut')}</button></div></td></tr>`).join(''):`<tr><td colspan="7" class="empty">${L('No rows match this view. Try another filter or search.','Bu görünümde satır yok. Başka filtre veya arama deneyin.')}</td></tr>`;
  document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===filter)));
  setText('pagination-summary',L(`${filtered.length? page*PAGE_SIZE+1:0}–${Math.min((page+1)*PAGE_SIZE,filtered.length)} of ${filtered.length} matching rows`,`${filtered.length} eşleşen satırdan ${filtered.length?page*PAGE_SIZE+1:0}–${Math.min((page+1)*PAGE_SIZE,filtered.length)}`));$('previous').disabled=page===0;$('next').disabled=page>=pages-1;
}
$('filters').onclick=e=>{const b=e.target.closest('[data-filter]');if(b){filter=b.dataset.filter;page=0;renderReview();}};
$('search').oninput=()=>{page=0;renderReview();};$('previous').onclick=()=>{page--;renderReview();};$('next').onclick=()=>{page++;renderReview();};
$('rows').onchange=e=>{if(e.target.dataset.approve){const r=working.find(r=>r.id===Number(e.target.dataset.approve));if(r?.status==='READY'){snapshot();r.approved=e.target.checked;changed();}}};
$('rows').onclick=e=>{const edit=e.target.closest('[data-edit]'),exclude=e.target.closest('[data-exclude]');if(edit)openEdit(Number(edit.dataset.edit));if(exclude){snapshot();const r=working.find(r=>r.id===Number(exclude.dataset.exclude));r.excluded=!r.excluded;r.approved=false;changed();}};
function openEdit(id){editing=id;const r=working.find(r=>r.id===id);setText('edit-title',L(`Edit source row ${r.sourceRow}`,`Kaynak satırı düzenle: ${r.sourceRow}`));
  $('edit-fields').innerHTML=COLUMNS.map(k=>{let value=r[k];if(['price','stock','min','max'].includes(k)&&value){const parsed=parseNumber(value,r.numberFormats?.[k]||format);if(parsed.ok)value=parsed.value;}return `<label class="${k==='description'?'wide':''}">${esc(field(k))}${k==='description'?`<textarea data-edit-field="${k}" maxlength="2000" rows="3">${esc(value)}</textarea>`:`<input data-edit-field="${k}" value="${esc(value)}" maxlength="2000" autocomplete="off" ${['price','stock','min','max'].includes(k)?'inputmode="decimal"':''}>`}</label>`;}).join('');$('edit-dialog').showModal();}
$('edit-form').onsubmit=e=>{e.preventDefault();const r=working.find(r=>r.id===editing);snapshot();r.numberFormats={...r.numberFormats};document.querySelectorAll('[data-edit-field]').forEach(input=>{const key=input.dataset.editField;const prior=parseNumber(r[key],r.numberFormats[key]||format);if(['price','stock','min','max'].includes(key)&&(input.value!==r[key]||prior.ok))r.numberFormats[key]='canonical';r[key]=input.value;});r.approved=false;$('edit-dialog').close();changed();};
$('approve-ready').onclick=()=>{snapshot();for(const r of working)if(r.status==='READY')r.approved=true;changed();$('export-panel').scrollIntoView({block:'nearest',behavior:'smooth'});};
$('undo').onclick=()=>{if(!previous)return;working=previous;previous=null;$('undo').disabled=true;changed();};
$('fixes').onclick=()=>{proposal=safeFixes(working,format);setText('fix-summary',L(`${proposal.changes.length} changes. Whitespace, currency casing and unambiguous numeric formats only. Codes and duplicates are never merged.`,`${proposal.changes.length} değişiklik. Yalnızca boşluklar, para birimi harfleri ve açık sayı biçimleri düzeltilir. Kodlar ve yinelenen satırlar birleştirilmez.`));$('fix-list').innerHTML=proposal.changes.length?`<table><thead><tr><th>${L('Row / field','Satır / alan')}</th><th>${L('Before','Önce')}</th><th>${L('After','Sonra')}</th></tr></thead><tbody>${proposal.changes.slice(0,100).map(c=>`<tr><td>${c.sourceRow} · ${esc(field(c.field))}</td><td><code>${esc(JSON.stringify(c.before))}</code></td><td><code>${esc(JSON.stringify(c.after))}</code></td></tr>`).join('')}</tbody></table>${proposal.changes.length>100?`<p>${L('Showing the first 100 changes.','İlk 100 değişiklik gösteriliyor.')}</p>`:''}`:L('No formatting changes are needed.','Biçim değişikliği gerekmiyor.');$('apply-fixes').disabled=!proposal.changes.length;$('fix-dialog').showModal();};
$('apply-fixes').onclick=()=>{if(!proposal?.changes.length)return;snapshot();working=proposal.rows;proposal=null;$('fix-dialog').close();changed();};
$('issues-report').onclick=()=>{const report=working.filter(r=>r.status==='REVIEW').flatMap(r=>r.issues.map(i=>({source_row:r.sourceRow,sku:r.sku,field:i.field,issue:issueText(i)})));download(serializeCsv(report,['source_row','sku','field','issue']),'SKU-Bridge-issue-report.csv');};
$('export').onclick=()=>{setText('confirm-summary',summary());$('confirm-check').checked=false;$('confirm-export').disabled=true;$('export-dialog').showModal();};
$('confirm-check').onchange=()=>{$('confirm-export').disabled=!$('confirm-check').checked;};
$('confirm-export').onclick=async()=>{if(busy||!$('confirm-check').checked)return;$('export-dialog').close();busy=true;$('export').disabled=true;setText('sku-export-message',L('Verifying access and preparing your CSV…','Erişim doğrulanıyor ve CSV hazırlanıyor…'));try{const approved=exportRows(reviewRows(working,format),format);if(!window.SkuSandbox){setText('sku-export-message',L('Export is not connected on this preview. Open the local fulfillment server to use your test account.','Bu önizlemede dışa aktarma bağlı değil. Test hesabınız için yerel fulfillment sunucusunu açın.'));return;}if(await window.SkuSandbox.exportRows(approved))step(4);}catch{setText('sku-export-message',L('Export did not finish. Refresh access and try again.','Dışa aktarma tamamlanmadı. Erişimi yenileyip tekrar deneyin.'));}finally{busy=false;renderReview();}};
$('refresh-access').onclick=()=>window.SkuSandbox?.refresh();
$('remap').onclick=()=>resetThen(()=>{clearReview();$('mapping-panel').hidden=false;step(2);});
$('reset').onclick=()=>resetThen(()=>{clearReview();source=null;table=null;$('mapping-panel').hidden=true;$('import-panel').hidden=false;notice();step(1);});
const sample='SKU;Description;Barcode;Unit;Price;Currency;Stock;Warehouse;Min;Max\r\n RAW-100 ;Fresh figs;4006381333931;kg;1,05;eur;12500;Raw materials;10;20000\r\nPKG-020;Gift carton;;piece;2,50;EUR;200;Packaging;20;500\r\nDUP-101;Blue mug;;piece;4,90;EUR;30;Main;5;100\r\nDUP-101;Blue mug duplicate;;piece;4,90;EUR;30;Main;5;100\r\nPRICE-7;Missing price;;piece;;EUR;12;Main;;\r\nBAR-8;Check barcode;123456789;piece;8,50;EUR;5;Main;;\r\nRANGE-9;Stock limit conflict;;piece;7,00;EUR;25;Main;100;20\r\nZERO-1;Zero is a valid price;;piece;0;EUR;0;Main;0;0\r\n';
$('sample').onclick=()=>resetThen(()=>loadFile(new File([sample],'SKU-Bridge-sample.csv',{type:'text/csv'})));
$('language').onchange=()=>{lang=$('language').value;document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=lang==='tr'?tr[el.dataset.i18n]||defaults.get(el.dataset.i18n):defaults.get(el.dataset.i18n));$('search').placeholder=L('Search SKU, name or barcode','SKU, ad veya barkod ara');if(table)renderMapping(mapping());if(working.length)renderReview();window.SkuSandbox?.refresh();};
window.addEventListener('beforeunload',event=>{if(working.length){event.preventDefault();event.returnValue='';}});
if(window.SkuSandbox){setText('environment','Paddle sandbox · v5');window.SkuSandbox.refresh();}else{$('checkout-link').hidden=true;$('refresh-access').hidden=true;}
