(function(root){
  'use strict';
  const n=v=>{const x=Number(String(v??'').replace(/,/g,''));return Number.isFinite(x)?x:0};
  function calculate(items,costs,targetMargin=25){
    const cleanItems=items.map((x,i)=>({...x,_i:i,qty:n(x.qty),weight:n(x.weight),volume:n(x.volume),estUnit:n(x.estUnit),actualUnit:n(x.actualUnit),selling:n(x.selling)}));
    const bases={quantity:cleanItems.reduce((s,x)=>s+x.qty,0),weight:cleanItems.reduce((s,x)=>s+x.weight,0),volume:cleanItems.reduce((s,x)=>s+x.volume,0),estimatedValue:cleanItems.reduce((s,x)=>s+x.qty*x.estUnit,0),actualValue:cleanItems.reduce((s,x)=>s+x.qty*x.actualUnit,0)};
    const rows=cleanItems.map(x=>({...x,estMerch:x.qty*x.estUnit,actualMerch:x.qty*x.actualUnit,estAllocated:0,actualAllocated:0,allocations:[]}));
    const controls=[], causes=[{category:'Merchandise purchase cost',variance:bases.actualValue-bases.estimatedValue}];
    const allocationShare=(x,basis,side)=>{
      let value,total;
      if(basis==='value'){value=side==='est'?x.estMerch:x.actualMerch;total=side==='est'?bases.estimatedValue:bases.actualValue}
      else {value=x[basis]||0;total=bases[basis]||0}
      if(total>0)return value/total;
      return rows.length?1/rows.length:0;
    };
    costs.forEach((c,ci)=>{
      const est=n(c.estimated),actual=n(c.actual),basis=['value','weight','volume','quantity'].includes(c.basis)?c.basis:'value';
      if((basis==='weight'&&!bases.weight)||(basis==='volume'&&!bases.volume)||(basis==='quantity'&&!bases.quantity)||(basis==='value'&&(!bases.estimatedValue||!bases.actualValue)))controls.push({level:'warning',text:`${c.category||`Cost ${ci+1}`}: ${basis} basis is zero on at least one side; equal allocation was used.`});
      rows.forEach(x=>{const ea=est*allocationShare(x,basis,'est'),aa=actual*allocationShare(x,basis,'actual');x.estAllocated+=ea;x.actualAllocated+=aa;x.allocations.push({category:c.category,estimated:ea,actual:aa})});
      causes.push({category:c.category||`Cost ${ci+1}`,variance:actual-est});
      if(est>0&&actual===0)controls.push({level:'warning',text:`${c.category}: actual cost is missing or zero.`});
    });
    const refs=new Map();costs.forEach(c=>{const ref=String(c.reference||'').trim().toLowerCase();if(ref){refs.set(ref,(refs.get(ref)||0)+1)}});refs.forEach((count,ref)=>{if(count>1)controls.push({level:'error',text:`Possible duplicate invoice/reference: ${ref} appears ${count} times.`})});
    const skus=new Map();rows.forEach(x=>{const sku=String(x.sku||'').trim().toLowerCase();if(!sku)controls.push({level:'error',text:`Row ${x._i+1}: SKU is missing.`});else skus.set(sku,(skus.get(sku)||0)+1);if(x.qty<=0)controls.push({level:'error',text:`${x.sku||`Row ${x._i+1}`}: quantity must be greater than zero.`});if(x.actualUnit<=0)controls.push({level:'warning',text:`${x.sku||`Row ${x._i+1}`}: actual merchandise cost is missing.`})});skus.forEach((count,sku)=>{if(count>1)controls.push({level:'error',text:`Duplicate SKU: ${sku} appears ${count} times.`})});
    rows.forEach(x=>{x.estTotal=x.estMerch+x.estAllocated;x.actualTotal=x.actualMerch+x.actualAllocated;x.estPerUnit=x.qty?x.estTotal/x.qty:0;x.actualPerUnit=x.qty?x.actualTotal/x.qty:0;x.variance=x.actualTotal-x.estTotal;x.variancePerUnit=x.qty?x.variance/x.qty:0;x.margin=x.selling>0?(x.selling-x.actualPerUnit)/x.selling*100:0;x.requiredPrice=targetMargin<100?x.actualPerUnit/(1-targetMargin/100):0});
    const estimated=rows.reduce((s,x)=>s+x.estTotal,0),actual=rows.reduce((s,x)=>s+x.actualTotal,0),variance=actual-estimated,sales=rows.reduce((s,x)=>s+x.selling*x.qty,0);
    return{rows,estimated,actual,variance,variancePct:estimated?variance/estimated*100:0,averageMargin:sales?(sales-actual)/sales*100:0,controls,causes:causes.filter(x=>Math.abs(x.variance)>.000001).sort((a,b)=>Math.abs(b.variance)-Math.abs(a.variance)).slice(0,5)};
  }
  const Engine={calculate}; if(typeof module!=='undefined'&&module.exports)module.exports=Engine; root.CostCloseEngine=Engine;
  if(typeof document==='undefined')return;
  const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=(v,c)=>`${c} ${n(v).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  let state={id:'',createdAt:'',method:'Manual web entry',revisions:0,reviewedAt:'',reviewedBy:'',items:[],costs:[]};
  const demos={
    cosmetics:{ref:'IMP-US-2026-041',origin:'Shenzhen, China',destination:'Houston, United States',currency:'USD',items:[{sku:'COS-118',description:'Private-label face serum',qty:6000,weight:2100,volume:11.8,estUnit:4.85,actualUnit:5.02,selling:8.25},{sku:'COS-220',description:'Vitamin C cream',qty:4000,weight:1620,volume:8.4,estUnit:3.9,actualUnit:4.03,selling:6.8},{sku:'PKG-610',description:'Retail cosmetic display set',qty:2000,weight:980,volume:7.1,estUnit:2.1,actualUnit:2.18,selling:4.2}],costs:[{category:'International freight',reference:'FRT-8841',estimated:4350,actual:6200,basis:'volume'},{category:'Cargo insurance',reference:'INS-410',estimated:390,actual:445,basis:'value'},{category:'Customs duty',reference:'CBP-7501-041',estimated:2450,actual:3740,basis:'value'},{category:'Broker and port fees',reference:'BRK-982',estimated:980,actual:1740,basis:'quantity'},{category:'Bank and FX costs',reference:'BANK-SEP',estimated:410,actual:920,basis:'value'}]},
    apparel:{ref:'IMP-US-2026-052',origin:'Istanbul, Türkiye',destination:'Newark, United States',currency:'USD',items:[{sku:'TSH-220',description:'Organic cotton T-shirts',qty:5000,weight:1100,volume:9.2,estUnit:3.1,actualUnit:3.18,selling:6.25},{sku:'HDY-410',description:'Cotton hoodies',qty:1800,weight:1260,volume:8.8,estUnit:8.4,actualUnit:8.65,selling:16.5}],costs:[{category:'International freight',reference:'FRT-9012',estimated:3100,actual:3550,basis:'volume'},{category:'Cargo insurance',reference:'INS-455',estimated:260,actual:275,basis:'value'},{category:'Customs duty',reference:'CBP-7501-052',estimated:5200,actual:5710,basis:'value'},{category:'Broker and port fees',reference:'BRK-1044',estimated:720,actual:860,basis:'quantity'}]},
    parts:{ref:'IMP-CA-2026-017',origin:'Hamburg, Germany',destination:'Toronto, Canada',currency:'CAD',items:[{sku:'BRG-6204',description:'Industrial bearing 6204-2RS',qty:800,weight:190,volume:.8,estUnit:6.4,actualUnit:6.58,selling:11.9},{sku:'SNS-088',description:'Temperature sensor assembly',qty:350,weight:72,volume:.4,estUnit:24,actualUnit:25.2,selling:42}],costs:[{category:'International freight',reference:'FRT-CA-77',estimated:1800,actual:2140,basis:'weight'},{category:'Cargo insurance',reference:'INS-CA-22',estimated:180,actual:195,basis:'value'},{category:'Customs duty',reference:'B3-017',estimated:760,actual:890,basis:'value'},{category:'Broker and terminal fees',reference:'BRK-CA-17',estimated:490,actual:640,basis:'quantity'}]}
  };
  function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.add('hidden'),2200)}
  function reportId(){return`CC-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${Math.random().toString(36).slice(2,7).toUpperCase()}`}
  function persist(){localStorage.setItem('hamvara_costclose_draft',JSON.stringify({state,identity:{generatedBy:$('generatedBy').value,company:$('company').value,email:$('email').value,shipmentRef:$('shipmentRef').value,origin:$('origin').value,destination:$('destination').value,currency:$('currency').value,targetMargin:$('targetMargin').value}}))}
  function touch(){state.revisions++;state.reviewedAt='';state.reviewedBy='';persist();render()}
  function renderInputs(){
    $('skuCount').textContent=`${state.items.length} / 10 SKU`;
    $('itemRows').innerHTML=state.items.map((x,i)=>`<tr data-i="${i}"><td><input class="wide" data-type="item" data-k="sku" value="${esc(x.sku)}"></td><td><input class="wide" data-type="item" data-k="description" value="${esc(x.description)}"></td><td><input data-type="item" data-k="qty" type="number" min="0" step="any" value="${n(x.qty)}"></td><td><input data-type="item" data-k="weight" type="number" min="0" step="any" value="${n(x.weight)}"></td><td><input data-type="item" data-k="volume" type="number" min="0" step="any" value="${n(x.volume)}"></td><td><input data-type="item" data-k="estUnit" type="number" min="0" step="any" value="${n(x.estUnit)}"></td><td><input data-type="item" data-k="actualUnit" type="number" min="0" step="any" value="${n(x.actualUnit)}"></td><td><input data-type="item" data-k="selling" type="number" min="0" step="any" value="${n(x.selling)}"></td><td><button class="del" data-del-item="${i}">Delete</button></td></tr>`).join('');
    $('costRows').innerHTML=state.costs.map((x,i)=>`<tr data-i="${i}"><td><input class="wide" data-type="cost" data-k="category" value="${esc(x.category)}"></td><td><input class="wide" data-type="cost" data-k="reference" value="${esc(x.reference)}"></td><td><input data-type="cost" data-k="estimated" type="number" min="0" step="any" value="${n(x.estimated)}"></td><td><input data-type="cost" data-k="actual" type="number" min="0" step="any" value="${n(x.actual)}"></td><td><select data-type="cost" data-k="basis"><option value="value" ${x.basis==='value'?'selected':''}>Merchandise value</option><option value="weight" ${x.basis==='weight'?'selected':''}>Weight</option><option value="volume" ${x.basis==='volume'?'selected':''}>Volume</option><option value="quantity" ${x.basis==='quantity'?'selected':''}>Quantity</option></select></td><td><button class="del" data-del-cost="${i}">Delete</button></td></tr>`).join('');
    document.querySelectorAll('[data-type]').forEach(el=>el.addEventListener('change',e=>{const type=e.target.dataset.type,k=e.target.dataset.k,i=Number(e.target.closest('tr').dataset.i),obj=type==='item'?state.items[i]:state.costs[i];obj[k]=['qty','weight','volume','estUnit','actualUnit','selling','estimated','actual'].includes(k)?n(e.target.value):e.target.value;touch()}));
    document.querySelectorAll('[data-del-item]').forEach(b=>b.onclick=()=>{state.items.splice(Number(b.dataset.delItem),1);touch()});document.querySelectorAll('[data-del-cost]').forEach(b=>b.onclick=()=>{state.costs.splice(Number(b.dataset.delCost),1);touch()});
  }
  function result(){return calculate(state.items,state.costs,n($('targetMargin').value))}
  function render(){
    renderInputs();const r=result(),c=$('currency').value;
    $('estimatedTotal').textContent=money(r.estimated,c);$('actualTotal').textContent=money(r.actual,c);$('varianceTotal').textContent=`${r.variance>=0?'+':''}${money(r.variance,c)}`;$('variancePct').textContent=`${r.variancePct>=0?'+':''}${r.variancePct.toFixed(2)}%`;$('averageMargin').textContent=`${r.averageMargin.toFixed(1)}%`;$('issueCount').textContent=r.controls.length;$('varianceCard').className=`metric ${r.variance>0?'bad':'good'}`;$('issuesCard').className=`metric ${r.controls.some(x=>x.level==='error')?'bad':r.controls.length?'':'good'}`;
    $('findings').innerHTML=r.causes.length?r.causes.map(x=>`<div class="finding"><span>${esc(x.category)}</span><b class="${x.variance>0?'positive':'negative'}">${x.variance>=0?'+':''}${money(x.variance,c)}</b></div>`).join(''):'<p>No cost variance entered.</p>';
    $('controls').innerHTML=r.controls.length?r.controls.map(x=>`<div class="finding"><span>${x.level==='error'?'⛔':'⚠️'} ${esc(x.text)}</span></div>`).join(''):'<div class="finding"><span>✓ No blocking or warning conditions detected.</span></div>';
    $('resultRows').innerHTML=r.rows.map(x=>`<tr><td><b>${esc(x.sku||'—')}</b></td><td>${money(x.estPerUnit,c)}</td><td>${money(x.actualPerUnit,c)}</td><td>${x.variancePerUnit>=0?'+':''}${money(x.variancePerUnit,c)}</td><td>${money(x.selling,c)}</td><td>${x.margin.toFixed(1)}%</td><td><b>${money(x.requiredPrice,c)}</b></td></tr>`).join('');
    $('reviewState').textContent=state.reviewedAt?'REVIEWED':'DRAFT · REVIEW REQUIRED';$('reviewState').className=`status ${state.reviewedAt?'reviewed':'draft'}`;$('auditId').textContent=state.id||'—';$('auditUser').textContent=$('generatedBy').value||'—';$('auditMethod').textContent=state.method;$('auditRevision').textContent=`${state.revisions} · ${state.reviewedAt?'REVIEWED':'DRAFT'}`;$('auditTime').textContent=state.createdAt?new Date(state.createdAt).toLocaleString():'—';$('auditReview').textContent=state.reviewedAt?`${state.reviewedBy} · ${new Date(state.reviewedAt).toLocaleString()}`:'Not reviewed';persist();
  }
  function loadDemo(){const d=demos[$('demoType').value];state={id:reportId(),createdAt:new Date().toISOString(),method:'Built-in realistic demonstration',revisions:0,reviewedAt:'',reviewedBy:'',items:JSON.parse(JSON.stringify(d.items)),costs:JSON.parse(JSON.stringify(d.costs))};$('shipmentRef').value=d.ref;$('origin').value=d.origin;$('destination').value=d.destination;$('currency').value=d.currency;render();toast('Realistic shipment loaded; every value is editable')}
  function validForReview(){const r=result();if(!$('generatedBy').value.trim()||!$('company').value.trim()||!$('shipmentRef').value.trim()){toast('Complete report owner, company and shipment reference');return false}if(!state.items.length){toast('Add at least one SKU');return false}if(r.controls.some(x=>x.level==='error')){toast('Resolve blocking control findings first');return false}return true}
  $('loadDemo').onclick=loadDemo;$('calculate').onclick=()=>{state.revisions++;render();toast('Analysis recalculated')};$('addItem').onclick=()=>{if(state.items.length>=10)return toast('Free beta limit: 10 SKU');state.items.push({sku:'',description:'',qty:1,weight:0,volume:0,estUnit:0,actualUnit:0,selling:0});touch()};$('addCost').onclick=()=>{state.costs.push({category:'Other import cost',reference:'',estimated:0,actual:0,basis:'value'});touch()};$('approve').onclick=()=>{if(!validForReview())return;state.reviewedAt=new Date().toISOString();state.reviewedBy=$('generatedBy').value.trim();render();toast('Report marked reviewed')};$('print').onclick=()=>window.print();
  $('download').onclick=()=>{if(!state.items.length)return toast('Load or enter a shipment first');const r=result(),c=$('currency').value,head=['report_id','status','generated_by','company','method','shipment','origin','destination','sku','description','quantity','estimated_landed_unit','actual_landed_unit','variance_unit','selling_price','actual_margin_percent','target_price','currency'],rows=r.rows.map(x=>[state.id,state.reviewedAt?'REVIEWED':'DRAFT',$('generatedBy').value,$('company').value,state.method,$('shipmentRef').value,$('origin').value,$('destination').value,x.sku,x.description,x.qty,x.estPerUnit,x.actualPerUnit,x.variancePerUnit,x.selling,x.margin,x.requiredPrice,c]),csv=[head,...rows].map(row=>row.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`${state.id||'CostClose-report'}.csv`;a.click();URL.revokeObjectURL(a.href)};
  $('reset').onclick=()=>{if(!confirm('Clear this browser draft and start over?'))return;localStorage.removeItem('hamvara_costclose_draft');state={id:reportId(),createdAt:new Date().toISOString(),method:'Manual web entry',revisions:0,reviewedAt:'',reviewedBy:'',items:[],costs:[]};render()};
  ['generatedBy','company','email','shipmentRef','origin','destination','currency','targetMargin'].forEach(id=>$(id).addEventListener('change',()=>touch()));
  try{const saved=JSON.parse(localStorage.getItem('hamvara_costclose_draft')||'null');if(saved?.state){state=saved.state;Object.entries(saved.identity||{}).forEach(([k,v])=>{if($(k))$(k).value=v});render()}else loadDemo()}catch{loadDemo()}
})(typeof window!=='undefined'?window:globalThis);
