import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {cashflowSources,buildBusinessCashflow,createBusinessCashflowPlan,reviewBusinessCashflowPlan,approveBusinessCashflowPlan} from '../../mrp/business-cashflow.js';

const sample=()=>({whatIfSimulations:[{id:'W1',simulationNo:'WIF-00001',name:'Accepted stress',status:'ACCEPTED',rows:[{period:'2026-09',revenue:1000,productionCost:500},{period:'2026-10',revenue:1200,productionCost:600}]}],sopPlans:[{id:'S1',planNo:'SOP-00001',scenario:'BASE',status:'APPROVED',rows:[{period:'2026-09',projectedRevenue:900,projectedProductionCost:450}]}],businessCashflowPlans:[],auditTrail:[]});
test('cash-flow sources include only controlled accepted plans',()=>{const state=sample();state.whatIfSimulations.push({id:'W2',status:'DRAFT',rows:[]});assert.deepEqual(cashflowSources(state).map(item=>item.id),['W1','S1'])});
test('cash-flow phases collections and supplier payments by terms',()=>{const result=buildBusinessCashflow(sample(),{sourceId:'W1',openingCash:1000,customerCollectionDays:30,supplierPaymentDays:30,materialCostSharePercent:60,monthlyFixedOpex:100,monthlyCapex:50,minimumCash:300});assert.equal(result.rows[0].collections,0);assert.equal(result.rows[0].materialPayments,0);assert.equal(result.rows[1].collections,1000);assert.equal(result.rows[1].materialPayments,300);assert.equal(result.rows[0].endingCash,650)});
test('cash-flow flags the peak funding requirement',()=>{const result=buildBusinessCashflow(sample(),{sourceId:'W1',openingCash:0,customerCollectionDays:60,supplierPaymentDays:0,materialCostSharePercent:100,monthlyFixedOpex:100,minimumCash:200});assert.equal(result.status,'FUNDING_REQUIRED');assert.ok(result.totals.peakFundingGap>0);assert.equal(result.totals.fundingMonths,2)});
test('plan snapshot and approval require three independent identities',()=>{const state=sample(),item=createBusinessCashflowPlan(state,{sourceId:'W1',name:'Annual cash plan',preparedBy:'planner',assumptionsNote:'Current approved commercial assumptions'});assert.throws(()=>reviewBusinessCashflowPlan(state,item.id,{reviewedBy:'planner',reviewNote:'Reviewed working capital assumptions'}),/independent/i);reviewBusinessCashflowPlan(state,item.id,{reviewedBy:'controller',reviewNote:'Reviewed working capital assumptions'});assert.throws(()=>approveBusinessCashflowPlan(state,item.id,{approvedBy:'controller',fundingDecision:'Maintain minimum cash reserve'}),/independent/i);approveBusinessCashflowPlan(state,item.id,{approvedBy:'ceo',fundingDecision:'Maintain minimum cash reserve through the horizon'});assert.equal(item.status,'APPROVED')});
test('cash-flow interface identifiers are unique',()=>{const html=readFileSync(new URL('../../mrp/index.html',import.meta.url),'utf8');for(const id of ['cashflowSource','cashflowName','cashflowOpening','cashflowCollectionDays','cashflowSupplierDays','cashflowMaterialShare','cashflowFixedOpex','cashflowCapex','cashflowMinimum','cashflowPreparer','cashflowReviewer','cashflowApprover','cashflowAssumptions','cashflowReviewNote','cashflowFundingDecision','createCashflowPlan','cashflowKpis','cashflowTable','cashflowClaim','cashflowRegister'])assert.equal((html.match(new RegExp(`id="${id}"`,'g'))||[]).length,1)});
