import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {buildDetailedSchedule,createDowntimeWindow,createProductionSchedule,releaseProductionSchedule} from '../../mrp/detailed-production-scheduling.js';
function sample(){return{mpsSnapshots:[{status:'FROZEN'}],shiftCalendars:[{code:'A',dailyHours:8,workDays:5,efficiencyPercent:100,active:true}],workCenters:[{id:'WC1',code:'CUT',name:'Cutting',shiftCode:'A',shiftStartHour:8,machineCount:1,changeoverMinutes:15,active:true},{id:'WC2',code:'ALT',name:'Alternative',shiftCode:'A',shiftStartHour:8,machineCount:1,changeoverMinutes:10,active:true}],productRoutings:[{id:'R1',productCode:'P1',sequence:1,operationCode:'CUT',workCenterId:'WC1',alternativeWorkCenterIds:['WC2'],setupMinutes:0,runMinutesPerUnit:60,active:true},{id:'R2',productCode:'P1',sequence:2,operationCode:'PACK',workCenterId:'WC1',setupMinutes:0,runMinutesPerUnit:60,active:true}],productionJobs:[{id:'J1',workOrderNo:'WO-1',productCode:'P1',plannedQty:1,completedQty:0,priority:'URGENT',dueDate:'2026-09-20',status:'PLANNED'}],machineDowntimeCalendars:[],productionSchedules:[],auditTrail:[]}}
test('detailed schedule preserves operation precedence',()=>{const plan=buildDetailedSchedule(sample(),{startAt:'2026-09-14T08:00:00Z'});assert.equal(plan.operations.length,2);assert.ok(new Date(plan.operations[1].startAt)>=new Date(plan.operations[0].endAt))});
test('planned downtime removes blocked time from the work-center calendar',()=>{const state=sample();createDowntimeWindow(state,{workCenterId:'WC1',startAt:'2026-09-14T08:00:00Z',endAt:'2026-09-14T10:00:00Z',reason:'Preventive maintenance'});const plan=buildDetailedSchedule(state,{startAt:'2026-09-14T08:00:00Z'});assert.equal(plan.operations[0].startAt,'2026-09-14T08:00:00.000Z');assert.equal(plan.operations[0].workCenterId,'WC2');assert.equal(plan.operations[1].startAt,'2026-09-14T10:00:00.000Z')});
test('scheduler assigns an alternative center when it provides the earliest slot',()=>{const state=sample();state.productionJobs.push({id:'J2',workOrderNo:'WO-2',productCode:'P1',plannedQty:1,completedQty:0,priority:'NORMAL',dueDate:'2026-09-20',status:'PLANNED'});state.productRoutings=[state.productRoutings[0]];const plan=buildDetailedSchedule(state,{startAt:'2026-09-14T08:00:00Z'});assert.equal(plan.operations[0].workCenterId,'WC1');assert.equal(plan.operations[1].workCenterId,'WC2');assert.equal(plan.totals.alternativeAssignments,1)});
test('long operations continue in the next working shift',()=>{const state=sample();state.productionJobs[0].plannedQty=10;state.productRoutings=[state.productRoutings[0]];const row=buildDetailedSchedule(state,{startAt:'2026-09-14T08:00:00Z'}).operations[0];assert.equal(row.endAt,'2026-09-15T10:00:00.000Z')});
test('schedule creation requires frozen MPS and independent release',()=>{const state=sample();state.mpsSnapshots=[];assert.throws(()=>createProductionSchedule(state,{startAt:'2026-09-14T08:00:00Z',preparedBy:'scheduler'}),/frozen MPS/);state.mpsSnapshots=[{status:'FROZEN'}];const item=createProductionSchedule(state,{startAt:'2026-09-14T08:00:00Z',preparedBy:'scheduler'});assert.throws(()=>releaseProductionSchedule(state,item.id,{releasedBy:'scheduler'}),/independent/);releaseProductionSchedule(state,item.id,{releasedBy:'production-manager'});assert.equal(item.status,'RELEASED');assert.equal(state.auditTrail.length,2)});
test('detailed scheduling interface identifiers are unique',()=>{const html=readFileSync(new URL('../../mrp/index.html',import.meta.url),'utf8');for(const id of ['scheduleStartAt','schedulePlanner','scheduleApprover','generateDetailedSchedule','detailedScheduleKpis','productionGantt','detailedScheduleTable','downtimeWorkCenter','downtimeStartAt','downtimeEndAt','downtimeReason','addDowntimeWindow','downtimeCalendarTable','productionScheduleRegister'])assert.equal((html.match(new RegExp(`id="${id}"`,'g'))||[]).length,1)});
