import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {REQUIRED_SCENARIOS,createFactoryAcceptanceCampaign,recordAcceptanceScenario,addAcceptanceDefect,closeAcceptanceDefect,factoryAcceptanceSummary,submitFactoryAcceptance,approveFactoryAcceptance} from '../../mrp/factory-acceptance.js';

const state=()=>({factoryAcceptanceCampaigns:[],auditTrail:[]});
const campaign=s=>createFactoryAcceptanceCampaign(s,{site:'Istanbul Pilot Factory',pilotOwner:'pilot-lead',scopeNote:'Full real-factory acceptance scope'});
const passAll=(s,item)=>REQUIRED_SCENARIOS.forEach(([code])=>recordAcceptanceScenario(s,item.id,code,{status:'PASS',evidence:`Controlled evidence recorded for ${code}`,executedBy:'key-user'}));

test('campaign starts with the complete mandatory factory scenario set',()=>{const s=state(),item=campaign(s),summary=factoryAcceptanceSummary(item);assert.equal(summary.total,10);assert.equal(summary.notRun,10);assert.equal(summary.ready,false)});
test('failed or unexecuted scenarios block submission',()=>{const s=state(),item=campaign(s);recordAcceptanceScenario(s,item.id,'FAT-01',{status:'FAIL',evidence:'Import reconciliation did not balance',executedBy:'key-user'});assert.throws(()=>submitFactoryAcceptance(s,item.id,{submittedBy:'pilot-lead',submissionNote:'Submit completed factory evidence'}),/blocked/i)});
test('high defect blocks acceptance until resolution evidence closes it',()=>{const s=state(),item=campaign(s);passAll(s,item);const defect=addAcceptanceDefect(s,item.id,{severity:'HIGH',title:'Inventory transfer balance mismatch',owner:'warehouse-lead'});assert.equal(factoryAcceptanceSummary(item).ready,false);closeAcceptanceDefect(s,item.id,defect.id,{closedBy:'qa-lead',resolution:'Retested transfer and reconciled both ledgers'});assert.equal(factoryAcceptanceSummary(item).ready,true)});
test('approval requires an independent approver',()=>{const s=state(),item=campaign(s);passAll(s,item);submitFactoryAcceptance(s,item.id,{submittedBy:'pilot-lead',submissionNote:'All scenarios passed with retained evidence'});assert.throws(()=>approveFactoryAcceptance(s,item.id,{approvedBy:'pilot-lead',acceptanceNote:'Approve operational pilot acceptance'}),/independent/i);approveFactoryAcceptance(s,item.id,{approvedBy:'factory-manager',acceptanceNote:'Approve controlled operational pilot acceptance'});assert.equal(item.status,'APPROVED')});
test('factory acceptance interface identifiers are unique',()=>{const html=readFileSync(new URL('../../mrp/index.html',import.meta.url),'utf8');for(const id of ['factoryAcceptanceStatus','fatSite','fatOwner','fatExecutor','fatApprover','fatScope','fatEvidence','fatSubmissionNote','fatAcceptanceNote','createFactoryAcceptance','factoryAcceptanceKpis','factoryAcceptanceScenarios','fatDefectSeverity','fatDefectTitle','fatDefectOwner','fatDefectCloser','fatDefectResolution','addFactoryDefect','factoryAcceptanceDefects','factoryAcceptanceRegister'])assert.equal((html.match(new RegExp(`id="${id}"`,'g'))||[]).length,1)});
