import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createInventoryTransaction,submitInventoryTransaction,approveInventoryTransaction,postInventoryTransaction,reverseInventoryTransaction} from '../../mrp/inventory-issue-transfer.js';
import {createAccountingPeriod,normalizeFinancialState} from '../../mrp/financial-core.js';
import {receiveInventoryCost,setInventoryCostMethod} from '../../mrp/inventory-costing.js';

function sample({tracked=false,policy='FIFO',profile='IFRS_TFRS'}={}){const value={settings:{currency:'USD'},accountingSettings:{profile,baseCurrency:'USD'},warehouses:[{code:'WH-RM'},{code:'WH-SF'}],skus:[{code:'RM-1',name:'Resin',cost:5,lotTracked:tracked,serialTracked:false,issuePolicy:policy}],stock:{'RM-1':{'WH-RM':20,'WH-SF':0,reserved:2}},inventoryLots:tracked?[{id:'L1',sku:'RM-1',warehouse:'WH-RM',lotNo:'OLD',receivedAt:'2026-08-01',expiryDate:'2026-12-01',quantity:8},{id:'L2',sku:'RM-1',warehouse:'WH-RM',lotNo:'NEW',receivedAt:'2026-09-01',expiryDate:'2026-10-01',quantity:12}]:[],inventoryTransactions:[],inventoryMovements:[],auditTrail:[]};normalizeFinancialState(value);createAccountingPeriod(value,{id:'P1',code:'2026-09',startDate:'2026-09-01',endDate:'2026-09-30'});return value}
function approved(state,input={}){const transaction=createInventoryTransaction(state,{type:'ISSUE',sku:'RM-1',sourceWarehouse:'WH-RM',quantity:5,reason:'Maintenance use',requestedBy:'operator',createdAt:'2026-09-11T08:00:00Z',...input});submitInventoryTransaction(state,transaction.id,{submittedBy:'operator',at:'2026-09-11T08:10:00Z'});approveInventoryTransaction(state,transaction.id,{approvedBy:'manager',at:'2026-09-11T08:20:00Z'});return transaction}

test('controlled issue requires independent approval and preserves an auditable workflow',()=>{const state=sample(),transaction=createInventoryTransaction(state,{sku:'RM-1',sourceWarehouse:'WH-RM',quantity:5,reason:'Maintenance use',requestedBy:'operator',createdAt:'2026-09-11T08:00:00Z'});submitInventoryTransaction(state,transaction.id,{submittedBy:'operator'});assert.throws(()=>approveInventoryTransaction(state,transaction.id,{approvedBy:'operator'}),/independent/);approveInventoryTransaction(state,transaction.id,{approvedBy:'manager'});assert.throws(()=>postInventoryTransaction(state,transaction.id,{postedBy:'operator'}),/different/);postInventoryTransaction(state,transaction.id,{postedBy:'warehouse-manager',at:'2026-09-11T09:00:00Z'});assert.equal(state.stock['RM-1']['WH-RM'],15);assert.equal(transaction.status,'POSTED');assert.equal(state.inventoryMovements[0].type,'CONTROLLED_INVENTORY_ISSUE');assert.equal(state.auditTrail[0].action,'INVENTORY_TRANSACTION_POSTED')});

test('available stock excludes reservations before posting',()=>{const state=sample(),transaction=approved(state,{quantity:19});assert.throws(()=>postInventoryTransaction(state,transaction.id,{postedBy:'warehouse-manager'}),/shortage 1/);assert.equal(state.stock['RM-1']['WH-RM'],20);assert.equal(transaction.status,'APPROVED')});

test('warehouse transfer follows FEFO and carries the lot to its destination',()=>{const state=sample({tracked:true,policy:'FEFO'}),transaction=approved(state,{type:'TRANSFER',destinationWarehouse:'WH-SF',quantity:5,reason:'Production replenishment'});postInventoryTransaction(state,transaction.id,{postedBy:'warehouse-manager',at:'2026-09-11T09:00:00Z'});assert.equal(state.stock['RM-1']['WH-RM'],15);assert.equal(state.stock['RM-1']['WH-SF'],5);assert.deepEqual(transaction.allocations.map(row=>row.lotNo),['NEW']);assert.equal(state.inventoryLots.find(row=>row.warehouse==='WH-SF').lotNo,'NEW');assert.deepEqual(state.inventoryMovements.slice(0,2).map(row=>row.type),['WAREHOUSE_TRANSFER_IN','WAREHOUSE_TRANSFER_OUT'])});

test('posted transfer is corrected only by a reasoned reversal',()=>{const state=sample({tracked:true}),transaction=approved(state,{type:'TRANSFER',destinationWarehouse:'WH-SF',quantity:5,reason:'Production replenishment'});postInventoryTransaction(state,transaction.id,{postedBy:'warehouse-manager',at:'2026-09-11T09:00:00Z'});assert.throws(()=>reverseInventoryTransaction(state,transaction.id,{reversedBy:'manager'}),/reason/);reverseInventoryTransaction(state,transaction.id,{reversedBy:'manager',reason:'Wrong destination',at:'2026-09-11T10:00:00Z'});assert.equal(transaction.status,'REVERSED');assert.equal(state.stock['RM-1']['WH-RM'],20);assert.equal(state.stock['RM-1']['WH-SF'],0);assert.equal(state.inventoryLots.find(row=>row.id==='L1').quantity,8);assert.equal(state.inventoryMovements[0].type,'WAREHOUSE_TRANSFER_REVERSAL_IN');assert.equal(state.auditTrail[0].action,'INVENTORY_TRANSACTION_REVERSED')});

test('US GAAP LIFO issue posts newest costs to COGS and reverses the same effect',()=>{const state=sample({profile:'US_GAAP'});setInventoryCostMethod(state,'RM-1','LIFO');receiveInventoryCost(state,{sku:'RM-1',warehouse:'WH-RM',qty:10,unitCost:5,date:'2026-09-01'});receiveInventoryCost(state,{sku:'RM-1',warehouse:'WH-RM',qty:10,unitCost:8,date:'2026-09-02'});const transaction=approved(state,{purpose:'SALES',quantity:12});postInventoryTransaction(state,transaction.id,{postedBy:'warehouse-manager',at:'2026-09-11T09:00:00Z'});assert.equal(transaction.costMethod,'LIFO');assert.equal(transaction.costValue,90);assert.equal(state.journalEntries[0].lines.find(row=>row.accountCode==='5000').debit,90);assert.deepEqual(state.inventoryCostMovements[0].layers.map(row=>row.unitCost),[8,5]);reverseInventoryTransaction(state,transaction.id,{reversedBy:'manager',reason:'Wrong sales issue',at:'2026-09-11T10:00:00Z'});assert.equal(state.inventoryValuations['RM-1|WH-RM'].value,130);assert.ok(transaction.journalReversalId)});

test('failed financial posting leaves physical and financial state unchanged',()=>{const state=sample({tracked:true});state.accountingPeriods=[];const transaction=approved(state);const lots=structuredClone(state.inventoryLots),stock=structuredClone(state.stock),costMovements=state.inventoryCostMovements?.length||0;assert.throws(()=>postInventoryTransaction(state,transaction.id,{postedBy:'warehouse-manager',at:'2026-09-11T09:00:00Z'}),/accounting period/i);assert.deepEqual(state.inventoryLots,lots);assert.deepEqual(state.stock,stock);assert.equal(state.inventoryCostMovements?.length||0,costMovements);assert.equal(transaction.status,'APPROVED')});

test('warehouse page exposes the controlled transaction workflow',async()=>{const html=await readFile(new URL('../../mrp/index.html',import.meta.url),'utf8');assert.match(html,/id="inventoryTransactionType"/);assert.match(html,/id="inventoryTransactionSource"/);assert.match(html,/id="inventoryTransactionDestination"/);assert.match(html,/id="inventoryTransactionTable"/);assert.match(html,/FIFO\/FEFO traceability and controlled reversal/)});
