import test from 'node:test';
import assert from 'node:assert/strict';
import {timePhasedMaterialPlan} from '../../mrp/time-phased-mrp.js';

function base(){return{products:[{code:'FG',productionLeadTimeDays:2},{code:'SA',outputSku:'SA-SKU',productionLeadTimeDays:3}],skus:[{code:'SA-SKU',warehouse:'WH-SF'},{code:'RAW',warehouse:'WH-RM',leadTime:4}],orders:[{orderNo:'SO-1',productCode:'FG',qty:10,due:'2026-10-20'}],boms:{FG:[{sku:'SA-SKU',warehouse:'WH-SF',qty:1}],SA:[{sku:'RAW',warehouse:'WH-RM',qty:2}]},stock:{'SA-SKU':{'WH-SF':4,reserved:0},RAW:{'WH-RM':0,reserved:0}},purchaseOrders:[],plannedSupplyOrders:[],bomProfiles:{},bomHistory:{}}}

test('normal subassembly is netted before only its planned shortage explodes',()=>{const plan=timePhasedMaterialPlan(base(),{asOf:'2026-10-01',horizonDays:30}),sa=plan.rows.find(row=>row.sku==='SA-SKU'),raw=plan.rows.find(row=>row.sku==='RAW');assert.deepEqual({gross:sa.grossRequired,available:sa.availableBefore,planned:sa.plannedQuantity,need:sa.needDate,release:sa.releaseDate},{gross:10,available:4,planned:6,need:'2026-10-18',release:'2026-10-15'});assert.deepEqual({gross:raw.grossRequired,planned:raw.plannedQuantity,need:raw.needDate,release:raw.releaseDate},{gross:12,planned:12,need:'2026-10-15',release:'2026-10-11'})});

test('phantom subassembly creates no supply row and passes full demand through',()=>{const data=base();data.products[1].phantom=true;data.stock['SA-SKU']['WH-SF']=99;const plan=timePhasedMaterialPlan(data,{asOf:'2026-10-01',horizonDays:30});assert.equal(plan.rows.some(row=>row.sku==='SA-SKU'),false);const raw=plan.rows.find(row=>row.sku==='RAW');assert.equal(raw.grossRequired,20);assert.equal(raw.needDate,'2026-10-18')});

test('shared component demand is aggregated when peg, warehouse and need date match',()=>{const data=base();data.products.push({code:'SA2',outputSku:'SA2-SKU',productionLeadTimeDays:3});data.skus.push({code:'SA2-SKU',warehouse:'WH-SF'});data.boms.FG.push({sku:'SA2-SKU',warehouse:'WH-SF',qty:1});data.boms.SA2=[{sku:'RAW',warehouse:'WH-RM',qty:3}];data.stock['SA-SKU']['WH-SF']=0;data.stock['SA2-SKU']={'WH-SF':0,reserved:0};const rows=timePhasedMaterialPlan(data,{asOf:'2026-10-01',horizonDays:30}).rows.filter(row=>row.sku==='RAW');assert.equal(rows.length,1);assert.equal(rows[0].grossRequired,50);assert.equal(rows[0].llc,2)});

test('cycle in normal subassemblies blocks planning with exact path',()=>{const data=base();data.boms.SA=[{sku:'FG',warehouse:'WH-SF',qty:1}];const plan=timePhasedMaterialPlan(data,{asOf:'2026-10-01',horizonDays:30});assert.equal(plan.rows[0].status,'BLOCKED');assert.match(plan.rows[0].error,/FG → SA-SKU → FG/)});

test('planning result is deterministic when source order input is permuted',()=>{const first=base();first.orders.push({orderNo:'SO-0',productCode:'FG',qty:2,due:'2026-10-20'});const second=structuredClone(first);second.orders.reverse();const compact=state=>timePhasedMaterialPlan(state,{asOf:'2026-10-01',horizonDays:30}).rows.map(({orderNo,sku,grossRequired,plannedQuantity,needDate,releaseDate})=>({orderNo,sku,grossRequired,plannedQuantity,needDate,releaseDate}));assert.deepEqual(compact(first),compact(second))});

test('purchase receipt is consumed only by its matching warehouse',()=>{const data=base();data.products=[{code:'FG'}];data.boms={FG:[{sku:'RAW',warehouse:'WH-RM',qty:1}]};data.orders[0].qty=5;data.stock.RAW={'WH-RM':0,'WH-OTHER':0,reserved:0};data.purchaseOrders=[{poNo:'WRONG-WH',sku:'RAW',warehouse:'WH-OTHER',qty:99,dueDate:'2026-10-10',status:'APPROVED'}];const raw=timePhasedMaterialPlan(data,{asOf:'2026-10-01',horizonDays:30}).rows[0];assert.equal(raw.scheduledReceipts,0);assert.equal(raw.plannedQuantity,5)});
