import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {evaluateMasterDataQuality,createMasterDataQualityGate,reviewMasterDataQualityGate,approveMasterDataQualityGate,assertCurrentMasterDataGate} from '../../mrp/master-data-quality.js';

const complete=()=>({products:[{code:'FG-1',name:'Finished',outputSku:'FG-1',productionLeadTimeHours:2}],skus:[{code:'FG-1',name:'Finished',unit:'EA',type:'FINISHED_GOOD',leadTime:0,safetyStock:0,orderMultiple:1,standardCost:5,costMethod:'STANDARD'},{code:'RM-1',name:'Material',unit:'KG',type:'RAW_MATERIAL',leadTime:7,safetyStock:0,orderMultiple:1,standardCost:2,costMethod:'STANDARD'}],warehouses:[{code:'WH-RM',name:'Raw'}],boms:{'FG-1':[{sku:'RM-1',warehouse:'WH-RM',qty:1}]},productRoutings:[{productCode:'FG-1',operationCode:'OP-1',workCenterId:'WC-1',setupMinutes:10,runMinutesPerUnit:1,laborMinutesPerUnit:0,active:true}],workCenters:[{id:'WC-1',code:'WC-1',active:true}],operators:[],suppliers:[],purchaseOrders:[],orders:[],accountingSettings:{profile:'IFRS_TFRS'},masterDataQualityGates:[],auditTrail:[]});
test('complete planning masters pass the quality gate',()=>{const result=evaluateMasterDataQuality(complete());assert.equal(result.blockers,0);assert.equal(result.status,'READY')});
test('gate detects duplicates invalid BOM routes skills and costing',()=>{const state=complete();state.skus.push({...state.skus[1]});state.boms['FG-1'].push({sku:'UNKNOWN',warehouse:'BAD',qty:0});state.productRoutings[0].workCenterId='BAD';state.productRoutings[0].laborMinutesPerUnit=1;state.productRoutings[0].requiredSkill='WELD';state.skus[0].costMethod='LIFO';const result=evaluateMasterDataQuality(state);assert.ok(result.blockers>=6);assert.ok(result.issues.some(item=>item.code==='LIFO_NOT_PERMITTED'));assert.ok(result.issues.some(item=>item.code==='SKILL_REQUIRED'))});
test('blocked snapshot cannot be approved',()=>{const state=complete();state.products[0].outputSku='UNKNOWN';const gate=createMasterDataQualityGate(state,{steward:'data-steward',scopeNote:'Complete MRP planning master scope'});reviewMasterDataQualityGate(state,gate.id,{reviewedBy:'planner',reviewNote:'Reviewed every blocker and warning'});assert.throws(()=>approveMasterDataQualityGate(state,gate.id,{approvedBy:'manager',decisionNote:'Approve current master data snapshot'}),/Resolve all/i)});
test('approved gate becomes stale after master data changes',()=>{const state=complete(),gate=createMasterDataQualityGate(state,{steward:'data-steward',scopeNote:'Complete MRP planning master scope'});reviewMasterDataQualityGate(state,gate.id,{reviewedBy:'planner',reviewNote:'Reviewed every master-data control'});approveMasterDataQualityGate(state,gate.id,{approvedBy:'manager',decisionNote:'Approved for the governed MRP baseline'});assert.equal(assertCurrentMasterDataGate(state).id,gate.id);state.skus[0].leadTime=2;assert.throws(()=>assertCurrentMasterDataGate(state),/changed after gate approval/i)});
test('master-data interface identifiers are unique',()=>{const html=readFileSync(new URL('../../mrp/index.html',import.meta.url),'utf8');for(const id of ['masterDataGateStatus','masterDataSteward','masterDataReviewer','masterDataApprover','masterDataScope','masterDataReviewNote','masterDataDecision','createMasterDataGate','masterDataKpis','masterDataIssueTable','masterDataClaim','masterDataGateRegister'])assert.equal((html.match(new RegExp(`id="${id}"`,'g'))||[]).length,1)});
