import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {buildMpsRccp,compareMpsVersions,createMpsSnapshot,reviewMpsSnapshot,freezeMpsSnapshot} from '../../mrp/mps-governance.js';
function sample(){return{products:[{code:'FG-1',name:'Product',productionStrategy:'MTO',routingHours:1}],orders:[{productCode:'FG-1',qty:50,due:'2026-09-20',status:'OPEN'}],demandForecasts:[],stock:{},capacityCalendar:{dailyHours:8,workDays:5,efficiencyPercent:100},shiftCalendars:[{code:'A',dailyHours:8,workDays:5,efficiencyPercent:100,active:true}],workCenters:[{id:'WC1',code:'CUT',name:'Cutting',shiftCode:'A',machineCount:1,availabilityPercent:100,active:true}],operators:[{id:'OP1',shift:'A',dailyHours:8,workDays:5,efficiencyPercent:100,skills:['CUT'],active:true}],productRoutings:[{id:'R1',productCode:'FG-1',operationCode:'CUT',requiredSkill:'CUT',workCenterId:'WC1',runMinutesPerUnit:60,laborMinutesPerUnit:60,operatorsRequired:1,active:true}],sopPlans:[{planNo:'SOP-00001',status:'APPROVED'}],auditTrail:[]}}
test('RCCP exposes aggregate MPS load and capacity shortage',()=>{const result=buildMpsRccp(sample(),{asOf:'2026-09-01',horizonDays:30});assert.equal(result.totals.demand,50);assert.equal(result.totals.requiredHours,50);assert.equal(result.rccp.centers[0].status,'OVERLOADED');assert.ok(result.exceptions.some(item=>item.code==='CENTER_OVERLOAD'))});
test('MPS comparison reports demand and planned quantity changes',()=>{const result=compareMpsVersions({rows:[{productCode:'FG-1',demand:60,plannedQty:65}]},{rows:[{productCode:'FG-1',demand:50,plannedQty:50}]});assert.deepEqual(result,{rows:[{productCode:'FG-1',previousDemand:50,currentDemand:60,demandChange:10,previousPlan:50,currentPlan:65,planChange:15}],changedProducts:1,demandChange:10,planChange:15})});
test('MPS freeze requires approved S&OP, independent gates and exception decision',()=>{const state=sample();state.sopPlans=[];assert.throws(()=>createMpsSnapshot(state,{asOf:'2026-09-01',horizonDays:30,preparedBy:'planner'}),/approved executive S&OP/);state.sopPlans=[{planNo:'SOP-00001',status:'APPROVED'}];const item=createMpsSnapshot(state,{asOf:'2026-09-01',horizonDays:30,preparedBy:'planner'});assert.throws(()=>reviewMpsSnapshot(state,item.id,{reviewedBy:'planner'}),/independent/);reviewMpsSnapshot(state,item.id,{reviewedBy:'production-manager'});assert.throws(()=>freezeMpsSnapshot(state,item.id,{approvedBy:'factory-manager'}),/management decision/);item.exceptionDecision='Approved overtime for the overloaded work center';freezeMpsSnapshot(state,item.id,{approvedBy:'factory-manager'});assert.equal(item.status,'FROZEN');assert.equal(state.auditTrail.length,3)});
test('freezing a new MPS supersedes the prior frozen version',()=>{const state=sample(),first=createMpsSnapshot(state,{asOf:'2026-09-01',horizonDays:30,preparedBy:'p1',exceptionDecision:'Approved overtime for all capacity shortages'});reviewMpsSnapshot(state,first.id,{reviewedBy:'r1'});freezeMpsSnapshot(state,first.id,{approvedBy:'a1'});const second=createMpsSnapshot(state,{asOf:'2026-09-02',horizonDays:30,preparedBy:'p2',exceptionDecision:'Approved overtime for all capacity shortages'});reviewMpsSnapshot(state,second.id,{reviewedBy:'r2'});freezeMpsSnapshot(state,second.id,{approvedBy:'a2'});assert.equal(first.status,'SUPERSEDED');assert.equal(second.status,'FROZEN')});
test('MPS versioning interface identifiers are unique',()=>{const html=readFileSync(new URL('../../mrp/index.html',import.meta.url),'utf8');for(const id of ['mpsVersionAsOf','mpsVersionHorizon','mpsVersionPlanner','mpsVersionReviewer','mpsVersionApprover','mpsExceptionDecision','createMpsVersion','mpsVersionKpis','rccpPreviewTable','mpsVersionRegister','mpsVersionComparison'])assert.equal((html.match(new RegExp(`id="${id}"`,'g'))||[]).length,1)});
