import test from 'node:test';
import assert from 'node:assert/strict';
import {assembleMrpRunArtifacts,chunkMrpRunArtifacts,createMrpArtifactBackup,externalizeMrpRunPayloads,mrpRunArtifactId,rehydrateMrpRunPayloads,restoreMrpArtifactBackup,selectOrphanedMrpArtifacts,streamMrpRunArtifact} from '../../mrp/mrp-run-artifacts.js';

const state=rows=>({schemaVersion:6,settings:{name:'Factory'},mrpRuns:[{id:'R1',runNo:'MRP-1',status:'RELEASED',resultFingerprint:'abc',rows,timeBucketCheckpoints:{schemaVersion:3,headHash:'head',checkpoints:[{index:0,records:rows.map(row=>[row.key,row.plannedQuantity])}]}}]});
test('large MRP run payload is externalized without mutating caller state',()=>{const original=state(Array.from({length:1000},(_,index)=>({key:`K${index}`,plannedQuantity:index}))),before=JSON.stringify(original),result=externalizeMrpRunPayloads(original,{thresholdBytes:100});assert.equal(JSON.stringify(original),before);assert.equal(result.externalizedRuns,1);assert.equal(result.coreState.mrpRuns[0].rows.length,0);assert.equal(result.coreState.mrpRuns[0].storageArtifact.artifactId,'R1:abc');assert.ok(result.coreBytes<result.artifacts[0].byteLength);});
test('artifact rehydration is lossless',()=>{const original=state([{key:'A',plannedQuantity:2},{key:'B',plannedQuantity:3}]),result=externalizeMrpRunPayloads(original,{thresholdBytes:1}),restored=rehydrateMrpRunPayloads(result.coreState,result.artifacts);assert.deepEqual(restored,original);});
test('small run stays inline for backward compatibility',()=>{const original=state([]),result=externalizeMrpRunPayloads(original,{thresholdBytes:1_000_000});assert.equal(result.externalizedRuns,0);assert.deepEqual(result.coreState,original);});
test('missing or length-mismatched artifact fails closed',()=>{const result=externalizeMrpRunPayloads(state([{key:'A'}]),{thresholdBytes:1});assert.throws(()=>rehydrateMrpRunPayloads(result.coreState,[]),/missing/);assert.throws(()=>rehydrateMrpRunPayloads(result.coreState,[{...result.artifacts[0],payloadJson:'{}'}]),/length mismatch/);});
test('artifact identity requires controlled run identity',()=>{assert.throws(()=>mrpRunArtifactId({id:'R1'}),/fingerprint/);});
test('artifact chunks round-trip Unicode across byte boundaries',()=>{const original=state(Array.from({length:200},(_,index)=>({key:`قطعه-${index}-İ`,description:'آلومینیوم و فولاد',plannedQuantity:index}))),external=externalizeMrpRunPayloads(original,{thresholdBytes:1}),chunked=chunkMrpRunArtifacts(external.artifacts,{chunkBytes:1024}),assembled=assembleMrpRunArtifacts(chunked.manifests,[...chunked.chunks].reverse()),restored=rehydrateMrpRunPayloads(external.coreState,assembled);assert.ok(chunked.chunks.length>1);assert.ok(chunked.chunks.every(item=>item.byteLength<=1024));assert.deepEqual(restored,original);});
test('missing chunk and corrupted byte length fail closed',()=>{const external=externalizeMrpRunPayloads(state(Array.from({length:100},(_,index)=>({key:`K${index}`}))),{thresholdBytes:1}),chunked=chunkMrpRunArtifacts(external.artifacts,{chunkBytes:1024});assert.throws(()=>assembleMrpRunArtifacts(chunked.manifests,chunked.chunks.slice(1)),/incomplete/);assert.throws(()=>assembleMrpRunArtifacts(chunked.manifests,chunked.chunks.map((item,index)=>index?item:{...item,byteLength:item.byteLength+1})),/integrity failed/);});
test('every chunk has an independent SHA-256 hash and a verified chain',()=>{const external=externalizeMrpRunPayloads(state(Array.from({length:100},(_,index)=>({key:`K${index}`,plannedQuantity:index}))),{thresholdBytes:1}),chunked=chunkMrpRunArtifacts(external.artifacts,{chunkBytes:1024}),manifest=chunked.manifests[0];assert.equal(manifest.hashAlgorithm,'SHA-256');assert.match(manifest.headHash,/^[0-9a-f]{64}$/);for(const [index,chunk] of chunked.chunks.entries()){assert.match(chunk.payloadHash,/^[0-9a-f]{64}$/);assert.match(chunk.hash,/^[0-9a-f]{64}$/);assert.equal(chunk.previousHash,index?chunked.chunks[index-1].hash:'GENESIS')}});
test('same-length payload tampering and chain substitution fail closed',()=>{const external=externalizeMrpRunPayloads(state(Array.from({length:100},(_,index)=>({key:`K${index}`,plannedQuantity:index}))),{thresholdBytes:1}),chunked=chunkMrpRunArtifacts(external.artifacts,{chunkBytes:1024}),tampered=chunked.chunks.map(item=>({...item}));tampered[0].payloadBase64=(tampered[0].payloadBase64[0]==='A'?'B':'A')+tampered[0].payloadBase64.slice(1);assert.throws(()=>assembleMrpRunArtifacts(chunked.manifests,tampered),/integrity failed/);const replaced=chunked.chunks.map(item=>({...item}));replaced[1].previousHash='0'.repeat(64);assert.throws(()=>assembleMrpRunArtifacts(chunked.manifests,replaced),/integrity failed/);});
test('lazy retrieval loads and verifies exactly one chunk at a time',async()=>{const original=state(Array.from({length:300},(_,index)=>({key:`قطعه-${index}`,plannedQuantity:index}))),external=externalizeMrpRunPayloads(original,{thresholdBytes:1}),chunked=chunkMrpRunArtifacts(external.artifacts,{chunkBytes:1024}),loaded=[],decoder=new TextDecoder(),pieces=[];for await(const bytes of streamMrpRunArtifact(chunked.manifests[0],async(artifactId,index)=>{loaded.push([artifactId,index]);return chunked.chunks[index]})){assert.equal(loaded.length,pieces.length+1);pieces.push(decoder.decode(bytes,{stream:true}))}pieces.push(decoder.decode());assert.equal(pieces.join(''),external.artifacts[0].payloadJson);assert.deepEqual(loaded.map(([,index])=>index),chunked.chunks.map(item=>item.index));});
test('lazy retrieval stops at the first invalid chunk without fetching later chunks',async()=>{const external=externalizeMrpRunPayloads(state(Array.from({length:300},(_,index)=>({key:`K${index}`,plannedQuantity:index}))),{thresholdBytes:1}),chunked=chunkMrpRunArtifacts(external.artifacts,{chunkBytes:1024}),loaded=[];await assert.rejects(async()=>{for await(const _ of streamMrpRunArtifact(chunked.manifests[0],async(_artifactId,index)=>{loaded.push(index);const item={...chunked.chunks[index]};if(index===1)item.payloadHash='0'.repeat(64);return item})){}},/integrity failed/);assert.deepEqual(loaded,[0,1]);});
test('artifact backup restores a complete run and rejects an incomplete snapshot',()=>{const original=state(Array.from({length:300},(_,index)=>({key:`K${index}`,plannedQuantity:index}))),external=externalizeMrpRunPayloads(original,{thresholdBytes:1}),chunked=chunkMrpRunArtifacts(external.artifacts,{chunkBytes:1024}),backup=createMrpArtifactBackup(external.coreState,chunked.manifests,chunked.chunks,{backupId:'B-1',createdAt:'2026-09-12T00:00:00Z'});assert.deepEqual(restoreMrpArtifactBackup(backup),original);assert.throws(()=>createMrpArtifactBackup(external.coreState,chunked.manifests,chunked.chunks.slice(1),{backupId:'B-2'}),/incomplete/);});
test('orphan cleanup preserves referenced and grace-period artifacts',()=>{const core=state([]),referenced={artifactId:'R1:abc',createdAt:'2026-08-01T00:00:00Z'},oldOrphan={artifactId:'R2:def',createdAt:'2026-08-01T00:00:00Z'},recentOrphan={artifactId:'R3:ghi',createdAt:'2026-09-11T00:00:00Z'};core.mrpRuns[0].storageArtifact={artifactId:referenced.artifactId};assert.deepEqual(selectOrphanedMrpArtifacts([core],[referenced,oldOrphan,recentOrphan],{createdBefore:'2026-09-01T00:00:00Z'}),[oldOrphan.artifactId]);assert.throws(()=>selectOrphanedMrpArtifacts([],[],{createdBefore:'invalid'}),/cutoff/);});
