import test from 'node:test';
import assert from 'node:assert/strict';
import {createProject,ensureDmaicStages,kpiActual,kpiHealth,linkErpRecord,normalizeProjectState,projectFinanceSummary,projectMetrics} from '../../mrp/projects.js';

test('project templates create method-specific controlled work',()=>{const state={};normalizeProjectState(state);const project=createProject(state,{method:'SIX_SIGMA',name:'Reduce scrap'});assert.equal(project.method,'SIX_SIGMA');assert.deepEqual(state.projectTasks.map(task=>task.phase),['Define','Measure','Analyze','Improve','Control']);assert.ok(state.projectTasks.every(task=>task.projectId===project.id))});

test('project metrics combine completion, blockers and overdue work',()=>{const state={projects:[{id:'P1'}],projectTasks:[{id:'1',projectId:'P1',status:'DONE',progress:100},{id:'2',projectId:'P1',status:'BLOCKED',progress:20,dueDate:'2026-01-01'}],kpiDefinitions:[]};normalizeProjectState(state);const metrics=projectMetrics(state,'P1',new Date('2026-09-10T00:00:00Z'));assert.deepEqual({tasks:metrics.tasks,done:metrics.done,blocked:metrics.blocked,overdue:metrics.overdue,progress:metrics.progress},{tasks:2,done:1,blocked:1,overdue:1,progress:60})});

test('live KPI reads production and inventory data from ERP state',()=>{const state={projects:[],projectTasks:[],kpiDefinitions:[],productionJobs:[{completedQty:90,scrapQty:10}],qualityInspections:[],skus:[{code:'RM-1',min:20}],stock:{'RM-1':{'WH-RM':10,reserved:0}}};assert.equal(kpiActual(state,{source:'PRODUCTION_YIELD'}),90);assert.equal(kpiActual(state,{source:'CRITICAL_STOCK'}),1);assert.deepEqual(kpiHealth(state,{source:'PRODUCTION_YIELD',target:95,direction:'ABOVE',warningTolerance:10}),{actual:90,status:'AT_RISK'})});

test('DMAIC workspace always contains the five controlled stages',()=>{const state={};const stages=ensureDmaicStages(state,'P1');assert.deepEqual(stages.map(item=>item.stage),['DEFINE','MEASURE','ANALYZE','IMPROVE','CONTROL']);assert.ok(stages.every(item=>item.gateStatus==='PENDING'))});

test('ERP link is stored on both the task and operational record',()=>{const state={projects:[{id:'P1'}],projectTasks:[{id:'T1',projectId:'P1'}],productionJobs:[{id:'J1',workOrderNo:'WO-1'}]};normalizeProjectState(state);const record=linkErpRecord(state,{type:'PRODUCTION_ORDER',reference:'WO-1',projectId:'P1',taskId:'T1'});assert.deepEqual({projectId:record.projectId,taskId:record.projectTaskId}, {projectId:'P1',taskId:'T1'});assert.deepEqual({type:state.projectTasks[0].linkedEntityType,reference:state.projectTasks[0].linkedEntityId,status:state.projectTasks[0].linkStatus},{type:'PRODUCTION_ORDER',reference:'WO-1',status:'LINKED'})});

test('project finance combines manual ledger with linked ERP commitments and revenue',()=>{const state={projects:[{id:'P1',budget:10000}],projectTasks:[],kpiDefinitions:[],projectFinance:[{projectId:'P1',type:'ACTUAL',amount:500,status:'POSTED'},{projectId:'P1',type:'INCOME',amount:200,status:'POSTED'}],purchaseOrders:[{projectId:'P1',qty:10,unitPrice:100,status:'APPROVED'}],financeApprovals:[{projectId:'P1',type:'PURCHASE_PAYMENT',amount:300,status:'APPROVED'}],salesOrders:[{projectId:'P1',qty:5,unitPrice:400,status:'SHIPPED'}]};normalizeProjectState(state);assert.deepEqual(projectFinanceSummary(state,'P1'),{budget:10000,planned:0,committed:1000,actual:800,revenue:2200,remaining:9200,forecast:1800,margin:1400,productionLoss:0})});

test('linked production loss flows into project actual cost',()=>{const state={projects:[{id:'P1',budget:1000}],projectTasks:[],kpiDefinitions:[],projectFinance:[],productionJobs:[{projectId:'P1',operationalLoss:125}]};normalizeProjectState(state);const summary=projectFinanceSummary(state,'P1');assert.equal(summary.productionLoss,125);assert.equal(summary.actual,125);assert.equal(summary.remaining,875)});
