import test from 'node:test';
import assert from 'node:assert/strict';
import {completeOperation,expectedStageInput,nextRequiredStage,normalizeShopFloorState,pauseOperation,raiseAndon,resumeOperation,shopFloorMetrics,startOperation,updateAndon} from '../../mrp/shop-floor-live.js';

function sampleState(){const state={productionJobs:[{id:'J1',workOrderNo:'WO-1',batchNo:'B-1',status:'IN_PRODUCTION',plannedQty:100,operationRoute:['SETUP','PRODUCTION']}],operators:[{id:'OP1',code:'OP-001',name:'Sara',active:true}],workCenters:[{id:'WC1',code:'WC-001',name:'Line 1',status:'AVAILABLE',active:true}],auditTrail:[]};normalizeShopFloorState(state);return state}

test('operator can only start the next required stage and work center becomes live',()=>{const state=sampleState();assert.equal(nextRequiredStage(state,'J1'),'SETUP');assert.throws(()=>startOperation(state,{jobId:'J1',operatorId:'OP1',workCenterId:'WC1',stage:'PRODUCTION'}),/Complete SETUP/);const session=startOperation(state,{id:'S1',jobId:'J1',operatorId:'OP1',workCenterId:'WC1',startedAt:'2026-09-10T08:00:00Z'});assert.equal(session.inputQty,100);assert.equal(state.workCenters[0].status,'RUNNING');assert.equal(state.productionJobs[0].shopFloorStatus,'RUNNING')});

test('pause and resume capture downtime and continuous improvement signal',()=>{const state=sampleState();startOperation(state,{id:'S1',jobId:'J1',operatorId:'OP1',workCenterId:'WC1',startedAt:'2026-09-10T08:00:00Z'});pauseOperation(state,'S1',{reason:'MACHINE',at:'2026-09-10T08:10:00Z'});assert.equal(state.workCenters[0].status,'STOPPED');resumeOperation(state,'S1',{at:'2026-09-10T08:30:00Z'});completeOperation(state,'S1',{goodQty:98,scrapQty:2,completedAt:'2026-09-10T09:00:00Z'});assert.equal(state.operationSessions[0].downtimeMinutes,20);assert.equal(state.workCenters[0].status,'AVAILABLE');assert.equal(state.continuousImprovementItems.length,1);assert.equal(state.continuousImprovementItems[0].source,'SCRAP')});

test('good output feeds the next stage and final output updates production draft',()=>{const state=sampleState();startOperation(state,{id:'S1',jobId:'J1',operatorId:'OP1',workCenterId:'WC1',startedAt:'2026-09-10T08:00:00Z'});completeOperation(state,'S1',{goodQty:95,scrapQty:5,completedAt:'2026-09-10T08:20:00Z'});assert.equal(expectedStageInput(state,'J1'),95);const final=startOperation(state,{id:'S2',jobId:'J1',operatorId:'OP1',workCenterId:'WC1',startedAt:'2026-09-10T08:30:00Z'});assert.equal(final.inputQty,95);completeOperation(state,'S2',{goodQty:94,scrapQty:1,reworkQty:0,completedAt:'2026-09-10T09:00:00Z'});assert.equal(nextRequiredStage(state,'J1'),'');assert.deepEqual({ready:state.productionJobs[0].shopFloorReady,status:state.productionJobs[0].shopFloorStatus,good:state.productionJobs[0].completedQty,scrap:state.productionJobs[0].scrapQty},{ready:true,status:'READY_FOR_FQC',good:94,scrap:6})});

test('Andon creates an improvement action and follows acknowledge/resolve control',()=>{const state=sampleState(),alert=raiseAndon(state,{id:'A1',jobId:'J1',operatorId:'OP1',category:'SAFETY',severity:'CRITICAL',message:'Guard opened',createdAt:'2026-09-10T08:00:00Z'});assert.equal(state.continuousImprovementItems[0].andonId,'A1');updateAndon(state,alert.id,'ACKNOWLEDGED');assert.equal(alert.status,'ACKNOWLEDGED');updateAndon(state,alert.id,'RESOLVED');assert.equal(state.productionJobs[0].andonStatus,'RESOLVED')});

test('live metrics aggregate operator activity, quality loss and downtime',()=>{const state=sampleState();startOperation(state,{id:'S1',jobId:'J1',operatorId:'OP1',workCenterId:'WC1',startedAt:'2026-09-10T08:00:00Z'});pauseOperation(state,'S1',{reason:'MACHINE',at:'2026-09-10T08:10:00Z'});resumeOperation(state,'S1',{at:'2026-09-10T08:25:00Z'});completeOperation(state,'S1',{goodQty:97,scrapQty:2,reworkQty:1,completedAt:'2026-09-10T09:00:00Z'});raiseAndon(state,{jobId:'J1',category:'MATERIAL'});const metrics=shopFloorMetrics(state,new Date('2026-09-10T12:00:00Z'));assert.deepEqual({good:metrics.goodQty,scrap:metrics.scrapQty,rework:metrics.reworkQty,downtime:metrics.downtimeMinutes,andon:metrics.openAndon},{good:97,scrap:2,rework:1,downtime:15,andon:1})});
