import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {compareMrpRuns,buildMrpRun,createMrpRun,mergeSortedPlanRows,reviewMrpRun,releaseMrpRun} from '../../mrp/mrp-run-governance.js';
import {appendMrpDelta} from '../../mrp/mrp-delta-ledger.js';
import {masterDataFingerprint} from '../../mrp/master-data-quality.js';

const state=()=>{const value={products:[],skus:[],orders:[],plannedSupplyOrders:[],purchaseOrders:[],mpsSnapshots:[{id:'MPS-1',status:'FROZEN'}],mrpRuns:[],auditTrail:[]};value.masterDataQualityGates=[{id:'MDQ-1',gateNo:'MDQ-00001',status:'APPROVED',fingerprint:masterDataFingerprint(value)}];return value};

test('MRP comparison reports new changed and removed requirements',()=>{const previous={rows:[{key:'A',orderNo:'O1',sku:'RM1',plannedQuantity:10,releaseDate:'2026-09-10',status:'PLANNED'},{key:'B',orderNo:'O2',sku:'RM2',plannedQuantity:5,releaseDate:'2026-09-11',status:'PLANNED'}]},current={rows:[{key:'A',orderNo:'O1',sku:'RM1',plannedQuantity:12,releaseDate:'2026-09-09',status:'PLANNED'},{key:'C',orderNo:'O3',sku:'RM3',plannedQuantity:7,releaseDate:'2026-09-12',status:'PLANNED'}]};const changes=compareMrpRuns(previous,current);assert.deepEqual(changes.map(row=>row.type).sort(),['CHANGED','NEW','REMOVED']);assert.equal(changes.find(row=>row.key==='A').quantityChange,2)});

test('incremental merge preserves deterministic planning order without a full sort',()=>{const left=[{orderNo:'O1',sku:'A',needDate:'2026-09-10',llc:1},{orderNo:'O3',sku:'C',needDate:'2026-09-12',llc:1}],right=[{orderNo:'O2',sku:'B',needDate:'2026-09-11',llc:1},{orderNo:'O4',sku:'D',needDate:'2026-09-13',llc:1}];assert.deepEqual(mergeSortedPlanRows(left,right).map(row=>row.orderNo),['O1','O2','O3','O4'])});

test('net-change run requires a released baseline',()=>{assert.throws(()=>buildMrpRun(state(),{asOf:'2026-09-11',mode:'NET_CHANGE'}),/released MRP baseline/i)});

test('governed MRP run requires a frozen MPS and planner',()=>{const value=state();value.mpsSnapshots=[];assert.throws(()=>createMrpRun(value,{plannedBy:'planner'}),/Freeze an MPS/i);value.mpsSnapshots=[{id:'MPS-1',status:'FROZEN'}];assert.throws(()=>createMrpRun(value,{}),/planner identity/i)});

test('governed MRP run requires a current approved master-data gate',()=>{const value=state();value.masterDataQualityGates=[];assert.throws(()=>createMrpRun(value,{plannedBy:'planner'}),/Master Data Quality Gate/i)});

test('review and release enforce three independent identities',()=>{const value=state(),run=createMrpRun(value,{asOf:'2026-09-11',mode:'FULL',plannedBy:'planner'},{at:'2026-09-11T08:00:00Z'});assert.throws(()=>reviewMrpRun(value,run.id,{reviewedBy:'planner',decision:'Reviewed all exceptions'}),/independent/i);reviewMrpRun(value,run.id,{reviewedBy:'reviewer',decision:'Reviewed all planning exceptions'});assert.throws(()=>releaseMrpRun(value,run.id,{releasedBy:'reviewer'}),/independent/i);releaseMrpRun(value,run.id,{releasedBy:'manager'});assert.equal(run.status,'RELEASED');for(const payload of [run.rows,run.inputSnapshot,run.deltaAnchor,run.timeBucketCheckpoints,run.changes,run.exceptions,run.totals,run.netChange,run.checkpointVerification])assert.ok(Object.isFrozen(payload))});

test('release blocks a reviewed run when planning inputs changed after calculation',()=>{const value=state(),run=createMrpRun(value,{asOf:'2026-09-11',mode:'FULL',plannedBy:'planner'});reviewMrpRun(value,run.id,{reviewedBy:'reviewer',decision:'Reviewed all planning exceptions'});appendMrpDelta(value,{entityType:'ITEM',entityKey:'RM-CHANGED',operation:'UPDATE'});assert.throws(()=>releaseMrpRun(value,run.id,{releasedBy:'manager'}),/inputs changed.*recalculate/i);assert.equal(run.status,'REVIEWED')});

test('release blocks when the planning change ledger loses integrity',()=>{const value=state();value.mrpDeltaLedger={schemaVersion:2,hashAlgorithm:'SHA-256',lastSequence:0,headHash:'GENESIS',entries:[],enforced:true};appendMrpDelta(value,{entityType:'ITEM',entityKey:'RM-1',operation:'UPDATE'});const run=createMrpRun(value,{asOf:'2026-09-11',mode:'FULL',plannedBy:'planner'});reviewMrpRun(value,run.id,{reviewedBy:'reviewer',decision:'Reviewed all planning exceptions'});value.mrpDeltaLedger.entries[0].entityKey='TAMPERED';assert.throws(()=>releaseMrpRun(value,run.id,{releasedBy:'manager'}),/lost integrity.*recalculate/i);assert.equal(run.status,'REVIEWED')});

test('release blocks when controlled MRP rows no longer match their checkpoint stream',()=>{const value=state(),run=createMrpRun(value,{asOf:'2026-09-11',mode:'FULL',plannedBy:'planner'});reviewMrpRun(value,run.id,{reviewedBy:'reviewer',decision:'Reviewed all planning exceptions'});run.rows.push({key:'TAMPERED',needDate:'2026-09-12',plannedQuantity:99});assert.throws(()=>releaseMrpRun(value,run.id,{releasedBy:'manager'}),/checkpoint stream.*recalculate/i);assert.equal(run.status,'REVIEWED')});

test('a new released MRP run supersedes the prior baseline',()=>{const value=state(),first=createMrpRun(value,{asOf:'2026-09-11',mode:'FULL',plannedBy:'p1'});reviewMrpRun(value,first.id,{reviewedBy:'r1',decision:'First baseline reviewed'});releaseMrpRun(value,first.id,{releasedBy:'a1'});const second=createMrpRun(value,{asOf:'2026-09-12',mode:'NET_CHANGE',plannedBy:'p2'});reviewMrpRun(value,second.id,{reviewedBy:'r2',decision:'Net change run reviewed'});releaseMrpRun(value,second.id,{releasedBy:'a2'});assert.equal(first.status,'SUPERSEDED');assert.equal(second.status,'RELEASED');assert.equal(second.baselineRunId,first.id)});

test('unchanged net-change run reuses its released baseline with proven parity',()=>{const value=state(),first=createMrpRun(value,{asOf:'2026-09-11',horizonDays:90,mode:'FULL',plannedBy:'p1'});reviewMrpRun(value,first.id,{reviewedBy:'r1',decision:'Baseline is controlled'});releaseMrpRun(value,first.id,{releasedBy:'a1'});const next=buildMrpRun(value,{asOf:'2026-09-11',horizonDays:90,mode:'NET_CHANGE'});assert.equal(next.netChange.executionStrategy,'REUSED_UNCHANGED_BASELINE');assert.equal(next.netChange.parityStatus,'PROVEN');assert.equal(next.netChange.dirty.changed,false);assert.deepEqual(next.rows,first.rows)});

test('legacy checkpoint schema is rebuilt instead of reused',()=>{const value=state(),first=createMrpRun(value,{asOf:'2026-09-11',horizonDays:90,mode:'FULL',plannedBy:'p1'});reviewMrpRun(value,first.id,{reviewedBy:'r1',decision:'Baseline is controlled'});releaseMrpRun(value,first.id,{releasedBy:'a1'});first.timeBucketCheckpoints={...first.timeBucketCheckpoints,schemaVersion:2};const next=buildMrpRun(value,{asOf:'2026-09-11',horizonDays:90,mode:'NET_CHANGE'});assert.equal(next.timeBucketCheckpoints.schemaVersion,3);assert.equal(next.timeBucketCheckpoints.mode,'FULL_BUILD')});

test('legacy ledger migration completes only when a new full baseline is released',()=>{const value=state();value.mrpDeltaLedger={schemaVersion:1,lastSequence:1,headHash:'12345678',entries:[{sequence:1,hash:'12345678'}],enforced:true};const run=createMrpRun(value,{asOf:'2026-09-11',mode:'FULL',plannedBy:'planner'});assert.equal(value.mrpDeltaLedger.requiresFullBaseline,true);reviewMrpRun(value,run.id,{reviewedBy:'reviewer',decision:'Migration baseline reviewed'});releaseMrpRun(value,run.id,{releasedBy:'manager'});assert.equal(value.mrpDeltaLedger.requiresFullBaseline,false);assert.equal(value.mrpDeltaLedger.enforced,true);assert.deepEqual(run.deltaAnchor,{sequence:0,headHash:'GENESIS'})});

test('dirty demand is classified and enters component-scoped incremental planning',()=>{const value=state(),first=createMrpRun(value,{asOf:'2026-09-11',mode:'FULL',plannedBy:'p1'});reviewMrpRun(value,first.id,{reviewedBy:'r1',decision:'Baseline is controlled'});releaseMrpRun(value,first.id,{releasedBy:'a1'});value.orders.push({orderNo:'SO-NEW',productCode:'MISSING',qty:1,due:'2026-09-20'});const next=buildMrpRun(value,{asOf:'2026-09-11',mode:'NET_CHANGE'});assert.equal(next.netChange.executionStrategy,'INCREMENTAL_COMPONENT');assert.deepEqual(next.netChange.dirty.dirtyOrders,['SO-NEW']);assert.ok(next.netChange.dirty.reasons.includes('DEMAND'))});

test('component-scoped incremental result has exact full-run parity',()=>{const value={products:[{code:'P1'},{code:'P2'}],skus:[{code:'R1'},{code:'R2'}],orders:[{orderNo:'O1',productCode:'P1',qty:10,due:'2026-09-20'},{orderNo:'O2',productCode:'P2',qty:7,due:'2026-09-20'}],boms:{P1:[{sku:'R1',warehouse:'WH-RM',qty:2}],P2:[{sku:'R2',warehouse:'WH-RM',qty:3}]},stock:{R1:{'WH-RM':5,reserved:0},R2:{'WH-RM':1,reserved:0}},purchaseOrders:[],plannedSupplyOrders:[],mrpRuns:[]},baseline=buildMrpRun(value,{asOf:'2026-09-11',horizonDays:30,mode:'FULL'});baseline.id='BASE';baseline.status='RELEASED';value.mrpRuns=[baseline];value.stock.R1['WH-RM']=9;const incremental=buildMrpRun(value,{asOf:'2026-09-11',horizonDays:30,mode:'NET_CHANGE'}),full=buildMrpRun({...value,mrpRuns:[]},{asOf:'2026-09-11',horizonDays:30,mode:'FULL'});assert.equal(incremental.netChange.executionStrategy,'INCREMENTAL_COMPONENT');assert.deepEqual(incremental.netChange.scope.impactedOrders,['O1']);assert.equal(incremental.resultFingerprint,full.resultFingerprint);assert.deepEqual(incremental.rows,full.rows)});

test('trusted delta ledger selects the fast path with exact full-run parity',()=>{const value={products:[{code:'P1'},{code:'P2'}],skus:[{code:'R1'},{code:'R2'}],orders:[{orderNo:'O1',productCode:'P1',qty:10,due:'2026-09-20'},{orderNo:'O2',productCode:'P2',qty:7,due:'2026-09-20'}],boms:{P1:[{sku:'R1',warehouse:'WH-RM',qty:2}],P2:[{sku:'R2',warehouse:'WH-RM',qty:3}]},stock:{R1:{'WH-RM':5,reserved:0},R2:{'WH-RM':1,reserved:0}},purchaseOrders:[],plannedSupplyOrders:[],mrpRuns:[],mrpDeltaLedger:{schemaVersion:2,hashAlgorithm:'SHA-256',lastSequence:0,headHash:'GENESIS',entries:[],enforced:true}},baseline=buildMrpRun(value,{asOf:'2026-09-11',horizonDays:30,mode:'FULL'});baseline.id='BASE';baseline.status='RELEASED';value.mrpRuns=[baseline];value.stock.R1['WH-RM']=9;appendMrpDelta(value,{entityType:'ITEM',entityKey:'R1',operation:'UPDATE'});const incremental=buildMrpRun(value,{asOf:'2026-09-11',horizonDays:30,mode:'NET_CHANGE'}),full=buildMrpRun({...value,mrpRuns:[]},{asOf:'2026-09-11',horizonDays:30,mode:'FULL'});assert.equal(incremental.netChange.changeDetection,'DELTA_LEDGER');assert.equal(incremental.netChange.executionStrategy,'INCREMENTAL_COMPONENT');assert.deepEqual(incremental.netChange.scope.impactedOrders,['O1']);assert.equal(incremental.resultFingerprint,full.resultFingerprint);assert.deepEqual(incremental.rows,full.rows)});

test('MRP run interface identifiers are unique',()=>{const html=readFileSync(new URL('../../mrp/index.html',import.meta.url),'utf8');for(const id of ['governedMrpPreviewStatus','governedMrpAsOf','governedMrpHorizon','governedMrpMode','governedMrpPlanner','governedMrpReviewer','governedMrpApprover','governedMrpDecision','createGovernedMrpRun','governedMrpKpis','governedMrpRunTable','governedMrpChangeTable'])assert.equal((html.match(new RegExp(`id="${id}"`,'g'))||[]).length,1)});
