import test from 'node:test';
import assert from 'node:assert/strict';
import {ensureBomProfile,saveBomRevision} from '../../mrp/bom-workflow.js';
import {createProductionJob,releaseProductionJob,issueProductionJob,completeProductionJob,cancelProductionJob,applyProductionQualityDecision} from '../../mrp/production-workflow.js';
import {createAccountingPeriod,normalizeFinancialState} from '../../mrp/financial-core.js';
import {receiveInventoryCost,setInventoryCostMethod} from '../../mrp/inventory-costing.js';

function sampleState(){
  const state={products:[{code:'P-1',name:'Product 1',unit:'ADET'}],skus:[{code:'RM-1',name:'Material',unit:'KG',cost:4,warehouse:'WH-RM'}],warehouses:[{code:'WH-RM'},{code:'WH-FG'},{code:'WH-QA'},{code:'WH-SF'}],orders:[{id:'o1',orderNo:'ORD-1',productCode:'P-1',qty:4,priority:'URGENT'}],boms:{'P-1':[{sku:'RM-1',warehouse:'WH-RM',qty:2.5,wastePercent:0}]},stock:{'RM-1':{'WH-RM':12,'WH-SF':0,reserved:0}},productionJobs:[],qualityInspections:[],auditTrail:[],inventoryMovements:[]};
  normalizeFinancialState(state);createAccountingPeriod(state,{id:'P1',code:'2026',startDate:'2026-01-01',endDate:'2026-12-31'});const profile=ensureBomProfile(state,'P-1');profile.effectiveDate='2026-01-01';saveBomRevision(state,'P-1',{at:'2026-01-01T00:00:00Z'});return state;
}

test('production completion waits in quarantine until accepted FQC',()=>{const state=sampleState(),order=state.orders[0];const job=createProductionJob(state,{id:'j1',workOrderNo:'WO-0001',order,createdAt:'2026-09-07'});assert.equal(job.materials[0].required,10);assert.equal(job.standardUnitCost,10);assert.equal(order.productionStatus,'PLANNED');releaseProductionJob(state,'j1','2026-09-07T09:00:00Z');assert.equal(state.stock['RM-1'].reserved,10);issueProductionJob(state,'j1','2026-09-07T10:00:00Z');assert.equal(state.stock['RM-1']['WH-RM'],2);assert.equal(state.stock['RM-1']['WH-SF'],10);assert.equal(state.stock['RM-1'].reserved,0);assert.equal(job.materialIssueCost,40);assert.ok(job.materialIssueJournalId);completeProductionJob(state,'j1',{completedQty:3,scrapQty:1,completedAt:'2026-09-07T12:00:00Z',inspectionId:'fqc1',inspectionNo:'FQC-0001',meta:{user:'operator',device:'LINE-1'}});assert.equal(state.stock['RM-1']['WH-SF'],0);assert.equal(state.inventoryValuations['RM-1|WH-SF'].quantity,0);assert.equal(job.actualMaterialCost,40);assert.equal(state.stock['FG-P-1']['WH-QA'],3);assert.equal(state.stock['FG-P-1']['WH-FG']||0,0);assert.equal(state.skus.at(-1).cost,10);assert.equal(state.skus.at(-1).costBomVersion,'1.0');assert.equal(order.productionStatus,'AWAITING_FQC');state.qualityInspections[0].result='ACCEPTED';applyProductionQualityDecision(state,'fqc1',{decidedAt:'2026-09-07T13:00:00Z',meta:{user:'quality',device:'QC-01'}});assert.equal(state.stock['FG-P-1']['WH-QA'],0);assert.equal(state.stock['FG-P-1']['WH-FG'],3);assert.equal(state.inventoryValuations['FG-P-1|WH-FG'].value,30);assert.ok(job.finishedGoodsJournalId);assert.equal(order.productionStatus,'COMPLETED');assert.equal(state.productionJobs[0].batchNo.startsWith('BATCH-'),true);assert.equal(state.auditTrail[0].user,'quality')});

test('production cost posting failure does not move physical material',()=>{const state=sampleState();state.accountingPeriods=[];const job=createProductionJob(state,{id:'j1',workOrderNo:'WO-0001',order:state.orders[0],createdAt:'2026-09-07'});releaseProductionJob(state,'j1','2026-09-07T09:00:00Z');const stock=structuredClone(state.stock);assert.throws(()=>issueProductionJob(state,'j1','2026-09-07T10:00:00Z'),/accounting period/i);assert.deepEqual(state.stock,stock);assert.equal(job.status,'RELEASED');assert.equal(state.inventoryCostMovements?.length||0,0)});

test('US GAAP production issue carries LIFO material cost through WIP',()=>{const state=sampleState();state.accountingSettings.profile='US_GAAP';setInventoryCostMethod(state,'RM-1','LIFO');receiveInventoryCost(state,{sku:'RM-1',warehouse:'WH-RM',qty:6,unitCost:3,date:'2026-09-01'});receiveInventoryCost(state,{sku:'RM-1',warehouse:'WH-RM',qty:6,unitCost:5,date:'2026-09-02'});const job=createProductionJob(state,{id:'j1',workOrderNo:'WO-LIFO',order:state.orders[0],createdAt:'2026-09-07'});releaseProductionJob(state,'j1','2026-09-07T09:00:00Z');issueProductionJob(state,'j1','2026-09-07T10:00:00Z');assert.equal(job.materialIssueCost,42);assert.equal(job.materials[0].costMethod,'LIFO');assert.equal(state.inventoryValuations['RM-1|WH-SF'].value,42);completeProductionJob(state,'j1',{completedQty:4,scrapQty:0,completedAt:'2026-09-07T12:00:00Z',inspectionId:'fqc1'});assert.equal(job.actualMaterialCost,42);assert.equal(state.inventoryValuations['RM-1|WH-SF'].quantity,0)});

test('completed shop-floor sessions accrue actual labor and overhead into WIP',()=>{const state=sampleState(),job=createProductionJob(state,{id:'j1',workOrderNo:'WO-CONV',order:state.orders[0],createdAt:'2026-09-07'});state.operators=[{id:'OP1',hourlyRate:20}];state.workCenters=[{id:'WC1',hourlyRate:10,overheadRate:5}];state.operationSessions=[{jobId:'j1',status:'COMPLETED',operatorId:'OP1',workCenterId:'WC1',actualMinutes:60}];releaseProductionJob(state,'j1','2026-09-07T09:00:00Z');issueProductionJob(state,'j1','2026-09-07T10:00:00Z');completeProductionJob(state,'j1',{completedQty:4,scrapQty:0,completedAt:'2026-09-07T12:00:00Z',inspectionId:'fqc1'});assert.equal(job.actualLaborCost,20);assert.equal(job.actualOverheadCost,15);assert.equal(job.conversionCost,35);const journal=state.journalEntries.find(item=>item.id===job.conversionCostJournalId);assert.equal(journal.lines.find(line=>line.accountCode==='1220').debit,35);assert.equal(journal.lines.find(line=>line.accountCode==='2100').credit,35)});

test('work order uses saved BOM snapshot instead of later unsaved edits',()=>{const state=sampleState();state.boms['P-1'][0].qty=99;const job=createProductionJob(state,{id:'j1',workOrderNo:'WO-0001',order:state.orders[0],createdAt:'2026-09-07'});assert.equal(job.materials[0].factor,2.5);assert.equal(job.materials[0].required,10)});

test('rejected FQC keeps the finished batch in quarantine under quality hold',()=>{const state=sampleState(),order=state.orders[0];createProductionJob(state,{id:'j1',workOrderNo:'WO-0001',order});releaseProductionJob(state,'j1');issueProductionJob(state,'j1');completeProductionJob(state,'j1',{completedQty:4,scrapQty:0,inspectionId:'fqc1'});state.qualityInspections[0].result='REJECTED';applyProductionQualityDecision(state,'fqc1',{ncrNo:'NCR-0001'});assert.equal(state.stock['FG-P-1']['WH-QA'],4);assert.equal(state.stock['FG-P-1']['WH-FG']||0,0);assert.equal(state.productionJobs[0].status,'QUALITY_HOLD');assert.equal(state.productionJobs[0].ncrNo,'NCR-0001')});

test('production prevents duplicate work orders and insufficient releases',()=>{const state=sampleState(),order=state.orders[0];createProductionJob(state,{id:'j1',workOrderNo:'WO-0001',order});assert.throws(()=>createProductionJob(state,{id:'j2',workOrderNo:'WO-0002',order}),/already exists/);state.stock['RM-1']['WH-RM']=9;assert.throws(()=>releaseProductionJob(state,'j1'),/Insufficient stock/);assert.equal(state.stock['RM-1'].reserved,0)});

test('completion enforces planned quantity and planned jobs can be cancelled',()=>{const state=sampleState(),order=state.orders[0];createProductionJob(state,{id:'j1',workOrderNo:'WO-0001',order});releaseProductionJob(state,'j1');issueProductionJob(state,'j1');assert.throws(()=>completeProductionJob(state,'j1',{completedQty:3,scrapQty:0}),/must equal/);assert.equal(state.stock['RM-1']['WH-SF'],10);const second=sampleState();createProductionJob(second,{id:'j2',workOrderNo:'WO-0001',order:second.orders[0]});cancelProductionJob(second,'j2');assert.equal(second.orders[0].productionStatus,'')});
