import test from 'node:test';
import assert from 'node:assert/strict';
import {customerPromise} from '../../mrp/promise-planning.js';

function state(){return{products:[{code:'FG',name:'Finished',outputSku:'FG',routingHours:1}],skus:[{code:'RM',name:'Raw',leadTime:5,safetyStock:0}],boms:{FG:[{sku:'RM',warehouse:'WH-RM',qty:2}]},bomProfiles:{},bomHistory:{},stock:{FG:{'WH-FG':20,reserved:0},RM:{'WH-RM':100,reserved:0}},orders:[{productCode:'FG',qty:8,due:'2026-09-20'}],productionJobs:[],capacityCalendar:{dailyHours:8,workDays:7,efficiencyPercent:100}}}

test('ATP confirms demand covered by uncommitted finished goods',()=>{const result=customerPromise(state(),{productCode:'FG',quantity:10,requestedDate:'2026-09-20',asOf:'2026-09-11'});assert.deepEqual({status:result.status,source:result.source,atp:result.availableToPromise,make:result.makeQty},{status:'CONFIRMED',source:'ATP_STOCK',atp:12,make:0})});
test('CTP confirms a producible shortfall inside material and capacity lead time',()=>{const result=customerPromise(state(),{productCode:'FG',quantity:20,requestedDate:'2026-09-20',asOf:'2026-09-11'});assert.equal(result.status,'CONFIRMED');assert.equal(result.makeQty,8);assert.equal(result.capacityDays,1)});
test('CTP proposes a later conditional date when material lead time misses request',()=>{const data=state();data.stock.RM['WH-RM']=0;data.skus[0].leadTime=15;const result=customerPromise(data,{productCode:'FG',quantity:20,requestedDate:'2026-09-20',asOf:'2026-09-11'});assert.deepEqual({status:result.status,promiseDate:result.promiseDate,lead:result.materialLeadDays},{status:'CONDITIONAL',promiseDate:'2026-09-26',lead:15})});
test('CTP blocks a promise without routing capacity',()=>{const data=state();data.products[0].routingHours=0;data.products[0].productionLeadTimeHours=0;const result=customerPromise(data,{productCode:'FG',quantity:20,requestedDate:'2026-09-20',asOf:'2026-09-11'});assert.equal(result.status,'BLOCKED')});
test('CTP blocks when an operation has no qualified operator',()=>{const data=state();Object.assign(data,{shiftCalendars:[{id:'S-A',code:'A',name:'Day',dailyHours:8,workDays:5,efficiencyPercent:100,active:true}],workCenters:[{id:'WC-1',code:'CUT',name:'Cutting',shiftCode:'A',machineCount:1,availabilityPercent:100,active:true}],operators:[{id:'OP-1',shift:'A',dailyHours:8,efficiencyPercent:100,skills:['PACKING'],active:true}],productRoutings:[{id:'R-1',productCode:'FG',sequence:1,operationCode:'CUT',requiredSkill:'LASER',workCenterId:'WC-1',laborMinutesPerUnit:60,operatorsRequired:1,active:true}]});const result=customerPromise(data,{productCode:'FG',quantity:20,requestedDate:'2026-09-20',asOf:'2026-09-11'});assert.equal(result.status,'BLOCKED');assert.equal(result.skillShortages[0].skill,'LASER');assert.match(result.reasons.at(-1),/No qualified operator/)});
test('CTP moves the promise date when qualified labor needs more time',()=>{const data=state();Object.assign(data,{shiftCalendars:[{id:'S-A',code:'A',name:'Day',dailyHours:8,workDays:5,efficiencyPercent:100,active:true}],workCenters:[{id:'WC-1',code:'CUT',name:'Cutting',shiftCode:'A',machineCount:1,availabilityPercent:100,active:true}],operators:[{id:'OP-1',shift:'A',dailyHours:8,efficiencyPercent:100,skills:['LASER'],active:true}],productRoutings:[{id:'R-1',productCode:'FG',sequence:1,operationCode:'CUT',requiredSkill:'LASER',workCenterId:'WC-1',laborMinutesPerUnit:120,operatorsRequired:1,active:true}]});const result=customerPromise(data,{productCode:'FG',quantity:30,requestedDate:'2026-09-12',asOf:'2026-09-11'});assert.equal(result.status,'CONDITIONAL');assert.equal(result.laborCapacityDays,3);assert.equal(result.promiseDate,'2026-09-14')});
