import test from 'node:test';
import assert from 'node:assert/strict';
import {chunkMrpRunArtifacts,externalizeMrpRunPayloads} from '../../mrp/mrp-run-artifacts.js';
import {cleanupOrphanedMrpArtifacts,hydrateStoredState,persistMrpArtifacts,snapshotMrpArtifactsForBackup} from '../src/mrp.js';

class ArtifactDb{
  constructor(){this.manifests=new Map();this.chunks=new Map()}
  prepare(sql){const db=this;return{values:[],bind(...values){this.values=values;return this},async first(){const [id,workspaceId]=this.values,row=db.manifests.get(id);if(sql.includes('SELECT head_hash'))return row&&row.workspace_id===workspaceId?{head_hash:row.head_hash,byte_length:row.byte_length,chunk_count:row.chunk_count}:null;if(sql.includes('SELECT * FROM mrp_run_artifacts'))return row&&row.workspace_id===workspaceId?row:null;throw new Error(`Unexpected first: ${sql}`)},async all(){const[id]=this.values;return{results:[...(db.chunks.get(id)||[])].sort((a,b)=>a.chunk_index-b.chunk_index)}},async run(){if(sql.includes('INSERT OR IGNORE INTO mrp_run_artifacts')){const [id,workspace_id,run_id,result_fingerprint,schema_version,byte_length,row_count,checkpoint_record_count,chunk_count,hash_algorithm,head_hash,created_by,created_at]=this.values;if(!db.manifests.has(id))db.manifests.set(id,{id,workspace_id,run_id,result_fingerprint,schema_version,byte_length,row_count,checkpoint_record_count,chunk_count,hash_algorithm,head_hash,created_by,created_at});return{success:true}}if(sql.includes('INSERT OR IGNORE INTO mrp_run_artifact_chunks')){const[artifact_id,chunk_index,chunk_count,byte_length,payload_base64,payload_hash,previous_hash,chain_hash]=this.values,items=db.chunks.get(artifact_id)||[];if(!items.some(item=>item.chunk_index===chunk_index))items.push({artifact_id,chunk_index,chunk_count,byte_length,payload_base64,payload_hash,previous_hash,chain_hash});db.chunks.set(artifact_id,items);return{success:true}}throw new Error(`Unexpected run: ${sql}`)}}}
  async batch(statements){return Promise.all(statements.map(statement=>statement.run()))}
}

class BackupDb extends ArtifactDb{
  constructor(){super();this.backupManifests=[];this.backupChunks=[];this.states=[]}
  prepare(sql){if(sql.includes('INSERT OR REPLACE INTO mrp_run_artifact_backups'))return statement(values=>{this.backupManifests.push(values);return{success:true}});if(sql.includes('INSERT OR REPLACE INTO mrp_run_artifact_chunk_backups'))return statement(values=>{this.backupChunks.push(values);return{success:true}});if(sql.includes('SELECT workspace_id,state_json FROM mrp_state'))return statement(null,()=>({results:this.states}));if(sql.includes("SELECT id FROM mrp_run_artifacts WHERE created_at"))return statement(null,()=>({results:[...this.manifests.values()].map(row=>({id:row.id}))}));if(sql.includes('DELETE FROM mrp_run_artifacts'))return statement(([id])=>{const existed=this.manifests.delete(id);this.chunks.delete(id);return{success:true,meta:{changes:existed?1:0}}});return super.prepare(sql)}
}
const statement=(run,all)=>({values:[],bind(...values){this.values=values;return this},async run(){return run(this.values)},async all(){return all(this.values)}});

const source=(workspace,marker)=>({schemaVersion:6,mrpRuns:[{id:'R1',resultFingerprint:'same-fingerprint',rows:Array.from({length:400},(_,index)=>({key:`${marker}-${index}`,plannedQuantity:index})),timeBucketCheckpoints:null}],workspace});

test('D1 artifact persistence round-trips a large run',async()=>{const original=source('W1','A'),external=externalizeMrpRunPayloads(original,{thresholdBytes:1}),chunked=chunkMrpRunArtifacts(external.artifacts,{chunkBytes:1024}),DB=new ArtifactDb(),actor={workspace:{id:'W1'},user:{id:'U1'}};await persistMrpArtifacts({DB},actor,chunked.manifests,chunked.chunks);assert.deepEqual(await hydrateStoredState({DB},'W1',external.coreState),original);assert.ok(DB.chunks.get('W1:R1:same-fingerprint').length>1)});

test('physical artifact ids isolate tenants with identical logical run ids',async()=>{const DB=new ArtifactDb();for(const [workspace,marker] of [['W1','A'],['W2','B']]){const original=source(workspace,marker),external=externalizeMrpRunPayloads(original,{thresholdBytes:1}),chunked=chunkMrpRunArtifacts(external.artifacts,{chunkBytes:1024});await persistMrpArtifacts({DB},{workspace:{id:workspace},user:{id:'U1'}},chunked.manifests,chunked.chunks);assert.deepEqual(await hydrateStoredState({DB},workspace,external.coreState),original)}assert.ok(DB.manifests.has('W1:R1:same-fingerprint'));assert.ok(DB.manifests.has('W2:R1:same-fingerprint'))});

test('D1 hydration fails closed when a stored chunk is changed',async()=>{const original=source('W1','A'),external=externalizeMrpRunPayloads(original,{thresholdBytes:1}),chunked=chunkMrpRunArtifacts(external.artifacts,{chunkBytes:1024}),DB=new ArtifactDb(),actor={workspace:{id:'W1'},user:{id:'U1'}};await persistMrpArtifacts({DB},actor,chunked.manifests,chunked.chunks);DB.chunks.get('W1:R1:same-fingerprint')[0].payload_base64='A'+DB.chunks.get('W1:R1:same-fingerprint')[0].payload_base64.slice(1);await assert.rejects(()=>hydrateStoredState({DB},'W1',external.coreState),/integrity failed/)});

test('backup snapshot retains every verified manifest and chunk',async()=>{const original=source('W1','A'),external=externalizeMrpRunPayloads(original,{thresholdBytes:1}),chunked=chunkMrpRunArtifacts(external.artifacts,{chunkBytes:1024}),DB=new BackupDb(),actor={workspace:{id:'W1'},user:{id:'U1'}};await persistMrpArtifacts({DB},actor,chunked.manifests,chunked.chunks);const result=await snapshotMrpArtifactsForBackup({DB},'B1','W1',JSON.stringify(external.coreState));assert.equal(result.artifacts,1);assert.equal(DB.backupManifests.length,1);assert.equal(DB.backupChunks.length,chunked.chunks.length)});

test('orphan cleanup keeps referenced artifacts and removes only unreferenced candidates',async()=>{const DB=new BackupDb();for(const [workspace,marker] of [['W1','A'],['W2','B']]){const external=externalizeMrpRunPayloads(source(workspace,marker),{thresholdBytes:1}),chunked=chunkMrpRunArtifacts(external.artifacts,{chunkBytes:1024});await persistMrpArtifacts({DB},{workspace:{id:workspace},user:{id:'U1'}},chunked.manifests,chunked.chunks);if(workspace==='W1')DB.states.push({workspace_id:workspace,state_json:JSON.stringify(external.coreState)})}const result=await cleanupOrphanedMrpArtifacts({DB});assert.equal(result.removed,1);assert.ok(DB.manifests.has('W1:R1:same-fingerprint'));assert.equal(DB.manifests.has('W2:R1:same-fingerprint'),false)});
