import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeAdvancedManufacturing,explodeRequirements,masterProductionSchedule,classifyInventory,inventoryPolicy,allocateFefoLots,oeeSummary} from '../../mrp/advanced-manufacturing.js';

function sample(){return{products:[{code:'FG',name:'Finished',outputSku:'FG',productionStrategy:'MTS',mtsTarget:20,routingHours:0.5},{code:'SUB',name:'Phantom kit',outputSku:'SUB',phantom:true}],skus:[{code:'FG',name:'Finished',cost:20,active:true},{code:'SUB',name:'Kit',cost:4,active:true},{code:'RM',name:'Raw',cost:5,leadTime:10,safetyStock:5,active:true}],boms:{FG:[{sku:'SUB',warehouse:'WH-RM',qty:2,wastePercent:0}],SUB:[{sku:'RM',warehouse:'WH-RM',qty:3,wastePercent:10}]},bomProfiles:{FG:{version:'1'},SUB:{version:'1'}},bomHistory:{FG:[{version:'1',effectiveDate:'2026-01-01',materials:[{sku:'SUB',warehouse:'WH-RM',qty:2,wastePercent:0}]}],SUB:[{version:'1',effectiveDate:'2026-01-01',materials:[{sku:'RM',warehouse:'WH-RM',qty:3,wastePercent:10}]}]},orders:[{productCode:'FG',qty:10,due:'2026-09-20'}],stock:{FG:{'WH-FG':5,reserved:0},RM:{'WH-RM':50,reserved:0}},inventoryMovements:[],inventoryLots:[],operationSessions:[]}}

test('multi-level explosion passes through phantom BOM and includes safety stock',()=>{const state=sample(),rows=explodeRequirements(state,'FG',10,{onDate:'2026-09-11'});assert.equal(rows.length,1);assert.equal(rows[0].grossRequired,66);assert.equal(rows[0].netRequired,21);assert.deepEqual(rows[0].levels,[2])});
test('MTS schedule replenishes target and finite capacity flags overload',()=>{const state=sample();normalizeAdvancedManufacturing(state);state.capacityCalendar={dailyHours:8,workDays:1,efficiencyPercent:100};const plan=masterProductionSchedule(state,{horizonDays:30});assert.equal(plan.rows.find(x=>x.productCode==='FG').plannedQty,25);assert.equal(plan.capacity.status,'OVERLOADED')});
test('inventory analysis assigns ABC XYZ, reorder policy and cycle frequency',()=>{const state=sample();state.inventoryMovements=[{sku:'RM',direction:'OUT',qty:100,at:'2026-01-01'},{sku:'RM',direction:'OUT',qty:100,at:'2026-02-01'}];const rows=classifyInventory(state);assert.equal(rows[0].abc,'A');assert.equal(state.skus.find(x=>x.code==='RM').cycleCountDays,30);assert.equal(inventoryPolicy(state,'RM').reorderPoint>5,true)});
test('FEFO rejects expired lots and allocates earliest expiry first',()=>{const state=sample();state.inventoryLots=[{sku:'RM',warehouse:'WH-RM',lotNo:'OLD',quantity:5,expiryDate:'2026-09-01'},{sku:'RM',warehouse:'WH-RM',lotNo:'L2',quantity:7,expiryDate:'2026-10-01'},{sku:'RM',warehouse:'WH-RM',lotNo:'L3',quantity:7,expiryDate:'2026-11-01'}];assert.deepEqual(allocateFefoLots(state,{sku:'RM',warehouse:'WH-RM',quantity:10,onDate:'2026-09-11'}).map(x=>[x.lotNo,x.quantity]),[['L2',7],['L3',3]])});
test('OEE combines availability performance and quality',()=>{const state=sample();state.operationSessions=[{status:'COMPLETED',actualMinutes:80,downtimeMinutes:20,inputQty:100,goodQty:90,idealCycleMinutes:.8}];assert.deepEqual(oeeSummary(state,{plannedMinutes:100}),{availability:80,performance:90,quality:90,oee:64.8})});
