import test from 'node:test';
import assert from 'node:assert/strict';
import {ensureBomProfile,addBomVariable,calculateBomCost,validateBomRevision,saveBomRevision,bomSnapshot,activateBomRevision} from '../../mrp/bom-workflow.js';

function sampleState(){return{products:[{code:'P1',name:'Product'}],skus:[{code:'RM1',name:'Material',type:'RAW_MATERIAL',unit:'KG',cost:4},{code:'PK1',name:'Carton',type:'PACKAGING',unit:'ADET',cost:1}],warehouses:[{code:'WH-RM'},{code:'WH-PK'}],boms:{P1:[{sku:'RM1',qty:2,warehouse:'WH-RM',wastePercent:10},{sku:'PK1',qty:1,warehouse:'WH-PK',wastePercent:0}]},bomProfiles:{},bomHistory:{}}}

test('BOM calculates material, packaging, conversion, unit and production costs',()=>{const state=sampleState(),profile=ensureBomProfile(state,'P1');profile.laborCost=2;profile.overheadCost=1;profile.otherCost=.2;const cost=calculateBomCost(state,'P1',{profile,quantity:10});assert.equal(cost.materialCost,8.8);assert.equal(cost.packagingCost,1);assert.equal(cost.unitCost,13);assert.equal(cost.totalCost,130);assert.equal(cost.lines[0].grossQty,2.2)});

test('BOM profile stores an immutable version and rejects overwriting it',()=>{const state=sampleState(),profile=ensureBomProfile(state,'P1');profile.version='2.3';profile.effectiveDate='2026-01-01';profile.model='M-A';addBomVariable(state,'P1');profile.variables[0]={name:'Temperature',value:'180',unit:'C',category:'PROCESS',required:true};const saved=saveBomRevision(state,'P1',{user:'planner',device:'PC-01',at:'2026-09-08T10:00:00Z'});profile.variables[0].value='190';state.boms.P1[0].qty=99;assert.equal(saved.version,'2.3');assert.equal(saved.variables[0].value,'180');assert.equal(saved.materials[0].qty,2);assert.equal(bomSnapshot(state,'P1','2026-09-08').materials[0].qty,2);assert.throws(()=>saveBomRevision(state,'P1'),/already exists/)});

test('a saved BOM version can be reactivated with its materials and costs',()=>{const state=sampleState(),profile=ensureBomProfile(state,'P1');profile.version='1.0';profile.effectiveDate='2026-01-01';profile.laborCost=3;saveBomRevision(state,'P1',{at:'2026-01-01T00:00:00Z'});profile.version='2.0';state.boms.P1[0].qty=5;saveBomRevision(state,'P1',{at:'2026-02-01T00:00:00Z'});activateBomRevision(state,'P1','1.0');assert.equal(profile.version,'1.0');assert.equal(profile.laborCost,3);assert.equal(state.boms.P1[0].qty,2)});

test('BOM rejects invalid rows, duplicate components and future revisions',()=>{const state=sampleState(),profile=ensureBomProfile(state,'P1');profile.effectiveDate='2026-10-01';state.boms.P1.push({sku:'RM1',qty:0,warehouse:'WH-RM'});const errors=validateBomRevision(state,'P1');assert.ok(errors.some(error=>error.includes('duplicate')));assert.ok(errors.some(error=>error.includes('greater than zero')));state.boms.P1.pop();saveBomRevision(state,'P1',{at:'2026-09-08T00:00:00Z'});assert.throws(()=>bomSnapshot(state,'P1','2026-09-08'),/not effective/)});

test('BOM profile enforces twenty process variables in addition to materials',()=>{const state=sampleState();state.boms.P1=Array.from({length:30},(_,i)=>({sku:`RM${i}`,qty:1}));for(let i=0;i<20;i++)addBomVariable(state,'P1');assert.throws(()=>addBomVariable(state,'P1'),/at most 20/);assert.equal(state.boms.P1.length,30)});
