import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {evaluateMrp2Conformance,createMrp2Assessment,reviewMrp2Assessment,approveMrp2Assessment} from '../../mrp/mrp2-conformance.js';

test('empty system exposes gaps without claiming certification',()=>{const report=evaluateMrp2Conformance({});assert.equal(report.controls.length,16);assert.equal(report.result,'GAPS_OPEN');assert.ok(report.fail>0);assert.match(report.claim,/not third-party certification/i)});

test('complete operating evidence aligns every internal control',()=>{const state={products:[{code:'FG-1'}],orders:[{status:'OPEN'}],demandForecasts:[],sopPlans:[{status:'APPROVED'}],mpsSnapshots:[{status:'FROZEN'}],mrpRuns:[{status:'RELEASED'}],planningTimeFences:{demandDays:7,planningDays:21},bomHistory:{'FG-1':[{}]},mrpExceptionLastSyncAt:'2026-09-11T08:00:00Z',mrpExceptionActions:[],workCenters:[{active:true}],shiftCalendars:[{active:true}],productRoutings:[{active:true}],productionSchedules:[{status:'RELEASED'}],operationSessions:[{status:'COMPLETED'}],purchaseOrders:[{status:'APPROVED'}],supplierSchedules:[{status:'CONFIRMED'}],cycleCounts:[{status:'APPROVED'}],wipSettlements:[{}],capacityFeedbackActions:[{}],accountingPeriods:[{}],journalEntries:[{status:'POSTED',lines:[{debit:10},{credit:10}]}],planningCycles:[{status:'CLOSED'}],auditTrail:[{}]};const report=evaluateMrp2Conformance(state);assert.equal(report.result,'ALIGNED');assert.equal(report.score,100);assert.equal(report.pass,16)});

test('partial evidence produces conditional alignment without hiding gaps',()=>{const state={products:[],orders:[{status:'OPEN'}],sopPlans:[{status:'APPROVED'}],mpsSnapshots:[{status:'FROZEN'}],mrpRuns:[{status:'RELEASED'}],planningTimeFences:{demandDays:7,planningDays:21},mrpExceptionLastSyncAt:'2026-09-11',workCenters:[{}],shiftCalendars:[{}],productRoutings:[{}],productionSchedules:[{status:'RELEASED'}],operationSessions:[],purchaseOrders:[],supplierSchedules:[],cycleCounts:[],wipSettlements:[],capacityFeedbackActions:[],accountingPeriods:[],journalEntries:[],planningCycles:[{}],auditTrail:[{}]};const report=evaluateMrp2Conformance(state);assert.equal(report.fail,0);assert.ok(report.partial>0);assert.equal(report.result,'CONDITIONALLY_ALIGNED')});

test('assessment snapshot preserves the evaluated controls',()=>{const state={mrp2Assessments:[],auditTrail:[]},item=createMrp2Assessment(state,{preparedBy:'lead',scopeNote:'Complete planning control scope'});const score=item.score;state.sopPlans=[{status:'APPROVED'}];assert.equal(item.score,score);assert.equal(item.controls.length,16)});

test('assessment review and approval enforce three independent identities',()=>{const state={mrp2Assessments:[],auditTrail:[]},item=createMrp2Assessment(state,{preparedBy:'lead',scopeNote:'Complete planning control scope'});assert.throws(()=>reviewMrp2Assessment(state,item.id,{reviewedBy:'lead',reviewNote:'Evidence was reviewed'}),/independent/i);reviewMrp2Assessment(state,item.id,{reviewedBy:'control',reviewNote:'Evidence was independently reviewed'});assert.throws(()=>approveMrp2Assessment(state,item.id,{approvedBy:'control',remediationDecision:'Assign every open control gap'}),/independent/i);approveMrp2Assessment(state,item.id,{approvedBy:'manager',remediationDecision:'Assign every open control gap'});assert.equal(item.status,'APPROVED')});

test('conformance interface identifiers are unique',()=>{const html=readFileSync(new URL('../../mrp/index.html',import.meta.url),'utf8');for(const id of ['mrp2ConformanceStatus','mrp2AssessmentPreparer','mrp2AssessmentReviewer','mrp2AssessmentApprover','mrp2AssessmentScope','mrp2AssessmentReviewNote','mrp2AssessmentRemediation','createMrp2Assessment','mrp2ConformanceKpis','mrp2ConformanceTable','mrp2ConformanceClaim','mrp2AssessmentRegister'])assert.equal((html.match(new RegExp(`id="${id}"`,'g'))||[]).length,1)});
