import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {masterDataFingerprint} from '../../mrp/master-data-quality.js';
import {evaluateMrp2E2e,createMrp2E2eValidation,reviewMrp2E2eValidation,approveMrp2E2eValidation} from '../../mrp/mrp2-e2e-validation.js';

const complete=()=>{const state={products:[],skus:[],warehouses:[],workCenters:[],productRoutings:[],suppliers:[],purchaseOrders:[],accountingSettings:{profile:'IFRS_TFRS'},sopPlans:[{id:'SOP-1',planNo:'SOP-00001',status:'APPROVED'}],mpsSnapshots:[{id:'MPS-1',versionNo:'MPS-00001',status:'FROZEN',sourceSopPlanNo:'SOP-00001'}],productionSchedules:[{scheduleNo:'DPS-00001',status:'RELEASED'}],supplierSchedules:[],inventoryMovements:[{direction:'IN'},{direction:'OUT'}],productionJobs:[{status:'COMPLETED'}],productionVariancePostings:[{}],wipSettlements:[{}],journalEntries:[{status:'POSTED',lines:[{debit:10},{credit:10}]}],accountingPeriods:[{}],businessCashflowPlans:[{planNo:'BCF-00001',status:'APPROVED'}],planningCycles:[{cycleNo:'PC-00001',status:'CLOSED'}],mrp2Assessments:[{assessmentNo:'M2A-00001',status:'APPROVED'}],mrp2E2eValidations:[],auditTrail:[]};const fingerprint=masterDataFingerprint(state);state.masterDataQualityGates=[{gateNo:'MDQ-00001',status:'APPROVED',fingerprint}];state.mrpRuns=[{runNo:'MRP-00001',status:'RELEASED',sourceMpsId:'MPS-1',masterDataGateNo:'MDQ-00001'}];return state};
test('complete linked evidence chain passes all twelve stages',()=>{const result=evaluateMrp2E2e(complete());assert.equal(result.stages.length,12);assert.equal(result.fail,0);assert.equal(result.score,100);assert.equal(result.result,'REPEAT_REQUIRED')});
test('broken source linkage blocks validation',()=>{const state=complete();state.mrpRuns[0].sourceMpsId='OLD';const result=evaluateMrp2E2e(state);assert.equal(result.result,'BLOCKED');assert.equal(result.stages.find(item=>item.code==='E2E-04').status,'FAIL')});
test('three identical executions establish repeatability',()=>{const state=complete();const first=createMrp2E2eValidation(state,{executedBy:'tester',scopeNote:'Full controlled manufacturing loop'}),second=createMrp2E2eValidation(state,{executedBy:'tester',scopeNote:'Full controlled manufacturing loop'}),third=createMrp2E2eValidation(state,{executedBy:'tester',scopeNote:'Full controlled manufacturing loop'});assert.equal(first.repeatSequence,1);assert.equal(second.repeatSequence,2);assert.equal(third.repeatSequence,3);assert.equal(third.validationResult,'VALIDATED')});
test('review and approval enforce evidence and independent identities',()=>{const state=complete();createMrp2E2eValidation(state,{executedBy:'tester',scopeNote:'Full controlled manufacturing loop'});createMrp2E2eValidation(state,{executedBy:'tester',scopeNote:'Full controlled manufacturing loop'});const item=createMrp2E2eValidation(state,{executedBy:'tester',scopeNote:'Full controlled manufacturing loop'});assert.throws(()=>reviewMrp2E2eValidation(state,item.id,{reviewedBy:'tester',reviewNote:'Reviewed the complete evidence chain'}),/independent/i);reviewMrp2E2eValidation(state,item.id,{reviewedBy:'controller',reviewNote:'Reviewed the complete evidence chain'});assert.throws(()=>approveMrp2E2eValidation(state,item.id,{approvedBy:'controller',acceptanceNote:'Accept the repeated validation'}),/independent/i);approveMrp2E2eValidation(state,item.id,{approvedBy:'manager',acceptanceNote:'Accept the repeated validation evidence'});assert.equal(item.status,'APPROVED')});
test('validation interface identifiers are unique',()=>{const html=readFileSync(new URL('../../mrp/index.html',import.meta.url),'utf8');for(const id of ['mrp2E2eStatus','mrp2E2eExecutor','mrp2E2eReviewer','mrp2E2eApprover','mrp2E2eScope','mrp2E2eReviewNote','mrp2E2eAcceptance','createMrp2E2eValidation','mrp2E2eKpis','mrp2E2eStageTable','mrp2E2eClaim','mrp2E2eRegister'])assert.equal((html.match(new RegExp(`id="${id}"`,'g'))||[]).length,1)});
