import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {buildSopScenario,createSopPlan,reviewSopPlan,approveSopPlan} from '../../mrp/sop-executive-planning.js';

function sample(){return{products:[{code:'FG-1',outputSku:'FG-1',productionStrategy:'MTS',routingHours:2,salesPrice:20}],skus:[{code:'FG-1',cost:5}],stock:{'FG-1':{'WH-FG':20}},orders:[{productCode:'FG-1',qty:40,due:'2026-09-20',status:'OPEN'}],demandForecasts:[{productCode:'FG-1',period:'2026-09',quantity:100,status:'APPROVED'}],capacityCalendar:{dailyHours:8,workDays:5,efficiencyPercent:100},bomHistory:{'FG-1':[{version:'1',standardUnitCost:5}]},bomProfiles:{'FG-1':{version:'1'}},auditTrail:[]}}

test('S&OP consumes firm demand from forecast and balances inventory target',()=>{const plan=buildSopScenario(sample(),{startPeriod:'2026-09',horizonMonths:1,scenario:'BASE',inventoryTargetPercent:10}),row=plan.rows[0];assert.equal(row.firmDemand,40);assert.equal(row.forecastDemand,60);assert.equal(row.adjustedDemand,100);assert.equal(row.plannedProduction,90);assert.equal(row.endingInventory,10)});
test('upside scenario adjusts demand and capacity while exposing overload',()=>{const plan=buildSopScenario(sample(),{startPeriod:'2026-09',horizonMonths:1,scenario:'UPSIDE',inventoryTargetPercent:10}),row=plan.rows[0];assert.equal(row.adjustedDemand,110);assert.equal(row.plannedProduction,101);assert.equal(row.capacityStatus,'OVERLOADED');assert.equal(plan.totals.revenue,2200);assert.equal(plan.totals.productionCost,505)});
test('S&OP requires independent cross-functional review and executive approval',()=>{const state=sample(),plan=createSopPlan(state,{startPeriod:'2026-09',horizonMonths:1,scenario:'BASE',inventoryTargetPercent:10,preparedBy:'planner',assumptions:'Current approved operating assumptions'});assert.throws(()=>reviewSopPlan(state,plan.id,{reviewedBy:'planner'}),/independent/);reviewSopPlan(state,plan.id,{reviewedBy:'factory-manager'});assert.throws(()=>approveSopPlan(state,plan.id,{approvedBy:'factory-manager'}),/independent/);approveSopPlan(state,plan.id,{approvedBy:'ceo'});assert.equal(plan.status,'APPROVED');assert.deepEqual(plan.history.map(item=>item.action),['CREATED','REVIEWED','APPROVED']);assert.equal(state.auditTrail.length,3)});
test('S&OP interface controls have unique identifiers',()=>{const html=readFileSync(new URL('../../mrp/index.html',import.meta.url),'utf8');for(const id of ['sopStartPeriod','sopHorizon','sopScenario','sopInventoryTarget','sopPreparer','sopReviewer','sopApprover','sopAssumptions','createSopPlan','sopPreviewKpis','sopPreviewTable','sopPlanRegister'])assert.equal((html.match(new RegExp(`id="${id}"`,'g'))||[]).length,1)});
