import test from 'node:test';
import assert from 'node:assert/strict';
import {assessStabilityFrontier,frontierZone} from '../../mrp/stability-frontier.js';
import {approveStabilityOverride,createMrpRun,releaseMrpRun,requestStabilityOverride,reviewMrpRun} from '../../mrp/mrp-run-governance.js';
import {masterDataFingerprint} from '../../mrp/master-data-quality.js';

test('frontier classifies frozen slushy and liquid release dates',()=>{const context={asOf:'2026-09-01',demandDays:7,planningDays:21};assert.equal(frontierZone('2026-09-08',context),'FROZEN');assert.equal(frontierZone('2026-09-15',context),'SLUSHY');assert.equal(frontierZone('2026-09-30',context),'LIQUID')});

test('frontier assessment blocks frozen changes and flags slushy changes',()=>{const result=assessStabilityFrontier({planningTimeFences:{demandDays:7,planningDays:21}},[{key:'A',type:'CHANGED',currentReleaseDate:'2026-09-05',quantityChange:1},{key:'B',type:'CHANGED',currentReleaseDate:'2026-09-15',quantityChange:1},{key:'C',type:'NEW',currentReleaseDate:'2026-09-30',quantityChange:1}],{asOf:'2026-09-01'});assert.equal(result.blocked.length,1);assert.equal(result.review.length,1);assert.equal(result.allowed.length,1)});

test('release gate rejects unresolved frozen-frontier changes',()=>{const value={products:[],skus:[],orders:[],plannedSupplyOrders:[],purchaseOrders:[],mpsSnapshots:[{id:'MPS-1',status:'FROZEN'}],mrpRuns:[],auditTrail:[],planningTimeFences:{demandDays:7,planningDays:21}};value.masterDataQualityGates=[{id:'MDQ-1',gateNo:'MDQ-00001',status:'APPROVED',fingerprint:masterDataFingerprint(value)}];const baseline={id:'BASE',status:'RELEASED',rows:[{key:'A',orderNo:'O1',sku:'R1',plannedQuantity:1,releaseDate:'2026-09-05',status:'PLANNED'}],inputSnapshot:null};value.mrpRuns=[baseline];const run=createMrpRun(value,{asOf:'2026-09-01',mode:'FULL',plannedBy:'planner'});reviewMrpRun(value,run.id,{reviewedBy:'reviewer',decision:'Reviewed planning changes'});assert.equal(run.stabilityFrontier.blocked.length,1);assert.throws(()=>releaseMrpRun(value,run.id,{releasedBy:'manager'}),/Frozen stability frontier/i)});

test('independent executive override permits an evidenced frozen-frontier release',()=>{const value={products:[],skus:[],orders:[],plannedSupplyOrders:[],purchaseOrders:[],mpsSnapshots:[{id:'MPS-1',status:'FROZEN'}],mrpRuns:[],auditTrail:[],planningTimeFences:{demandDays:7,planningDays:21}};value.masterDataQualityGates=[{id:'MDQ-1',gateNo:'MDQ-00001',status:'APPROVED',fingerprint:masterDataFingerprint(value)}];value.mrpRuns=[{id:'BASE',status:'RELEASED',rows:[{key:'A',orderNo:'O1',sku:'R1',plannedQuantity:1,releaseDate:'2026-09-05',status:'PLANNED'}],inputSnapshot:null}];const run=createMrpRun(value,{asOf:'2026-09-01',mode:'FULL',plannedBy:'planner'});reviewMrpRun(value,run.id,{reviewedBy:'reviewer',decision:'Reviewed planning changes'});requestStabilityOverride(value,run.id,{requestedBy:'operations-lead',reason:'Customer safety commitment requires an emergency controlled change.'});assert.throws(()=>approveStabilityOverride(value,run.id,{approvedBy:'operations-lead',role:'CEO',decision:'Emergency change approved'}),/independent/i);approveStabilityOverride(value,run.id,{approvedBy:'executive',role:'CEO',decision:'Emergency change approved'});releaseMrpRun(value,run.id,{releasedBy:'release-manager'});assert.equal(run.status,'RELEASED');assert.equal(run.stabilityOverride.status,'APPROVED');assert.ok(Object.isFrozen(run.stabilityOverride))});
