import test from 'node:test';
import assert from 'node:assert/strict';
import {timePhasedMaterialPlan,plannedSupplyExceptions,firmPlannedSupply,updatePlannedSupply,submitPlannedSupply,approvePlannedSupply,rejectPlannedSupply,releasePlannedSupply,cancelPlannedSupply} from '../../mrp/time-phased-mrp.js';

function state(){return{products:[{code:'P1',name:'Product'}],skus:[{code:'RM1',name:'Material',warehouse:'WH-RM',leadTime:7,safetyStock:3,minimumOrderQty:10,orderMultiple:5}],orders:[{id:'O1',orderNo:'ORD-1',productCode:'P1',qty:10,due:'2026-09-30',priority:'URGENT'}],boms:{P1:[{sku:'RM1',warehouse:'WH-RM',qty:2,wastePercent:0}]},bomProfiles:{},bomHistory:{},stock:{RM1:{'WH-RM':5,reserved:0}},purchaseOrders:[{poNo:'PO-1',sku:'RM1',qty:6,dueDate:'2026-09-20',status:'APPROVED'}],plannedSupplyOrders:[]}}

test('time-phased MRP nets dated supply and calculates pegged release date with lot sizing',()=>{const plan=timePhasedMaterialPlan(state(),{asOf:'2026-09-11',horizonDays:30}),row=plan.rows[0];assert.deepEqual({gross:row.grossRequired,available:row.availableBefore,receipts:row.scheduledReceipts,net:row.netRequired,planned:row.plannedQuantity,release:row.releaseDate,action:row.action,status:row.status},{gross:20,available:11,receipts:6,net:12,planned:15,release:'2026-09-23',action:'BUY',status:'PLANNED'});assert.equal(plan.plannedBuy,15)});

test('approved S&OP forecast flows through MPS demand into time-phased material requirements',()=>{const data=state();data.products[0].productionStrategy='MTS';data.demandForecasts=[{id:'FC1',forecastNo:'FC-00001',productCode:'P1',period:'2026-09',quantity:30,status:'APPROVED'}];const plan=timePhasedMaterialPlan(data,{asOf:'2026-09-11',horizonDays:30}),forecastRow=plan.rows.find(row=>row.orderNo.startsWith('FC-00001'));assert.equal(forecastRow.grossRequired,40);assert.equal(plan.plannedBuy,55)});

test('firm planned order preserves demand pegging and prevents duplicate firming',()=>{const data=state(),row=timePhasedMaterialPlan(data,{asOf:'2026-09-11',horizonDays:30}).rows[0],firm=firmPlannedSupply(data,row,{id:'F1',createdBy:'planner'});assert.equal(firm.sourceOrderNo,'ORD-1');assert.equal(firm.peggingKey,'ORD-1|P1|RM1|WH-RM|2026-09-30');assert.throws(()=>firmPlannedSupply(data,row),/already covers/);cancelPlannedSupply(data,'F1',{cancelledBy:'manager'});assert.equal(firm.status,'CANCELLED');assert.doesNotThrow(()=>firmPlannedSupply(data,row,{id:'F2'}))});

test('closed-loop MRP detects aligned, increased and cancelled supply recommendations',()=>{const data=state(),row=timePhasedMaterialPlan(data,{asOf:'2026-09-11',horizonDays:30}).rows[0];firmPlannedSupply(data,row,{id:'F1'});assert.deepEqual(plannedSupplyExceptions(data,{asOf:'2026-09-11',horizonDays:30}).rows[0].actions,['ALIGNED']);data.stock.RM1['WH-RM']=0;data.purchaseOrders=[];let exception=plannedSupplyExceptions(data,{asOf:'2026-09-11',horizonDays:30}).rows[0];assert.equal(exception.suggestedQuantity,25);assert.ok(exception.actions.includes('INCREASE'));data.stock.RM1['WH-RM']=30;exception=plannedSupplyExceptions(data,{asOf:'2026-09-11',horizonDays:30}).rows[0];assert.deepEqual(exception.actions,['CANCEL_REVIEW'])});

test('closed-loop MRP finds a reschedule after the pegged demand date changes',()=>{const data=state(),row=timePhasedMaterialPlan(data,{asOf:'2026-09-11',horizonDays:30}).rows[0];firmPlannedSupply(data,row,{id:'F1'});data.orders[0].due='2026-09-25';const exception=plannedSupplyExceptions(data,{asOf:'2026-09-11',horizonDays:30}).rows[0];assert.ok(exception.actions.includes('EXPEDITE'));assert.equal(exception.suggestedReleaseDate,'2026-09-18');assert.equal(exception.suggestedNeedDate,'2026-09-25')});

test('planned order requires an independent management approval before release',()=>{const data=state(),row=timePhasedMaterialPlan(data,{asOf:'2026-09-11',horizonDays:30}).rows[0],firm=firmPlannedSupply(data,row,{id:'F1',createdBy:'planner'});updatePlannedSupply(data,firm.id,{quantity:20,releaseDate:'2026-09-22',needDate:'2026-09-30',user:'planner'});assert.equal(firm.quantity,20);assert.throws(()=>releasePlannedSupply(data,firm.id),/approval is required/);submitPlannedSupply(data,firm.id,{submittedBy:'planner'});assert.throws(()=>updatePlannedSupply(data,firm.id,{quantity:25,releaseDate:'2026-09-22',needDate:'2026-09-30'}),/can be edited/);assert.throws(()=>approvePlannedSupply(data,firm.id,{approvedBy:'planner'}),/independent/);approvePlannedSupply(data,firm.id,{approvedBy:'manager'});assert.equal(firm.status,'APPROVED');assert.deepEqual(firm.history.map(entry=>entry.action),['FIRMED','EDITED','SUBMITTED','APPROVED'])});

test('submitted order can be rejected only with a reason by an independent reviewer',()=>{const data=state(),row=timePhasedMaterialPlan(data,{asOf:'2026-09-11',horizonDays:30}).rows[0],firm=firmPlannedSupply(data,row,{id:'F1',createdBy:'planner'});submitPlannedSupply(data,firm.id,{submittedBy:'planner'});assert.throws(()=>rejectPlannedSupply(data,firm.id,{rejectedBy:'manager'}),/reason is required/);rejectPlannedSupply(data,firm.id,{rejectedBy:'manager',reason:'Budget unavailable'});assert.equal(firm.status,'REJECTED');assert.equal(firm.rejectionReason,'Budget unavailable')});

test('release converts BUY plan to a pegged purchase request',()=>{const data=state(),row=timePhasedMaterialPlan(data,{asOf:'2026-09-11',horizonDays:30}).rows[0],firm=firmPlannedSupply(data,row,{id:'F1',createdBy:'planner'});submitPlannedSupply(data,firm.id,{submittedBy:'planner'});approvePlannedSupply(data,firm.id,{approvedBy:'manager'});releasePlannedSupply(data,firm.id,{releasedAt:'2026-09-12T08:00:00Z',releasedBy:'buyer',documentId:'PR1',documentNo:'PR-100'});assert.equal(firm.status,'RELEASED');assert.deepEqual({reference:firm.releasedReference,source:data.purchaseRequests[0].source,plannedOrderId:data.purchaseRequests[0].plannedOrderId,order:data.purchaseRequests[0].sourceOrders[0]},{reference:'PR-100',source:'TIME_PHASED_MRP',plannedOrderId:'F1',order:'ORD-1'})});

test('release converts MAKE plan to an internal production order',()=>{const data=state();data.products.push({code:'SF-P',name:'Semi Finished',outputSku:'SF1'});const firm=firmPlannedSupply(data,{plannedQuantity:8,action:'MAKE',sku:'SF1',warehouse:'WH-SF',releaseDate:'2026-09-20',needDate:'2026-09-25',orderNo:'ORD-1',productCode:'P1',priority:'URGENT'},{id:'M1',createdBy:'planner'});submitPlannedSupply(data,firm.id,{submittedBy:'planner'});approvePlannedSupply(data,firm.id,{approvedBy:'manager'});releasePlannedSupply(data,firm.id,{releasedAt:'2026-09-12T08:00:00Z',releasedBy:'planner',documentId:'MO1',documentNo:'MO-100'});const order=data.orders[0];assert.deepEqual({product:order.productCode,qty:order.qty,parent:order.parentOrderNo,source:order.source,reference:firm.releasedReference},{product:'SF-P',qty:8,parent:'ORD-1',source:'TIME_PHASED_MRP',reference:'MO-100'})});
