import test from 'node:test';
import assert from 'node:assert/strict';
import {timePhasedMaterialPlan,firmPlannedSupply,releasePlannedSupply,cancelPlannedSupply} from '../../mrp/time-phased-mrp.js';

function state(){return{products:[{code:'P1',name:'Product'}],skus:[{code:'RM1',name:'Material',warehouse:'WH-RM',leadTime:7,safetyStock:3,minimumOrderQty:10,orderMultiple:5}],orders:[{id:'O1',orderNo:'ORD-1',productCode:'P1',qty:10,due:'2026-09-30',priority:'URGENT'}],boms:{P1:[{sku:'RM1',warehouse:'WH-RM',qty:2,wastePercent:0}]},bomProfiles:{},bomHistory:{},stock:{RM1:{'WH-RM':5,reserved:0}},purchaseOrders:[{poNo:'PO-1',sku:'RM1',qty:6,dueDate:'2026-09-20',status:'APPROVED'}],plannedSupplyOrders:[]}}

test('time-phased MRP nets dated supply and calculates pegged release date with lot sizing',()=>{const plan=timePhasedMaterialPlan(state(),{asOf:'2026-09-11',horizonDays:30}),row=plan.rows[0];assert.deepEqual({gross:row.grossRequired,available:row.availableBefore,receipts:row.scheduledReceipts,net:row.netRequired,planned:row.plannedQuantity,release:row.releaseDate,action:row.action,status:row.status},{gross:20,available:11,receipts:6,net:12,planned:15,release:'2026-09-23',action:'BUY',status:'PLANNED'});assert.equal(plan.plannedBuy,15)});

test('firm planned order preserves demand pegging and prevents duplicate firming',()=>{const data=state(),row=timePhasedMaterialPlan(data,{asOf:'2026-09-11',horizonDays:30}).rows[0],firm=firmPlannedSupply(data,row,{id:'F1',createdBy:'planner'});assert.equal(firm.sourceOrderNo,'ORD-1');assert.equal(firm.peggingKey,'ORD-1|P1|RM1|WH-RM|2026-09-30');assert.throws(()=>firmPlannedSupply(data,row),/already covers/);cancelPlannedSupply(data,'F1',{cancelledBy:'manager'});assert.equal(firm.status,'CANCELLED');assert.doesNotThrow(()=>firmPlannedSupply(data,row,{id:'F2'}))});

test('release converts BUY plan to a pegged purchase request',()=>{const data=state(),row=timePhasedMaterialPlan(data,{asOf:'2026-09-11',horizonDays:30}).rows[0],firm=firmPlannedSupply(data,row,{id:'F1'});releasePlannedSupply(data,firm.id,{releasedAt:'2026-09-12T08:00:00Z',releasedBy:'buyer',documentId:'PR1',documentNo:'PR-100'});assert.equal(firm.status,'RELEASED');assert.deepEqual({reference:firm.releasedReference,source:data.purchaseRequests[0].source,plannedOrderId:data.purchaseRequests[0].plannedOrderId,order:data.purchaseRequests[0].sourceOrders[0]},{reference:'PR-100',source:'TIME_PHASED_MRP',plannedOrderId:'F1',order:'ORD-1'})});

test('release converts MAKE plan to an internal production order',()=>{const data=state();data.products.push({code:'SF-P',name:'Semi Finished',outputSku:'SF1'});const firm=firmPlannedSupply(data,{plannedQuantity:8,action:'MAKE',sku:'SF1',warehouse:'WH-SF',releaseDate:'2026-09-20',needDate:'2026-09-25',orderNo:'ORD-1',productCode:'P1',priority:'URGENT'},{id:'M1'});releasePlannedSupply(data,firm.id,{releasedAt:'2026-09-12T08:00:00Z',releasedBy:'planner',documentId:'MO1',documentNo:'MO-100'});const order=data.orders[0];assert.deepEqual({product:order.productCode,qty:order.qty,parent:order.parentOrderNo,source:order.source,reference:firm.releasedReference},{product:'SF-P',qty:8,parent:'ORD-1',source:'TIME_PHASED_MRP',reference:'MO-100'})});
