import test from 'node:test';
import assert from 'node:assert/strict';
import {buildTimeBucketCheckpoints,earliestAffectedBucket,patchTimeBucketCheckpoints,verifyRowsAgainstCheckpoints,verifyTimeBucketCheckpoints} from '../../mrp/time-bucket-checkpoints.js';

test('weekly checkpoints form a deterministic verifiable chain',()=>{const rows=[{key:'B',orderNo:'O2',sku:'R2',needDate:'2026-09-19',plannedQuantity:3,projectedAvailable:0,status:'PLANNED'},{key:'A',orderNo:'O1',sku:'R1',needDate:'2026-09-12',plannedQuantity:2,projectedAvailable:1,status:'PLANNED'}],first=buildTimeBucketCheckpoints(rows,{asOf:'2026-09-11',cutoff:'2026-10-02',bucketDays:7}),second=buildTimeBucketCheckpoints([...rows].reverse(),{asOf:'2026-09-11',cutoff:'2026-10-02',bucketDays:7});assert.equal(first.headHash,second.headHash);assert.equal(first.checkpoints.length,4);assert.deepEqual(verifyTimeBucketCheckpoints(first),{valid:true,reason:'VALID'})});

test('checkpoint verification detects bucket mutation',()=>{const manifest=buildTimeBucketCheckpoints([{key:'A',needDate:'2026-09-12',plannedQuantity:2}],{asOf:'2026-09-11',cutoff:'2026-09-30'});manifest.checkpoints[0].plannedQuantity=999;assert.equal(verifyTimeBucketCheckpoints(manifest).valid,false)});

test('demand-only change restarts at its earliest due-date bucket',()=>{const manifest=buildTimeBucketCheckpoints([],{asOf:'2026-09-01',cutoff:'2026-09-30',bucketDays:7}),state={orders:[{orderNo:'O1',due:'2026-09-18'}]},result=earliestAffectedBucket(state,{changed:true,dirtyOrders:['O1'],dirtyItems:[],dirtyProducts:[],forecastChanged:false,contextChanged:false},manifest,{previousSnapshot:{demandMeta:{O1:{due:'2026-09-20'}}}});assert.equal(result.index,2);assert.equal(result.from,'2026-09-15')});

test('item effect safely restarts from the first bucket',()=>{const manifest=buildTimeBucketCheckpoints([],{asOf:'2026-09-01',cutoff:'2026-09-30'}),result=earliestAffectedBucket({}, {changed:true,dirtyOrders:[],dirtyItems:['R1'],dirtyProducts:[],forecastChanged:false,contextChanged:false},manifest);assert.equal(result.index,0);assert.equal(result.reason,'GLOBAL_OR_ITEM_EFFECT')});

test('Merkle patch rebuilds only touched buckets and equals a full build',()=>{const options={asOf:'2026-09-01',cutoff:'2026-09-30',bucketDays:7},before=[{key:'A',orderNo:'O1',needDate:'2026-09-03',plannedQuantity:2},{key:'B',orderNo:'O2',needDate:'2026-09-18',plannedQuantity:4}],after=[before[0],{...before[1],plannedQuantity:7}],baseline=buildTimeBucketCheckpoints(before,options),patched=patchTimeBucketCheckpoints(baseline,{previousRows:[before[1]],currentRows:[after[1]]},options),full=buildTimeBucketCheckpoints(after,options);assert.equal(patched.mode,'MERKLE_PATCH');assert.equal(patched.rebuiltBuckets,1);assert.equal(patched.reusedBuckets,4);assert.equal(patched.headHash,full.headHash);assert.equal(verifyTimeBucketCheckpoints(patched).valid,true)});

test('Merkle patch refuses an incompatible or broken baseline',()=>{const options={asOf:'2026-09-01',cutoff:'2026-09-30'},baseline=buildTimeBucketCheckpoints([],{...options,bucketDays:7});baseline.checkpoints[0].hash='BROKEN';assert.equal(patchTimeBucketCheckpoints(baseline,{}, {...options,bucketDays:7}),null);assert.equal(patchTimeBucketCheckpoints(buildTimeBucketCheckpoints([],options),{}, {...options,cutoff:'2026-10-01'}),null)});

test('compact storage uses tuples and streaming verification proves row parity',()=>{const rows=[{key:'A',orderNo:'O1',sku:'R1',needDate:'2026-09-03',plannedQuantity:2},{key:'B',orderNo:'O2',sku:'R2',needDate:'2026-09-18',plannedQuantity:4}],manifest=buildTimeBucketCheckpoints(rows,{asOf:'2026-09-01',cutoff:'2026-09-30'}),result=verifyRowsAgainstCheckpoints(rows,manifest);assert.equal(manifest.storage,'COMPACT_TUPLES');assert.ok(Array.isArray(manifest.checkpoints[0].records[0]));assert.equal(result.valid,true);assert.equal(result.rowsRead,2);assert.ok(result.peakBucketRows<rows.length)});

test('streaming verification detects changed rows without a second plan snapshot',()=>{const rows=[{key:'A',needDate:'2026-09-03',plannedQuantity:2}],manifest=buildTimeBucketCheckpoints(rows,{asOf:'2026-09-01',cutoff:'2026-09-30'}),result=verifyRowsAgainstCheckpoints([{...rows[0],plannedQuantity:3}],manifest);assert.equal(result.valid,false);assert.equal(result.reason,'ROW_BUCKET_MISMATCH')});

test('streaming verification covers decision-driving MRP fields',()=>{const row={key:'A',needDate:'2026-09-03',plannedQuantity:2,grossRequired:2,netRequired:2,action:'BUY',leadTimeDays:3},manifest=buildTimeBucketCheckpoints([row],{asOf:'2026-09-01',cutoff:'2026-09-30'});for(const [field,value] of [['grossRequired',3],['netRequired',3],['action','MAKE'],['leadTimeDays',4]])assert.equal(verifyRowsAgainstCheckpoints([{...row,[field]:value}],manifest).valid,false,field)});
