import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {buildWhatIfSimulation,createWhatIfSimulation,reviewWhatIfSimulation,decideWhatIfSimulation} from '../../mrp/what-if-simulation.js';

const sample=()=>({products:[{code:'FG-1',productionStrategy:'MTS',routingHours:1,salesPrice:20}],orders:[{productCode:'FG-1',qty:100,due:'2026-09-10',status:'OPEN'}],demandForecasts:[],stock:{'FG-1':{'WH-FG':0}},skus:[{code:'FG-1',standardCost:5}],capacityCalendar:{dailyHours:8,workDays:5,efficiencyPercent:100},whatIfSimulations:[],auditTrail:[]});

test('what-if applies demand capacity cost price scrap and supplier shocks',()=>{const result=buildWhatIfSimulation(sample(),{startPeriod:'2026-09',horizonMonths:1,demandPercent:20,capacityPercent:-50,supplierDelayDays:14,materialCostPercent:10,salesPricePercent:5,scrapPercent:5});const row=result.rows[0];assert.equal(row.scenarioDemand,120);assert.equal(row.supplyRisk,'MEDIUM');assert.equal(row.capacityStatus,'OVERLOADED');assert.equal(result.totals.scenarioRevenue,2520);assert.ok(result.totals.scenarioCost>result.totals.baselineCost)});
test('simulation does not mutate operational planning records',()=>{const state=sample(),before=JSON.stringify(state);buildWhatIfSimulation(state,{startPeriod:'2026-09',horizonMonths:1,demandPercent:30});assert.equal(JSON.stringify(state),before)});
test('saved simulation is an immutable result snapshot',()=>{const state=sample(),item=createWhatIfSimulation(state,{name:'Supply shock',analyst:'planner',rationale:'Evaluate delayed imported material',startPeriod:'2026-09',horizonMonths:1,supplierDelayDays:21});const revenue=item.totals.scenarioRevenue;state.products[0].salesPrice=100;assert.equal(item.totals.scenarioRevenue,revenue)});
test('review and decision require three independent identities',()=>{const state=sample(),item=createWhatIfSimulation(state,{name:'Demand shock',analyst:'planner',rationale:'Evaluate a major demand increase',startPeriod:'2026-09',horizonMonths:1});assert.throws(()=>reviewWhatIfSimulation(state,item.id,{reviewedBy:'planner',reviewNote:'Reviewed all scenario assumptions'}),/independent/i);reviewWhatIfSimulation(state,item.id,{reviewedBy:'controller',reviewNote:'Reviewed all scenario assumptions'});assert.throws(()=>decideWhatIfSimulation(state,item.id,{approvedBy:'controller',decision:'ACCEPTED',decisionNote:'Use this scenario for planning'}),/independent/i);decideWhatIfSimulation(state,item.id,{approvedBy:'manager',decision:'ACCEPTED',decisionNote:'Use this scenario for planning review'});assert.equal(item.status,'ACCEPTED')});
test('what-if interface identifiers are unique',()=>{const html=readFileSync(new URL('../../mrp/index.html',import.meta.url),'utf8');for(const id of ['whatIfName','whatIfStartPeriod','whatIfHorizon','whatIfDemand','whatIfCapacity','whatIfSupplierDelay','whatIfMaterialCost','whatIfSalesPrice','whatIfScrap','whatIfAnalyst','whatIfReviewer','whatIfApprover','whatIfRationale','whatIfReviewNote','whatIfDecisionNote','whatIfDecision','createWhatIfSimulation','whatIfKpis','whatIfTable','whatIfClaim','whatIfRegister'])assert.equal((html.match(new RegExp(`id="${id}"`,'g'))||[]).length,1)});
