import {normalizeFinancialState,accountingComplianceStatus} from './financial-core.js';
import {IFRS_ENGINE} from './ifrs-engine.js';
import {US_GAAP_ENGINE} from './us-gaap-engine.js';

const amount=value=>Math.round((Number(value)||0)*100)/100;
export const ACCOUNTING_ENGINES={IFRS_TFRS:IFRS_ENGINE,US_GAAP:US_GAAP_ENGINE};
export function accountingEngine(profile){if(profile==='MANAGEMENT_ONLY')return null;const engine=ACCOUNTING_ENGINES[profile];if(!engine)throw Error('A statutory accounting engine is not available for this profile.');return engine}
function balances(state,{from='',to='',cumulative=false}={}){const map=new Map((state.chartOfAccounts||[]).map(account=>[account.code,{code:account.code,name:account.name,type:account.type,debit:0,credit:0,amount:0}]));for(const entry of (state.journalEntries||[]).filter(item=>item.status==='POSTED'&&(!to||item.date<=to)&&(cumulative||!from||item.date>=from)))for(const line of entry.lines||[]){const row=map.get(line.accountCode);if(!row)continue;row.debit=amount(row.debit+Number(line.debit||0));row.credit=amount(row.credit+Number(line.credit||0));row.amount=amount(['LIABILITY','EQUITY','REVENUE'].includes(row.type)?row.credit-row.debit:row.debit-row.credit)}return[...map.values()]}
function balanceSheetRows(state,to=''){const rows=balances(state,{to,cumulative:true}),total=type=>amount(rows.filter(row=>row.type===type).reduce((sum,row)=>sum+row.amount,0)),assets=amount(total('ASSET')-total('CONTRA_ASSET')),liabilities=total('LIABILITY'),equity=total('EQUITY'),accumulatedResult=amount(total('REVENUE')-total('EXPENSE')),totalEquity=amount(equity+accumulatedResult);return[{statement:'Statement of financial position',line:'Assets',amount:assets,standard:'Presentation'},{statement:'Statement of financial position',line:'Liabilities',amount:liabilities,standard:'Presentation'},{statement:'Statement of financial position',line:'Contributed and retained equity',amount:equity,standard:'Presentation'},{statement:'Statement of financial position',line:'Accumulated result',amount:accumulatedResult,standard:'Presentation'},{statement:'Statement of financial position',line:'Total equity',amount:totalEquity,standard:'Presentation'},{statement:'Statement of financial position',line:'Balance check',amount:amount(assets-liabilities-totalEquity),standard:'Control'}]}
export function buildStatutoryReport(state,{from='',to=''}={}){normalizeFinancialState(state);const engine=accountingEngine(state.accountingSettings.profile);if(!engine)throw Error('Select IFRS/TFRS or US GAAP to run a statutory engine.');const validation=engine.validate(state),periodBalances=balances(state,{from,to});return{engine:engine.id,name:engine.name,presentation:engine.presentation,inventoryStandard:engine.inventoryStandard,rows:[...engine.incomeStatement(periodBalances,from),...balanceSheetRows(state,to)],issues:validation.issues,warnings:validation.warnings,readiness:validation.issues.length?'BLOCKED':validation.warnings.length?'REVIEW_REQUIRED':'READY'}}
export function buildAccountingControlReport(state,{from='',to=''}={}){const base=accountingComplianceStatus(state);if(base.profile==='MANAGEMENT_ONLY')return{...base,engine:'NONE',engineName:'Management reporting',engineIssues:[],engineWarnings:[{severity:'WARNING',code:'NON_STATUTORY',reference:'',message:'Select IFRS/TFRS or US GAAP for statutory-engine controls.'}]};const report=buildStatutoryReport(state,{from,to});return{...base,engine:report.engine,engineName:report.name,engineIssues:report.issues,engineWarnings:report.warnings,readiness:report.readiness}}
export function evaluateInventoryUnderActiveEngine(state,input={}){normalizeFinancialState(state);const engine=accountingEngine(state.accountingSettings.profile);if(!engine)throw Error('Management-only profile has no statutory inventory measurement engine.');return engine.inventoryMeasurement(input)}
export function proposeInventoryAdjustment(state,input={}){const result=evaluateInventoryUnderActiveEngine(state,input);if(!result.adjustment)return{...result,lines:[]};const value=Math.abs(result.adjustment),reversal=result.adjustment>0;return{...result,lines:reversal?[{accountCode:'1240',debit:value,credit:0},{accountCode:'5200',debit:0,credit:value}]:[{accountCode:'5200',debit:value,credit:0},{accountCode:'1240',debit:0,credit:value}],requiresApproval:true,reference:input.reference||`${input.sku||''}@${input.warehouse||''}`}}
