const clone=value=>JSON.parse(JSON.stringify(value));
const uid=()=>`ECO-${globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2)}`;
export const ECO_STATUSES=['DRAFT','SUBMITTED','TECHNICAL_REVIEW','APPROVED','REJECTED','RELEASED','CANCELLED'];
export function normalizeEngineeringChanges(state){state.engineeringChanges??=[];state.releasedProductRoutings??={};state.routingRevisionHistory??={};state.engineeringChanges.forEach(item=>{item.id||=uid();item.ecoNo||=`ECO-${String(state.engineeringChanges.indexOf(item)+1).padStart(4,'0')}`;item.type||='BOM';item.status=ECO_STATUSES.includes(item.status)?item.status:'DRAFT';item.history??=[];item.routingSnapshot??=[]});return state}
export function createEngineeringChange(state,input={},meta={}){normalizeEngineeringChanges(state);if(!input.productCode)throw Error('Product is required.');if(!['BOM','ROUTING','BOM_AND_ROUTING'].includes(input.type))throw Error('Select a valid change type.');const item={id:uid(),ecoNo:input.ecoNo||`ECO-${String(state.engineeringChanges.length+1).padStart(4,'0')}`,productCode:input.productCode,type:input.type,title:String(input.title||'').trim(),reason:String(input.reason||'').trim(),risk:String(input.risk||'').trim(),impact:String(input.impact||'').trim(),targetBomVersion:String(input.targetBomVersion||'').trim(),routingRevision:String(input.routingRevision||'').trim(),effectiveDate:input.effectiveDate||'',requestedBy:input.requestedBy||meta.user||'unknown',status:'DRAFT',routingSnapshot:clone((state.productRoutings||[]).filter(route=>route.productCode===input.productCode)),history:[]};item.history.push({action:'CREATED',by:item.requestedBy,at:meta.at||new Date().toISOString()});state.engineeringChanges.unshift(item);return item}
const record=(item,action,by,at)=>item.history.push({action,by,at:at||new Date().toISOString()});
export function submitEngineeringChange(state,id,meta={}){const item=find(state,id);if(item.status!=='DRAFT')throw Error('Only a draft ECO can be submitted.');if(!item.title||!item.reason||!item.effectiveDate)throw Error('Title, reason and effective date are required.');if(item.type.includes('BOM')&&!item.targetBomVersion)throw Error('Target BOM version is required.');if(item.type.includes('ROUTING')&&!item.routingRevision)throw Error('Routing revision is required.');item.status='SUBMITTED';item.submittedAt=meta.at||new Date().toISOString();record(item,'SUBMITTED',meta.user||item.requestedBy,item.submittedAt);return item}
export function reviewEngineeringChange(state,id,meta={}){const item=find(state,id);if(item.status!=='SUBMITTED')throw Error('ECO must be submitted before technical review.');if(!meta.user||meta.user===item.requestedBy)throw Error('Technical reviewer must be different from requester.');if(!item.impact||!item.risk)throw Error('Impact and risk assessment are required.');item.status='TECHNICAL_REVIEW';item.reviewedBy=meta.user;item.reviewedAt=meta.at||new Date().toISOString();record(item,'TECHNICALLY_REVIEWED',meta.user,item.reviewedAt);return item}
export function approveEngineeringChange(state,id,meta={}){const item=find(state,id);if(item.status!=='TECHNICAL_REVIEW')throw Error('Technical review is required before approval.');if(!meta.user||[item.requestedBy,item.reviewedBy].includes(meta.user))throw Error('Approver must be independent from requester and reviewer.');item.status='APPROVED';item.approvedBy=meta.user;item.approvedAt=meta.at||new Date().toISOString();record(item,'APPROVED',meta.user,item.approvedAt);return item}
export function releaseEngineeringChange(state,id,meta={}){const item=find(state,id),date=String(meta.at||new Date().toISOString()).slice(0,10);if(item.status!=='APPROVED')throw Error('Only an approved ECO can be released.');if(item.effectiveDate>date)throw Error(`ECO is scheduled for ${item.effectiveDate}.`);if(item.type.includes('BOM')){const revision=(state.bomHistory?.[item.productCode]||[]).find(value=>value.version===item.targetBomVersion);if(!revision)throw Error(`BOM version ${item.targetBomVersion} was not found.`);state.bomProfiles[item.productCode]={...state.bomProfiles[item.productCode],version:revision.version,effectiveDate:revision.effectiveDate};state.boms[item.productCode]=clone(revision.materials||[]).map(line=>({...line,qty:Number(line.qty||line.usageQty)||0}))}if(item.type.includes('ROUTING')){state.releasedProductRoutings[item.productCode]=clone(item.routingSnapshot);state.routingRevisionHistory[item.productCode]??=[];state.routingRevisionHistory[item.productCode].unshift({revision:item.routingRevision,effectiveDate:item.effectiveDate,ecoNo:item.ecoNo,routes:clone(item.routingSnapshot),releasedAt:meta.at||new Date().toISOString(),releasedBy:meta.user||'unknown'})}item.status='RELEASED';item.releasedBy=meta.user||'unknown';item.releasedAt=meta.at||new Date().toISOString();record(item,'RELEASED',item.releasedBy,item.releasedAt);return item}
function find(state,id){normalizeEngineeringChanges(state);const item=state.engineeringChanges.find(value=>value.id===id);if(!item)throw Error('Engineering change was not found.');return item}
