const te=new TextEncoder(),td=new TextDecoder();
const xmlEscape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const xmlText=n=>String(n??'').replace(/<[^>]+>/g,'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&');

function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function u16(a,o,v){a[o]=v&255;a[o+1]=(v>>>8)&255}function u32(a,o,v){u16(a,o,v);u16(a,o+2,v>>>16)}
function colName(i){let s='';for(i++;i;i=Math.floor((i-1)/26))s=String.fromCharCode(65+(i-1)%26)+s;return s}

function sheetXml(rows){const body=rows.map((row,r)=>`<row r="${r+1}">`+row.map((v,c)=>{
  const ref=colName(c)+(r+1);if(typeof v==='number'&&Number.isFinite(v))return `<c r="${ref}"><v>${v}</v></c>`;
  return `<c r="${ref}" t="inlineStr"><is><t>${xmlEscape(v)}</t></is></c>`
}).join('')+'</row>').join('');return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${body}</sheetData></worksheet>`}

function zipStore(files){const locals=[],centrals=[];let offset=0;for(const [name,data] of files){const nb=te.encode(name),db=typeof data==='string'?te.encode(data):data,crc=crc32(db),local=new Uint8Array(30+nb.length+db.length);u32(local,0,0x04034b50);u16(local,4,20);u16(local,6,0x800);u16(local,8,0);u32(local,14,crc);u32(local,18,db.length);u32(local,22,db.length);u16(local,26,nb.length);local.set(nb,30);local.set(db,30+nb.length);locals.push(local);const cen=new Uint8Array(46+nb.length);u32(cen,0,0x02014b50);u16(cen,4,20);u16(cen,6,20);u16(cen,8,0x800);u16(cen,10,0);u32(cen,16,crc);u32(cen,20,db.length);u32(cen,24,db.length);u16(cen,28,nb.length);u32(cen,42,offset);cen.set(nb,46);centrals.push(cen);offset+=local.length}const csize=centrals.reduce((s,x)=>s+x.length,0),end=new Uint8Array(22);u32(end,0,0x06054b50);u16(end,8,files.length);u16(end,10,files.length);u32(end,12,csize);u32(end,16,offset);return new Blob([...locals,...centrals,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}

export function downloadWorkbook(filename,sheetName,headers,sampleRows=[]){const files=[
 ['[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'],
 ['_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],
 ['xl/workbook.xml',`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${xmlEscape(sheetName)}" sheetId="1" r:id="rId1"/></sheets></workbook>`],
 ['xl/_rels/workbook.xml.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'],
 ['xl/worksheets/sheet1.xml',sheetXml([headers,...sampleRows])]
];const a=document.createElement('a');a.href=URL.createObjectURL(zipStore(files));a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

async function unzip(bytes){const dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let eocd=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(dv.getUint32(i,true)===0x06054b50){eocd=i;break}if(eocd<0)throw Error('Invalid XLSX file');const count=dv.getUint16(eocd+10,true),central=dv.getUint32(eocd+16,true),out={};let p=central;for(let i=0;i<count;i++){if(dv.getUint32(p,true)!==0x02014b50)throw Error('Invalid XLSX directory');const method=dv.getUint16(p+10,true),size=dv.getUint32(p+20,true),nameLen=dv.getUint16(p+28,true),extra=dv.getUint16(p+30,true),comment=dv.getUint16(p+32,true),local=dv.getUint32(p+42,true),name=td.decode(bytes.slice(p+46,p+46+nameLen)),ln=dv.getUint16(local+26,true),le=dv.getUint16(local+28,true),start=local+30+ln+le,compressed=bytes.slice(start,start+size);let data;if(method===0)data=compressed;else if(method===8){const stream=new Blob([compressed]).stream().pipeThrough(new DecompressionStream('deflate-raw'));data=new Uint8Array(await new Response(stream).arrayBuffer())}else throw Error('Unsupported XLSX compression');out[name]=data;p+=46+nameLen+extra+comment}return out}
function parseSheet(xml,shared){const rows=[];for(const rm of xml.matchAll(/<row\b[^>]*>([\s\S]*?)<\/row>/g)){const row=[];for(const cm of rm[1].matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>/g)){const attr=cm[1],body=cm[2],ref=(attr.match(/\br="([A-Z]+)\d+"/)||[])[1]||'A';let col=0;for(const ch of ref)col=col*26+ch.charCodeAt(0)-64;col--;const type=(attr.match(/\bt="([^"]+)"/)||[])[1],v=(body.match(/<v[^>]*>([\s\S]*?)<\/v>/)||[])[1],inline=(body.match(/<t[^>]*>([\s\S]*?)<\/t>/)||[])[1];let value='';if(type==='s')value=shared[Number(v)]??'';else if(type==='inlineStr'||type==='str')value=xmlText(inline??v??'');else if(v!=null)value=Number.isFinite(Number(v))?Number(v):xmlText(v);row[col]=value}rows.push(row)}return rows}
export async function readWorkbookFile(file){const bytes=new Uint8Array(await file.arrayBuffer()),files=await unzip(bytes),sharedXml=files['xl/sharedStrings.xml']?td.decode(files['xl/sharedStrings.xml']):'',shared=[...sharedXml.matchAll(/<si>([\s\S]*?)<\/si>/g)].map(m=>[...m[1].matchAll(/<t[^>]*>([\s\S]*?)<\/t>/g)].map(x=>xmlText(x[1])).join(''));const sheetName=Object.keys(files).find(x=>/^xl\/worksheets\/sheet\d+\.xml$/.test(x));if(!sheetName)throw Error('No worksheet found');const rows=parseSheet(td.decode(files[sheetName]),shared);const headers=(rows.shift()||[]).map(x=>String(x??'').trim());return rows.filter(r=>r.some(v=>v!==''&&v!=null)).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])))}
