import {appendAudit} from './audit-workflow.js';
import {assertWorkOrderUnlocked} from './production-close-control.js';

const uid=prefix=>`${prefix}-${globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2)}`;
const amount=value=>{const result=Number(value);return Number.isFinite(result)?Math.round(result*100)/100:0};
const metaFields=(meta={})=>({user:meta.user||'unknown',role:meta.role||'',workspace:meta.workspace||'',device:meta.device||'unknown'});

export const ACCOUNTING_PROFILES=['IFRS_TFRS','US_GAAP','MANAGEMENT_ONLY'];
export const ACCOUNTING_PROFILE_POLICIES={
  IFRS_TFRS:{label:'IFRS / TFRS',statutory:true,basis:'Accrual · double-entry',inventoryMeasurement:'Lower of cost and NRV',allowedCostMethods:['FIFO','WEIGHTED_AVERAGE','STANDARD'],lifo:false,developmentCosts:'Capitalize only when recognition criteria are met',assetRevaluation:true},
  US_GAAP:{label:'US GAAP',statutory:true,basis:'Accrual · double-entry',inventoryMeasurement:'Lower of cost and NRV / market, as applicable',allowedCostMethods:['FIFO','WEIGHTED_AVERAGE','STANDARD','LIFO'],lifo:true,developmentCosts:'Expense unless specific guidance permits capitalization',assetRevaluation:false},
  MANAGEMENT_ONLY:{label:'Management only',statutory:false,basis:'Internal accrual · double-entry',inventoryMeasurement:'Management valuation; no statutory compliance claim',allowedCostMethods:['FIFO','WEIGHTED_AVERAGE','STANDARD'],lifo:false,developmentCosts:'Management policy',assetRevaluation:false}
};
export const DEFAULT_CHART_OF_ACCOUNTS=[
  ['1000','Cash and cash equivalents','ASSET'],['1100','Trade receivables','ASSET'],['1200','Raw material inventory','ASSET'],['1210','Packaging inventory','ASSET'],['1220','Work in process inventory','ASSET'],['1230','Finished goods inventory','ASSET'],['1240','Inventory impairment allowance','CONTRA_ASSET'],
  ['2000','Trade payables','LIABILITY'],['2100','Accrued expenses','LIABILITY'],['2200','Tax payable','LIABILITY'],
  ['3000','Share capital and retained earnings','EQUITY'],
  ['4000','Sales revenue','REVENUE'],['4100','Other operating income','REVENUE'],
  ['5000','Cost of goods sold','EXPENSE'],['5100','Material usage variance','EXPENSE'],['5110','Purchase price variance','EXPENSE'],['5120','Labor variance','EXPENSE'],['5130','Production overhead variance','EXPENSE'],['5140','Scrap and rework loss','EXPENSE'],['5150','Production downtime loss','EXPENSE'],['5200','Inventory impairment loss','EXPENSE'],['6000','Operating expenses','EXPENSE'],['7000','Finance costs','EXPENSE'],['7100','Foreign exchange gain or loss','EXPENSE'],['8000','Income tax expense','EXPENSE']
].map(([code,name,type])=>({id:`ACC-${code}`,code,name,type,active:true,system:true}));

export function normalizeFinancialState(state){
  state.accountingSettings??={};state.accountingSettings.profile=ACCOUNTING_PROFILES.includes(state.accountingSettings.profile)?state.accountingSettings.profile:'IFRS_TFRS';state.accountingSettings.baseCurrency||=state.settings?.currency||'TRY';state.accountingSettings.fiscalYearStart||='01-01';
  state.chartOfAccounts??=[];for(const account of DEFAULT_CHART_OF_ACCOUNTS)if(!state.chartOfAccounts.some(item=>item.code===account.code))state.chartOfAccounts.push({...account});
  state.accountingPeriods??=[];state.journalEntries??=[];state.journalEntries.forEach(entry=>{entry.lines??=[];entry.status||='DRAFT';entry.currency||=state.accountingSettings.baseCurrency;entry.exchangeRate=Number(entry.exchangeRate)||1});return state;
}

export function accountingProfilePolicy(profile){return ACCOUNTING_PROFILE_POLICIES[ACCOUNTING_PROFILES.includes(profile)?profile:'IFRS_TFRS']}

export function setAccountingProfile(state,profile,meta={}){normalizeFinancialState(state);if(!ACCOUNTING_PROFILES.includes(profile))throw Error('Unsupported accounting profile.');const previous=state.accountingSettings.profile;if(previous===profile)return state.accountingSettings;if(state.journalEntries.some(entry=>entry.status==='POSTED'))throw Error('Accounting profile is locked after the first posted journal. Reverse or migrate records in a controlled process.');const policy=accountingProfilePolicy(profile),invalid=(state.skus||[]).filter(item=>!policy.allowedCostMethods.includes(item.costMethod||'STANDARD'));if(invalid.length)throw Error(`${invalid.length} SKU(s) use a cost method prohibited by ${policy.label}.`);state.accountingSettings.profile=profile;state.accountingSettings.profileSelectedAt=meta.at||new Date().toISOString();state.accountingSettings.profileSelectedBy=metaFields(meta);appendAudit(state,{...metaFields(meta),action:'ACCOUNTING_PROFILE_CHANGED',entity:'FINANCE',reference:profile,at:state.accountingSettings.profileSelectedAt,details:`${previous} → ${profile}`});return state.accountingSettings}

export function accountingComplianceStatus(state){normalizeFinancialState(state);const policy=accountingProfilePolicy(state.accountingSettings.profile),issues=[],warnings=[];if(!/^[A-Z]{3}$/.test(state.accountingSettings.baseCurrency||''))issues.push('Base currency must be a three-letter ISO code.');if(!/^\d{2}-\d{2}$/.test(state.accountingSettings.fiscalYearStart||''))issues.push('Fiscal year start must use MM-DD.');if(!state.accountingPeriods.length)warnings.push('No accounting period has been configured.');if(!state.journalEntries.some(entry=>entry.status==='POSTED'))warnings.push('No journal has been posted yet.');const invalid=(state.skus||[]).filter(item=>!policy.allowedCostMethods.includes(item.costMethod||'STANDARD'));if(invalid.length)issues.push(`${invalid.length} SKU(s) have a prohibited inventory cost method.`);for(const entry of state.journalEntries.filter(item=>item.status==='POSTED')){const debit=amount((entry.lines||[]).reduce((sum,line)=>sum+amount(line.debit),0)),credit=amount((entry.lines||[]).reduce((sum,line)=>sum+amount(line.credit),0));if(debit!==credit)issues.push(`Journal ${entry.entryNo||entry.id} is not balanced.`)}const readiness=issues.length?'BLOCKED':warnings.length?'CONFIGURATION_REQUIRED':'OPERATIONAL';return{profile:state.accountingSettings.profile,label:policy.label,policy,readiness,issues,warnings,postedJournals:state.journalEntries.filter(item=>item.status==='POSTED').length,profileLocked:state.journalEntries.some(item=>item.status==='POSTED'),complianceClaim:policy.statutory?'Controls enabled; formal compliance requires entity configuration and professional review.':'Internal management reporting only; not a statutory accounting framework.'}}

function account(state,code){const result=state.chartOfAccounts.find(item=>item.code===code&&item.active!==false);if(!result)throw Error(`Active account ${code} was not found.`);return result}
function periodFor(state,date){return state.accountingPeriods.find(item=>date>=item.startDate&&date<=item.endDate)}
function assertOpenPeriod(state,date){const period=periodFor(state,date);if(!period)throw Error(`No accounting period covers ${date}.`);if(period.status!=='OPEN')throw Error(`Accounting period ${period.code} is ${period.status}.`);return period}

export function createAccountingPeriod(state,input={},meta={}){normalizeFinancialState(state);const startDate=input.startDate,endDate=input.endDate;if(!startDate||!endDate||endDate<startDate)throw Error('A valid accounting period date range is required.');if(state.accountingPeriods.some(item=>startDate<=item.endDate&&endDate>=item.startDate))throw Error('Accounting periods cannot overlap.');const period={id:input.id||uid('PER'),code:input.code||startDate.slice(0,7),startDate,endDate,status:'OPEN',closedAt:'',closedBy:null};state.accountingPeriods.push(period);state.accountingPeriods.sort((a,b)=>a.startDate.localeCompare(b.startDate));appendAudit(state,{...metaFields(meta),action:'ACCOUNTING_PERIOD_CREATED',entity:'FINANCE',reference:period.code,details:`${startDate} to ${endDate}`});return period}

export function closeAccountingPeriod(state,periodId,meta={}){normalizeFinancialState(state);const period=state.accountingPeriods.find(item=>item.id===periodId);if(!period)throw Error('Accounting period was not found.');if(!['ACCOUNTING','CEO'].includes(String(meta.role||'').toUpperCase()))throw Error('Accounting or CEO role is required to close a period.');if(period.status!=='OPEN')throw Error('Only an open accounting period can be closed.');if(state.journalEntries.some(entry=>entry.status==='DRAFT'&&entry.date>=period.startDate&&entry.date<=period.endDate))throw Error('Post or cancel all draft journals before closing the period.');period.status='CLOSED';period.closedAt=meta.at||new Date().toISOString();period.closedBy=metaFields(meta);appendAudit(state,{...metaFields(meta),action:'ACCOUNTING_PERIOD_CLOSED',entity:'FINANCE',reference:period.code,at:period.closedAt});return period}

export function postJournalEntry(state,input={},meta={}){normalizeFinancialState(state);const date=input.date||new Date().toISOString().slice(0,10),period=assertOpenPeriod(state,date),lines=(input.lines||[]).map(line=>({accountCode:String(line.accountCode||''),description:line.description||'',debit:amount(line.debit),credit:amount(line.credit),dimension:line.dimension||'',reference:line.reference||input.reference||''}));if(lines.length<2)throw Error('A journal entry requires at least two lines.');for(const workOrderNo of new Set(lines.filter(line=>line.accountCode==='1220'&&line.dimension).map(line=>line.dimension)))assertWorkOrderUnlocked(state,{workOrderNo});for(const line of lines){account(state,line.accountCode);if(line.debit<0||line.credit<0||line.debit&&line.credit||!line.debit&&!line.credit)throw Error('Each journal line must contain one positive debit or credit amount.')}const debit=amount(lines.reduce((sum,line)=>sum+line.debit,0)),credit=amount(lines.reduce((sum,line)=>sum+line.credit,0));if(debit!==credit)throw Error(`Journal entry is not balanced: debit ${debit}, credit ${credit}.`);const entry={id:input.id||uid('JE'),entryNo:input.entryNo||`JE-${String(state.journalEntries.length+1).padStart(6,'0')}`,date,periodId:period.id,description:input.description||'',source:input.source||'MANUAL',sourceId:input.sourceId||'',reference:input.reference||'',currency:input.currency||state.accountingSettings.baseCurrency,exchangeRate:Number(input.exchangeRate)||1,lines,status:'POSTED',totalDebit:debit,totalCredit:credit,postedAt:meta.at||new Date().toISOString(),postedBy:metaFields(meta),reversalOf:''};if(state.journalEntries.some(item=>item.entryNo===entry.entryNo))throw Error('Journal entry number already exists.');state.journalEntries.unshift(entry);appendAudit(state,{...metaFields(meta),action:'JOURNAL_POSTED',entity:'FINANCE',reference:entry.entryNo,at:entry.postedAt,details:`${entry.source} · ${debit} ${entry.currency}`});return entry}

export function reverseJournalEntry(state,entryId,{date=new Date().toISOString().slice(0,10),reason='Correction',meta={}}={}){normalizeFinancialState(state);const original=state.journalEntries.find(item=>item.id===entryId&&item.status==='POSTED');if(!original)throw Error('Posted journal entry was not found.');if(original.reversedBy)throw Error('Journal entry has already been reversed.');const reversal=postJournalEntry(state,{date,description:`Reversal: ${original.description}`,source:'REVERSAL',sourceId:original.id,reference:reason,currency:original.currency,exchangeRate:original.exchangeRate,lines:original.lines.map(line=>({...line,debit:line.credit,credit:line.debit}))},meta);reversal.reversalOf=original.id;original.reversedBy=reversal.id;appendAudit(state,{...metaFields(meta),action:'JOURNAL_REVERSED',entity:'FINANCE',reference:original.entryNo,details:reason});return reversal}

export function trialBalance(state,{from='',to=''}={}){normalizeFinancialState(state);const balances=new Map(state.chartOfAccounts.map(item=>[item.code,{accountCode:item.code,accountName:item.name,type:item.type,debit:0,credit:0,balance:0}]));for(const entry of state.journalEntries.filter(item=>item.status==='POSTED'&&(!from||item.date>=from)&&(!to||item.date<=to)))for(const line of entry.lines){const row=balances.get(line.accountCode);row.debit=amount(row.debit+line.debit);row.credit=amount(row.credit+line.credit);row.balance=amount(row.debit-row.credit)}return[...balances.values()].filter(item=>item.debit||item.credit)}
