import {appendAudit} from './audit-workflow.js';

const text=value=>String(value??'').trim();
const num=value=>Number.isFinite(Number(value))?Number(value):0;
const METRICS=[
  ['HC-01','Availability %','MIN',99],
  ['HC-02','Transaction success %','MIN',99],
  ['HC-03','Inventory reconciliation variance %','MAX',0.5],
  ['HC-04','MRP critical exceptions','MAX',0],
  ['HC-05','Open critical/high incidents','MAX',0],
  ['HC-06','Backup and restore verification','MIN',1]
];
const metric=([code,name,direction,target])=>({code,name,direction,target,actual:null,status:'PENDING',evidence:'',measuredBy:'',measuredAt:''});
export function normalizeHypercare(state){state.hypercareCycles??=[];for(const item of state.hypercareCycles){item.metrics??=METRICS.map(metric);item.incidents??=[];item.history??=[];item.status??='ACTIVE'}return state}
function latestLive(state){return(state.goLivePlans||[]).find(item=>item.status==='LIVE')}
function find(state,id){normalizeHypercare(state);const item=state.hypercareCycles.find(row=>row.id===id);if(!item)throw Error('Hypercare cycle was not found.');return item}
export function hypercareSummary(cycle){const metrics=cycle?.metrics||[],incidents=cycle?.incidents||[],passed=metrics.filter(item=>item.status==='PASS').length,failed=metrics.filter(item=>item.status==='FAIL').length,pending=metrics.filter(item=>item.status==='PENDING').length,open=incidents.filter(item=>item.status!=='CLOSED'),blocking=open.filter(item=>['CRITICAL','HIGH'].includes(item.severity));return{passed,failed,pending,openIncidents:open.length,blockingIncidents:blocking.length,ready:metrics.length===METRICS.length&&!failed&&!pending&&!blocking.length}}
export function createHypercareCycle(state,{site,owner,startAt,endAt}={},meta={}){normalizeHypercare(state);const goLive=latestLive(state),factory=text(site),lead=text(owner||meta.user),start=Date.parse(startAt),end=Date.parse(endAt);if(!goLive)throw Error('An activated LIVE go-live plan is required before hypercare.');if(!factory||!lead||!Number.isFinite(start)||!Number.isFinite(end)||end<=start)throw Error('Site, owner and a valid hypercare window are required.');const at=meta.at||new Date().toISOString(),item={id:`HC-${Date.now()}-${state.hypercareCycles.length+1}`,cycleNo:`HC-${String(state.hypercareCycles.length+1).padStart(5,'0')}`,goLivePlanNo:goLive.planNo,releaseVersion:goLive.releaseVersion,site:factory,owner:lead,startAt:new Date(start).toISOString(),endAt:new Date(end).toISOString(),status:'ACTIVE',metrics:METRICS.map(metric),incidents:[],history:[{action:'STARTED',at,user:lead}]};state.hypercareCycles.unshift(item);appendAudit(state,{...meta,user:lead,action:'HYPERCARE_STARTED',entity:'HYPERCARE',reference:item.cycleNo,details:`${item.releaseVersion} · ${factory}`});return item}
export function recordHypercareMetric(state,id,code,{actual,evidence,measuredBy,at=new Date().toISOString()}={}){const item=find(state,id),row=item.metrics.find(entry=>entry.code===code),value=Number(actual),proof=text(evidence),user=text(measuredBy);if(item.status!=='ACTIVE'||!row)throw Error('Active hypercare metric was not found.');if(!Number.isFinite(value)||proof.length<10||!user)throw Error('Numeric result, measurer and evidence of at least 10 characters are required.');const pass=row.direction==='MIN'?value>=row.target:value<=row.target;Object.assign(row,{actual:value,status:pass?'PASS':'FAIL',evidence:proof,measuredBy:user,measuredAt:at});appendAudit(state,{action:`HYPERCARE_METRIC_${row.status}`,entity:'HYPERCARE',reference:`${item.cycleNo}/${code}`,user,at,details:`${value} · ${proof}`});return row}
export function openHypercareIncident(state,id,{severity,title,owner,responseTargetMinutes}={},meta={}){const item=find(state,id),level=text(severity).toUpperCase(),name=text(title),assigned=text(owner),target=num(responseTargetMinutes);if(item.status!=='ACTIVE')throw Error('Incidents can only be opened during active hypercare.');if(!['LOW','MEDIUM','HIGH','CRITICAL'].includes(level)||name.length<5||!assigned||target<=0)throw Error('Severity, title, owner and positive response target are required.');const at=meta.at||new Date().toISOString(),incident={id:`INC-${Date.now()}-${item.incidents.length+1}`,incidentNo:`${item.cycleNo}-I${String(item.incidents.length+1).padStart(3,'0')}`,severity:level,title:name,owner:assigned,responseTargetMinutes:target,status:'OPEN',openedAt:at,respondBy:new Date(Date.parse(at)+target*60000).toISOString()};item.incidents.unshift(incident);appendAudit(state,{...meta,action:'HYPERCARE_INCIDENT_OPENED',entity:'HYPERCARE',reference:incident.incidentNo,details:`${level} · ${name}`});return incident}
export function closeHypercareIncident(state,id,incidentId,{closedBy,resolution,at=new Date().toISOString()}={}){const item=find(state,id),incident=item.incidents.find(row=>row.id===incidentId),user=text(closedBy),note=text(resolution);if(item.status!=='ACTIVE'||!incident||incident.status==='CLOSED')throw Error('Open hypercare incident was not found.');if(!user||note.length<10)throw Error('Incident closer and resolution evidence of at least 10 characters are required.');Object.assign(incident,{status:'CLOSED',closedBy:user,resolution:note,closedAt:at,responseMet:Date.parse(at)<=Date.parse(incident.respondBy)});appendAudit(state,{action:'HYPERCARE_INCIDENT_CLOSED',entity:'HYPERCARE',reference:incident.incidentNo,user,at,details:note});return incident}
export function submitHypercareExit(state,id,{submittedBy,exitNote,at=new Date().toISOString()}={}){const item=find(state,id),summary=hypercareSummary(item),user=text(submittedBy),note=text(exitNote);if(item.status!=='ACTIVE')throw Error('Only active hypercare can be submitted for exit.');if(!summary.ready)throw Error(`Hypercare exit is blocked: ${summary.failed} failed, ${summary.pending} pending, ${summary.blockingIncidents} blocking incident(s).`);if(!user||note.length<10)throw Error('Submitter and exit note of at least 10 characters are required.');Object.assign(item,{status:'EXIT_REVIEW',submittedBy:user,exitNote:note,submittedAt:at});appendAudit(state,{action:'HYPERCARE_EXIT_SUBMITTED',entity:'HYPERCARE',reference:item.cycleNo,user,at,details:note});return item}
export function approveHypercareExit(state,id,{approvedBy,stabilizationNote,at=new Date().toISOString()}={}){const item=find(state,id),user=text(approvedBy),note=text(stabilizationNote);if(item.status!=='EXIT_REVIEW')throw Error('Hypercare exit review is required.');if(!user||note.length<10)throw Error('Independent approver and stabilization note are required.');if([item.owner,item.submittedBy].some(value=>value.toLowerCase()===user.toLowerCase()))throw Error('Hypercare exit approver must be independent from owner and submitter.');Object.assign(item,{status:'STABILIZED',approvedBy:user,stabilizationNote:note,approvedAt:at});appendAudit(state,{action:'PRODUCTION_STABILIZED',entity:'HYPERCARE',reference:item.cycleNo,user,at,details:note});return item}
export {METRICS};
