export const PERSIAN_I18N={
  saved:'ذخیره شد',saving:'در حال ذخیره…',backup:'پشتیبان‌گیری',fullBackup:'پشتیبان کامل',restoreBackup:'بازیابی پشتیبان',operations:'عملیات',dashboard:'داشبورد',products:'محصولات',itemsSku:'اقلام و SKU',warehouseStock:'موجودی انبار',goodsReceipt:'رسید کالا',stockEditHint:'این جدول فقط برای موجودی اولیه یا اصلاحات مجاز استفاده شود.',description:'شرح',warehouse:'انبار',quantity:'مقدار',receiptDate:'تاریخ رسید',referenceNo:'شماره مرجع / سند',supplier:'تأمین‌کننده',notes:'یادداشت‌ها',postReceipt:'ارسال برای کنترل کیفیت',receiptHistory:'سوابق رسید',productBom:'BOM محصول',orders:'سفارش‌ها',requirements:'نیازمندی‌ها',reportsAnalytics:'گزارش‌ها و تحلیل‌ها',universalImport:'ورود اطلاعات عمومی',processControl:'کنترل فرایند',productionExecution:'اجرای تولید',documentsLabelsScan:'اسناد، لیبل و اسکن',procurementSuppliers:'تدارکات و تأمین‌کنندگان',qualityNcr:'کیفیت و NCR',salesOrders:'سفارش‌های فروش',financeShipping:'مالی و ارسال',exchange:'بورس Hamvara',settings:'تنظیمات',operationsDashboard:'داشبورد عملیات',actionRequired:'اقدام لازم',newProduct:'+ محصول جدید',itemMaster:'اطلاعات پایه اقلام و SKU',newSku:'+ SKU جدید',warehouseInventory:'موجودی انبار',addItem:'+ افزودن قلم',saveBom:'ذخیره BOM',productionOrders:'سفارش‌های تولید و مشتری',newOrderLine:'+ ردیف سفارش جدید',sameOrderHint:'برای چند محصول از یک شماره سفارش یکسان استفاده کنید.',materialRequirements:'نیازمندی‌ها و کسری مواد',exportCsv:'خروجی CSV',exchangeTitle:'بورس موجودی مازاد',exchangeHint:'موجودی راکد و مازاد کارخانه را به نقدینگی تبدیل کنید.',searchListing:'جست‌وجوی SKU، کالا یا محل',suggestExcess:'شناسایی موجودی مازاد',newListing:'+ آگهی جدید',systemSettings:'تنظیمات سیستم',language:'زبان',companyName:'نام شرکت',currency:'واحد پول',appVersion:'نسخه برنامه',publisher:'ناشر',dataSchema:'نسخه ساختار داده',dataLocation:'داده‌های عملیاتی در پوشه Data کنار فایل EXE نگهداری می‌شوند.',saveSettings:'ذخیره تنظیمات',searchCodeName:'جست‌وجوی کد یا نام',searchSku:'جست‌وجوی SKU',downloadTemplate:'دانلود قالب',importExcel:'ورود از Excel',warehouses:'انبارها'
};

const TEXTS={
  'Reports & Analytics':['Raporlar ve Analizler','گزارش‌ها و تحلیل‌ها'],'Universal Import':['Evrensel İçe Aktarma','ورود اطلاعات عمومی'],'PROCESS CONTROL':['SÜREÇ KONTROLÜ','کنترل فرایند'],'Production Execution':['Üretim Yürütme','اجرای تولید'],'Documents, Labels & Scan':['Belgeler, Etiketler ve Tarama','اسناد، لیبل و اسکن'],'Procurement & Suppliers':['Satın Alma ve Tedarikçiler','تدارکات و تأمین‌کنندگان'],'Quality & NCR':['Kalite ve Uygunsuzluk','کیفیت و NCR'],'Sales Orders':['Satış Siparişleri','سفارش‌های فروش'],'Finance & Shipping':['Finans ve Sevkiyat','مالی و ارسال'],
  'Business Management Overview':['İşletme Yönetimi Özeti','نمای کلی مدیریت کسب‌وکار'],'Inventory Movement & Traceability':['Stok Hareketi ve İzlenebilirlik','گردش موجودی و ردیابی'],'Production Performance & KPI':['Üretim Performansı ve KPI','عملکرد تولید و KPI'],'Procurement, Supplier & Cost':['Satın Alma, Tedarikçi ve Maliyet','خرید، تأمین‌کننده و هزینه'],'Goods Receipt & Posting':['Mal Kabul ve Kayıt','رسید و ثبت کالا'],'Audit Trail & Last Changes':['Denetim İzi ve Son Değişiklikler','سوابق ممیزی و آخرین تغییرات'],
  'Management reporting across inventory, traceability, production, quality, procurement, sales, finance and audit':['Stok, izlenebilirlik, üretim, kalite, satın alma, satış, finans ve denetim yönetim raporları','گزارش مدیریتی موجودی، ردیابی، تولید، کیفیت، خرید، فروش، مالی و ممیزی'],'Refresh':['Yenile','به‌روزرسانی'],'Print / Save PDF':['Yazdır / PDF Kaydet','چاپ / ذخیره PDF'],'Report':['Rapor','گزارش'],'Business Overview':['İşletme Özeti','نمای کلی کسب‌وکار'],'Inventory by Warehouse':['Depoya Göre Stok','موجودی بر اساس انبار'],'Movement & Traceability':['Hareket ve İzlenebilirlik','گردش و ردیابی'],'Production & KPI':['Üretim ve KPI','تولید و KPI'],'Procurement & Cost':['Satın Alma ve Maliyet','خرید و هزینه'],'Sales, Invoice & Shipping':['Satış, Fatura ve Sevkiyat','فروش، فاکتور و ارسال'],'Goods Receipts':['Mal Kabulleri','رسیدهای کالا'],'Audit & Last Changes':['Denetim ve Son Değişiklikler','ممیزی و آخرین تغییرات'],'From':['Başlangıç','از تاریخ'],'To':['Bitiş','تا تاریخ'],'All Warehouses':['Tüm Depolar','همه انبارها'],'Search SKU, reference, batch, user or document':['SKU, referans, parti, kullanıcı veya belge ara','جست‌وجوی SKU، مرجع، بچ، کاربر یا سند'],'Business Management Overview':['İşletme Yönetimi Özeti','نمای کلی مدیریت کسب‌وکار'],
  'Universal Import Center':['Evrensel İçe Aktarma Merkezi','مرکز ورود اطلاعات عمومی'],'Normalize exports from ERP, CRM, accounting and spreadsheet systems before posting to Hamvara':['ERP, CRM, muhasebe ve elektronik tablo çıktılarını Hamvara’ya aktarmadan önce standartlaştırın','خروجی ERP، CRM، حسابداری و فایل‌های جدولی را پیش از ثبت در Hamvara استاندارد کنید'],'Download Import Contract':['İçe Aktarma Şartnamesini İndir','دانلود استاندارد ورود اطلاعات'],'Data type':['Veri türü','نوع داده'],'Auto detect':['Otomatik algıla','تشخیص خودکار'],'Excel / CSV / TSV file':['Excel / CSV / TSV dosyası','فایل Excel / CSV / TSV'],'Select a file. Hamvara will detect its data type and suggest a column mapping.':['Bir dosya seçin. Hamvara veri türünü algılar ve sütun eşleştirmesi önerir.','یک فایل انتخاب کنید؛ Hamvara نوع داده را تشخیص می‌دهد و نگاشت ستون‌ها را پیشنهاد می‌کند.'],'Column Mapping':['Sütun Eşleştirme','نگاشت ستون‌ها'],'Review the suggested mapping before validation':['Doğrulamadan önce önerilen eşleştirmeyi inceleyin','پیش از اعتبارسنجی، نگاشت پیشنهادی را بررسی کنید'],'Validate mapped rows':['Eşleştirilen Satırları Doğrula','اعتبارسنجی ردیف‌های نگاشت‌شده'],'Hamvara Standard Import Contract':['Hamvara Standart İçe Aktarma Şartnamesi','استاندارد ورود اطلاعات Hamvara'],
  'Previous':['Önceki','قبلی'],'Next':['Sonraki','بعدی'],'Warehouse Movement Report':['Depo Hareket Raporu','گزارش گردش انبار'],'New receipts enter Quarantine first. QC acceptance and manager approval are required before stock is posted to the destination warehouse.':['Yeni kabuller önce Karantina deposuna girer. Hedef depoya aktarım için kalite ve yönetici onayı gerekir.','رسیدهای جدید ابتدا وارد قرنطینه می‌شوند؛ انتقال به انبار مقصد نیازمند تأیید کنترل کیفیت و مدیر است.'],'Submit for QC':['Kalite Kontrolüne Gönder','ارسال برای کنترل کیفیت'],
  '+ New Product BOM':['+ Yeni Ürün Reçetesi','+ BOM محصول جدید'],'+ Material':['+ Malzeme','+ ماده اولیه'],'BOM Version, Product Configuration & Conversion Cost':['Reçete Sürümü, Ürün Yapılandırması ve Dönüşüm Maliyeti','نسخه BOM، مشخصات محصول و هزینه تبدیل'],'Version':['Sürüm','نسخه'],'Effective date':['Geçerlilik tarihi','تاریخ اجرا'],'Model':['Model','مدل'],'Design':['Tasarım','طرح'],'Packaging type':['Ambalaj türü','نوع بسته‌بندی'],'Labor cost / unit':['Birim işçilik maliyeti','هزینه نیروی کار / واحد'],'Overhead cost / unit':['Birim genel gider','هزینه سربار / واحد'],'Other cost / unit':['Diğer birim maliyet','سایر هزینه‌ها / واحد'],'Costing quantity':['Maliyet miktarı','مقدار محاسبه هزینه'],'Material Requirements & Cost':['Malzeme İhtiyaçları ve Maliyet','مواد مورد نیاز و هزینه'],'Process, Quality & Packaging Variables':['Proses, Kalite ve Ambalaj Değişkenleri','متغیرهای فرایند، کیفیت و بسته‌بندی'],'Up to 20 variables per BOM version':['Her reçete sürümünde en fazla 20 değişken','حداکثر ۲۰ متغیر برای هر نسخه BOM'],'+ Variable':['+ Değişken','+ متغیر'],'Version History':['Sürüm Geçmişi','تاریخچه نسخه‌ها'],'Save New BOM Version':['Yeni Reçete Sürümünü Kaydet','ذخیره نسخه جدید BOM'],
  'Work order → material reservation → shop-floor issue → finished-goods receipt':['İş emri → malzeme rezervasyonu → üretime çıkış → mamul kabulü','دستور کار ← رزرو مواد ← تحویل به خط ← دریافت محصول نهایی'],'+ Work Order':['+ İş Emri','+ دستور کار'],'Release reserves BOM materials. Issue moves them to Shop Floor. Reporting completion moves the batch to Quarantine; only accepted FQC posts it to Product warehouse.':['Serbest bırakma reçete malzemelerini rezerve eder. Çıkış malzemeleri üretim alanına taşır. Tamamlama partiyi Karantinaya alır; yalnızca kabul edilen FQC Ürün deposuna aktarır.','آزادسازی، مواد BOM را رزرو می‌کند؛ تحویل، مواد را به Shop Floor می‌برد؛ تکمیل، بچ را به قرنطینه منتقل می‌کند و فقط تأیید FQC آن را وارد انبار محصول می‌کند.'],'Prioritized Production Queue':['Öncelikli Üretim Sırası','صف اولویت‌بندی تولید'],'Work Orders':['İş Emirleri','دستورهای کار'],'Batch Traceability & Actual Time':['Parti İzlenebilirliği ve Gerçek Süre','ردیابی بچ و زمان واقعی'],'Production Audit Trail':['Üretim Denetim İzi','سوابق ممیزی تولید'],
  'Production Documents, Labels & Scan':['Üretim Belgeleri, Etiketler ve Tarama','اسناد تولید، لیبل و اسکن'],'Printable work-order documents, carton labels and controlled shop-floor receipt':['Yazdırılabilir iş emri belgeleri, koli etiketleri ve kontrollü üretim alanı kabulü','اسناد قابل چاپ دستور کار، لیبل کارتن و دریافت کنترل‌شده از Shop Floor'],'A4 Work-order Documents':['A4 İş Emri Belgeleri','اسناد A4 دستور کار'],'Documents use the BOM version and process-variable snapshot captured when the work order was created.':['Belgeler, iş emri oluşturulurken kaydedilen reçete sürümü ve proses değişkenlerini kullanır.','اسناد از نسخه BOM و مقادیر فرایندی ثبت‌شده هنگام ایجاد دستور کار استفاده می‌کنند.'],'Print Production Instruction':['Üretim Talimatını Yazdır','چاپ دستورالعمل تولید'],'Print Material Issue Form':['Malzeme Çıkış Formunu Yazdır','چاپ حواله مواد اولیه'],'Receive from Shop Floor':['Üretim Alanından Teslim Al','دریافت از Shop Floor'],'Scanned work order / batch':['Taranan iş emri / parti','دستور کار / بچ اسکن‌شده'],'Good quantity':['Sağlam miktar','مقدار سالم'],'Scrap quantity':['Fire miktarı','مقدار ضایعات'],'Use Mobile Camera':['Mobil Kamerayı Kullan','استفاده از دوربین موبایل'],'Confirm Receipt to FQC':['FQC Kabulünü Onayla','تأیید دریافت برای FQC'],'The finished batch is posted to Quarantine and cannot enter Product stock until FQC acceptance.':['Tamamlanan parti Karantinaya alınır ve FQC kabulüne kadar Ürün stokuna giremez.','بچ تکمیل‌شده وارد قرنطینه می‌شود و تا تأیید FQC به موجودی محصول وارد نخواهد شد.'],
  'Carton Label Designer':['Koli Etiketi Tasarımcısı','طراحی لیبل کارتن'],'Saved templates':['Kayıtlı şablonlar','قالب‌های ذخیره‌شده'],'New template':['Yeni şablon','قالب جدید'],'Template name':['Şablon adı','نام قالب'],'Size':['Boyut','اندازه'],'Custom':['Özel','سفارشی'],'Width mm':['Genişlik mm','عرض (میلی‌متر)'],'Height mm':['Yükseklik mm','ارتفاع (میلی‌متر)'],'Orientation':['Yön','جهت'],'Portrait':['Dikey','عمودی'],'Landscape':['Yatay','افقی'],'Margin mm':['Kenar boşluğu mm','حاشیه (میلی‌متر)'],'Labels per page':['Sayfa başına etiket','تعداد لیبل در صفحه'],'Gap mm':['Aralık mm','فاصله (میلی‌متر)'],'Manufacture date':['Üretim tarihi','تاریخ تولید'],'Expiry date':['Son kullanma tarihi','تاریخ انقضا'],'Quantity / carton':['Koli miktarı','مقدار در کارتن'],'Warning text':['Uyarı metni','متن هشدار'],'Logo / product / package image':['Logo / ürün / ambalaj görseli','لوگو / تصویر محصول / بسته‌بندی'],'Save Template':['Şablonu Kaydet','ذخیره قالب'],
  'Supplier Waybill Recognition & Incoming Labels':['Tedarikçi İrsaliye Tanıma ve Giriş Etiketleri','تشخیص بارنامه تأمین‌کننده و لیبل ورود'],'Read Waybill Image':['İrsaliye Görselini Oku','خواندن تصویر بارنامه'],'Upload an image; extracted rows must be reviewed before posting.':['Bir görsel yükleyin; çıkarılan satırlar kaydedilmeden önce incelenmelidir.','تصویر را بارگذاری کنید؛ ردیف‌های استخراج‌شده باید پیش از ثبت بررسی شوند.'],'Print One Barcode Label per Row':['Her Satır İçin Bir Barkod Etiketi Yazdır','چاپ یک لیبل بارکد برای هر ردیف'],
  'Procurement & Approved Suppliers':['Satın Alma ve Onaylı Tedarikçiler','تدارکات و تأمین‌کنندگان تأییدشده'],'PR → approved supplier → PO → quarantine receipt → three-way match':['PR → onaylı tedarikçi → PO → karantina kabulü → üçlü eşleştirme','PR ← تأمین‌کننده تأییدشده ← PO ← دریافت قرنطینه ← تطبیق سه‌طرفه'],'+ Supplier':['+ Tedarikçi','+ تأمین‌کننده'],'+ Purchase Request':['+ Satın Alma Talebi','+ درخواست خرید'],'+ Purchase Order':['+ Satın Alma Siparişi','+ سفارش خرید'],'MRP Purchase Suggestions':['MRP Satın Alma Önerileri','پیشنهادهای خرید MRP'],'Review uncovered material shortages before creating a purchase request.':['Satın alma talebi oluşturmadan önce karşılanmamış malzeme eksiklerini inceleyin.','پیش از ایجاد درخواست خرید، کسری‌های پوشش‌داده‌نشده مواد را بررسی کنید.'],'Approved Supplier List (ASL)':['Onaylı Tedarikçi Listesi (ASL)','فهرست تأمین‌کنندگان تأییدشده (ASL)'],'Purchase Requests (PR)':['Satın Alma Talepleri (PR)','درخواست‌های خرید (PR)'],'Purchase Orders (PO) and receiving gate':['Satın Alma Siparişleri (PO) ve kabul kontrolü','سفارش‌های خرید (PO) و کنترل دریافت'],
  'Quality Control & NCR':['Kalite Kontrol ve Uygunsuzluk','کنترل کیفیت و NCR'],'IQC incoming · IPQC process · FQC final · OQC outgoing':['IQC giriş · IPQC proses · FQC final · OQC çıkış','IQC ورودی · IPQC فرایند · FQC نهایی · OQC خروجی'],'+ Inspection':['+ Kontrol','+ بازرسی'],'Quarantine stock is released only by an accepted IQC decision. Rejected or conditional items remain traceable under NCR.':['Karantina stoku yalnızca kabul edilen IQC kararıyla serbest bırakılır. Reddedilen veya şartlı kalemler NCR altında izlenir.','موجودی قرنطینه فقط با تأیید IQC آزاد می‌شود؛ اقلام ردشده یا مشروط در NCR قابل ردیابی می‌مانند.'],'Commercial & Sales Orders':['Ticari ve Satış Siparişleri','سفارش‌های تجاری و فروش'],'Customer commitment, ATP check, stock reservation and credit status':['Müşteri taahhüdü, ATP kontrolü, stok rezervasyonu ve kredi durumu','تعهد مشتری، کنترل ATP، رزرو موجودی و وضعیت اعتبار'],'+ Sales Order':['+ Satış Siparişi','+ سفارش فروش'],'Finance Gates & Shipping':['Finans Kontrolleri ve Sevkiyat','کنترل‌های مالی و ارسال'],'Payment/credit approval → picking → OQC → invoice → shipment → POD':['Ödeme/kredi onayı → toplama → OQC → fatura → sevkiyat → POD','تأیید پرداخت/اعتبار ← جمع‌آوری ← OQC ← فاکتور ← ارسال ← تأیید تحویل'],'+ Finance Approval':['+ Finans Onayı','+ تأیید مالی'],'+ Shipment':['+ Sevkiyat','+ ارسال'],'Financial approvals':['Finans onayları','تأییدهای مالی'],'Shipping release queue':['Sevkiyat serbest bırakma sırası','صف مجوز ارسال'],
  'Device / Workstation Name':['Cihaz / İş İstasyonu Adı','نام دستگاه / ایستگاه کاری'],'Barcode Standard':['Barkod Standardı','استاندارد بارکد'],'Retail labels require a valid numeric GTIN. Enter 12 digits for EAN-13 or 11 digits for UPC-A and Hamvara will calculate the check digit; a supplied check digit is validated.':['Perakende etiketleri geçerli sayısal GTIN gerektirir. EAN-13 için 12, UPC-A için 11 rakam girin; Hamvara kontrol hanesini hesaplar ve girilen haneyi doğrular.','لیبل فروشگاهی به GTIN عددی معتبر نیاز دارد. برای EAN-13 تعداد ۱۲ رقم و برای UPC-A تعداد ۱۱ رقم وارد کنید؛ Hamvara رقم کنترل را محاسبه و بررسی می‌کند.'],'Automatic full backup: twice daily at 06:00 and 18:00 UTC.':['Otomatik tam yedekleme: her gün UTC 06:00 ve 18:00.','پشتیبان‌گیری کامل خودکار: روزانه ساعت ۰۶:۰۰ و ۱۸:۰۰ UTC.'],
  'Create Product BOM':['Ürün Reçetesi Oluştur','ایجاد BOM محصول'],'Create a product here or select an existing product that has no BOM.':['Burada bir ürün oluşturun veya reçetesi olmayan mevcut bir ürünü seçin.','در همین‌جا محصول جدید بسازید یا محصول موجود بدون BOM را انتخاب کنید.'],'Start with':['Başlangıç','شروع با'],'Create a new product':['Yeni ürün oluştur','ایجاد محصول جدید'],'Product code *':['Ürün kodu *','کد محصول *'],'Product name *':['Ürün adı *','نام محصول *'],'Unit':['Birim','واحد'],'Production lead time (hours)':['Üretim temin süresi (saat)','زمان برنامه‌ریزی تولید (ساعت)'],'First BOM version':['İlk reçete sürümü','اولین نسخه BOM'],'After creation, the BOM opens automatically with its first material row ready for entry.':['Oluşturulduktan sonra reçete, ilk malzeme satırı hazır olarak otomatik açılır.','پس از ایجاد، BOM به‌صورت خودکار با اولین ردیف آماده ورود مواد باز می‌شود.'],'Cancel':['İptal','لغو'],'Create & Open BOM':['Oluştur ve Reçeteyi Aç','ایجاد و بازکردن BOM'],'Import Validation':['İçe Aktarma Doğrulaması','اعتبارسنجی ورود اطلاعات'],'Post READY Rows':['HAZIR Satırları Kaydet','ثبت ردیف‌های آماده'],
  'Delete':['Sil','حذف'],'Action':['İşlem','عملیات'],'Status':['Durum','وضعیت'],'Date':['Tarih','تاریخ'],'Date & Time':['Tarih ve Saat','تاریخ و زمان'],'Reference':['Referans','مرجع'],'Destination':['Hedef','مقصد'],'Manager':['Yönetici','مدیر'],'Product':['Ürün','محصول'],'Product Code':['Ürün Kodu','کد محصول'],'Description':['Açıklama','شرح'],'Type':['Tür','نوع'],'Cost':['Maliyet','هزینه'],'Main Warehouse':['Ana Depo','انبار اصلی'],'Reserved':['Rezerve','رزروشده'],'Warehouse':['Depo','انبار'],'Warehouse State':['Depo Durumu','وضعیت انبار'],'SKU count':['SKU sayısı','تعداد SKU'],'Quantity here':['Buradaki miktar','مقدار در این انبار'],'Inventory value':['Stok değeri','ارزش موجودی'],'Last movement':['Son hareket','آخرین گردش'],'Direction':['Yön','جهت'],'Batch':['Parti','بچ'],'User':['Kullanıcı','کاربر'],'Device':['Cihaz','دستگاه'],'Order':['Sipariş','سفارش'],'Factor':['Katsayı','ضریب مصرف'],'Required':['İhtiyaç','مورد نیاز'],'Available':['Mevcut','قابل استفاده'],'Shortage':['Eksik','کسری'],'Planned':['Planlanan','برنامه‌ریزی‌شده'],'Completed':['Tamamlanan','تکمیل‌شده'],'Scrap':['Fire','ضایعات'],'Current Location':['Mevcut Konum','محل فعلی'],'Material SKU':['Malzeme SKU','SKU ماده'],'Material Qty':['Malzeme Miktarı','مقدار ماده'],'Output SKU':['Çıktı SKU','SKU خروجی'],'Gate':['Kontrol','دروازه کنترل'],'Area':['Alan','حوزه'],'Metric':['Ölçüt','شاخص'],'Value':['Değer','مقدار'],'Unit Cost':['Birim Maliyet','هزینه واحد'],'Work Order':['İş Emri','دستور کار'],'Inspection':['Kontrol','بازرسی'],'Disposition':['Karar','تعیین تکلیف'],'Released':['Serbest Bırakıldı','آزادشده'],'PO':['PO','سفارش خرید'],'PR':['PR','درخواست خرید'],'Unit Price':['Birim Fiyat','قیمت واحد'],'Total':['Toplam','جمع'],'Due Date':['Termin Tarihi','تاریخ سررسید'],'Invoice':['Fatura','فاکتور'],'Customer':['Müşteri','مشتری'],'Payment':['Ödeme','پرداخت'],'Shipment':['Sevkiyat','ارسال'],'Shipping Status':['Sevkiyat Durumu','وضعیت ارسال'],'Role':['Rol','نقش'],'Details':['Ayrıntılar','جزئیات'],'No records match the selected report filters.':['Seçilen rapor filtreleriyle eşleşen kayıt yok.','هیچ رکوردی با فیلترهای انتخاب‌شده مطابقت ندارد.'],'No action required.':['İşlem gerekmiyor.','اقدامی لازم نیست.'],'No unassigned production order.':['Atanmamış üretim siparişi yok.','سفارش تولید تخصیص‌نیافته‌ای وجود ندارد.'],'Next production priority:':['Sonraki üretim önceliği:','اولویت بعدی تولید:'],
  'Sign out':['Çıkış yap','خروج'],'Cloud connected':['Buluta bağlı','اتصال ابری برقرار است'],'Cloud saved':['Buluta kaydedildi','در فضای ابری ذخیره شد'],'Sign in':['Giriş yap','ورود'],'Sign in to your workspace':['Çalışma alanınıza giriş yapın','ورود به فضای کاری'],'Company data is isolated and stored securely in the Hamvara cloud.':['Şirket verileri ayrılmış şekilde Hamvara bulutunda güvenle saklanır.','اطلاعات شرکت به‌صورت مجزا و امن در فضای ابری Hamvara نگهداری می‌شود.'],'Workspace':['Çalışma alanı','فضای کاری'],'Username':['Kullanıcı adı','نام کاربری'],'Access Key':['Erişim Anahtarı','کلید دسترسی'],'Search report':['Rapor ara','جست‌وجوی گزارش'],'Scan or enter WO / batch':['İş emri / parti tara veya gir','دستور کار / بچ را اسکن یا وارد کنید'],'Product name':['Ürün adı','نام محصول'],
  'Active':['Aktif','فعال'],'Active Listings':['Aktif İlanlar','آگهی‌های فعال'],'Approved Suppliers':['Onaylı Tedarikçiler','تأمین‌کنندگان تأییدشده'],'Archived':['Arşivlendi','بایگانی‌شده'],'Awaiting IQC':['IQC Bekleyen','در انتظار IQC'],'Blocked':['Engelli','مسدود'],'Condition':['Durum','شرایط'],'Contact':['İletişim','اطلاعات تماس'],'Critical Items':['Kritik Kalemler','اقلام بحرانی'],'Draft orders':['Taslak siparişler','سفارش‌های پیش‌نویس'],'Finance pending':['Finans bekliyor','در انتظار تأیید مالی'],'Good':['İyi','مناسب'],'In Negotiation':['Görüşmede','در حال مذاکره'],'Inspection Required':['Kontrol Gerekli','نیازمند بازرسی'],'Issue':['Sorun','مشکل'],'Listed Value':['İlan Değeri','ارزش آگهی‌ها'],'Listing Status':['İlan Durumu','وضعیت آگهی'],'Live Exchange Listings':['Aktif Borsa İlanları','آگهی‌های فعال بازار'],'Location':['Konum','محل'],'Near Expiry':['Son Kullanım Yakın','نزدیک انقضا'],'Negotiation':['Görüşme','مذاکره'],'New / Unused':['Yeni / Kullanılmamış','نو / استفاده‌نشده'],'New Product':['Yeni Ürün','محصول جدید'],'New SKU':['Yeni SKU','SKU جدید'],'Normal':['Normal','عادی'],'Notes':['Notlar','یادداشت‌ها'],'Open PO':['Açık PO','سفارش خرید باز'],'Open PR':['Açık PR','درخواست خرید باز'],'Order No.':['Sipariş No.','شماره سفارش'],'Order Shortages':['Sipariş Eksikleri','کسری سفارش‌ها'],'Pending inspection':['Bekleyen kontrol','بازرسی‌های در انتظار'],'Priority':['Öncelik','اولویت'],'Producible Orders':['Üretilebilir Siparişler','سفارش‌های قابل تولید'],'Ready':['Hazır','آماده'],'Ready to ship':['Sevke hazır','آماده ارسال'],'Reject':['Reddet','رد کردن'],'Rejected':['Reddedilen','ردشده'],'Release blocked':['Çıkış engelli','مجوز خروج مسدود'],'Released stock':['Serbest bırakılan stok','موجودی آزادشده'],'Seller':['Satıcı','فروشنده'],'Shipped':['Sevk edildi','ارسال‌شده'],'Sold':['Satıldı','فروخته‌شده'],'Source Warehouse':['Kaynak Depo','انبار مبدأ'],'Stock':['Stok','موجودی'],'Usage Quantity':['Kullanım Miktarı','مقدار مصرف'],'Urgent':['Acil','فوری'],'Very Urgent':['Çok Acil','بسیار فوری'],
  'Export CSV':['CSV Dışa Aktar','خروجی CSV'],'Orders':['Siparişler','سفارش‌ها'],'Quantity':['Miktar','مقدار'],'Supplier':['Tedarikçi','تأمین‌کننده'],'Await FQC':['FQC Bekle','در انتظار FQC'],'Create PR':['PR Oluştur','ایجاد PR'],'Quality hold':['Kalite blokajı','توقف کیفی'],'Report completion':['Tamamlamayı bildir','ثبت گزارش تکمیل'],'INSTRUCTION':['TALİMAT','دستورالعمل'],'Ignore / not supplied':['Yoksay / sağlanmadı','نادیده گرفتن / ارائه نشده'],'No producible open orders':['Üretilebilir açık sipariş yok','سفارش باز قابل تولید وجود ندارد'],'No work orders':['İş emri yok','دستور کاری وجود ندارد'],'PROCESS':['PROSES','فرایند'],'QUALITY':['KALİTE','کیفیت'],'PACKAGING':['AMBALAJ','بسته‌بندی'],
  'ASL':['ASL','فهرست تأمین‌کننده مجاز'],'Accepted type':['Kabul edilen tür','نوع پذیرفته‌شده'],'Actual h':['Gerçek saat','ساعت واقعی'],'Amount':['Tutar','مبلغ'],'Approval':['Onay','تأیید'],'Budget':['Bütçe','بودجه'],'Category':['Kategori','دسته‌بندی'],'Code':['Kod','کد'],'Created':['Oluşturuldu','تاریخ ایجاد'],'Credit':['Kredi','اعتبار'],'Docs match':['Belgeler eşleşiyor','تطبیق اسناد'],'Due':['Termin','سررسید'],'Duplicate key':['Tekrarlanan anahtar','کلید تکراری'],'Effective':['Geçerlilik','تاریخ اجرا'],'Errors / Notes':['Hatalar / Notlar','خطاها / یادداشت‌ها'],'Expiry':['Son kullanma','انقضا'],'Finished SKU':['Mamul SKU','SKU محصول نهایی'],'Gross Usage':['Brüt Kullanım','مصرف ناخالص'],'Hamvara field':['Hamvara alanı','فیلد Hamvara'],'Issued':['Çıkarılan','تحویل‌شده'],'Key / SKU / Product':['Anahtar / SKU / Ürün','کلید / SKU / محصول'],'Lead days':['Termin günü','زمان تأمین (روز)'],'Line Cost / Unit':['Birim Satır Maliyeti','هزینه ردیف / واحد'],'MRP Shortage':['MRP Eksiği','کسری MRP'],'Matched SKU':['Eşleşen SKU','SKU منطبق'],'Materials':['Malzemeler','مواد'],'Name':['Ad','نام'],'Need':['İhtiyaç Tarihi','تاریخ نیاز'],'Open PR Qty':['Açık PR Miktarı','مقدار PR باز'],'Optional fields':['İsteğe bağlı alanlar','فیلدهای اختیاری'],'Packing list':['Paket listesi','لیست بسته‌بندی'],'Pick Qty':['Toplama Miktarı','مقدار برداشت'],'Planned Lead':['Planlanan Süre','زمان برنامه‌ریزی‌شده'],'Planned Lead (h)':['Planlanan Süre (s)','زمان برنامه‌ریزی‌شده (ساعت)'],'Planned h':['Planlanan saat','ساعت برنامه‌ریزی‌شده'],'Price':['Fiyat','قیمت'],'Production Reported':['Üretim Bildirildi','گزارش تولید ثبت شد'],'Qty':['Miktar','مقدار'],'Rating':['Puan','امتیاز'],'Readiness':['Hazırlık','آمادگی'],'Recognized description':['Tanınan açıklama','شرح تشخیص‌داده‌شده'],'Release':['Serbest Bırakma','مجوز خروج'],'Requester':['Talep Eden','درخواست‌کننده'],'Required fields':['Zorunlu alanlar','فیلدهای الزامی'],'Result':['Sonuç','نتیجه'],'Row':['Satır','ردیف'],'Sales Order':['Satış Siparişi','سفارش فروش'],'Saved':['Kaydedildi','ذخیره‌شده'],'Sequence':['Sıra','ترتیب'],'Source column':['Kaynak sütun','ستون مبدأ'],'Stage':['Aşama','مرحله'],'Standard Unit Cost':['Standart Birim Maliyet','هزینه استاندارد واحد'],'Suggested Qty':['Önerilen Miktar','مقدار پیشنهادی'],'Target value':['Hedef değer','مقدار هدف'],'Terms':['Koşullar','شرایط'],'Variable / Requirement':['Değişken / Gereksinim','متغیر / الزام'],'Variables':['Değişkenler','متغیرها'],'Waste %':['Fire %','درصد ضایعات'],
  'Initial data loaded':['Başlangıç verileri yüklendi','اطلاعات اولیه بارگذاری شد'],'Full backup created':['Tam yedek oluşturuldu','پشتیبان کامل ایجاد شد'],'Settings saved':['Ayarlar kaydedildi','تنظیمات ذخیره شد'],'Data imported':['Veriler içe aktarıldı','اطلاعات وارد شد'],'Excel template downloaded.':['Excel şablonu indirildi.','قالب اکسل دانلود شد.'],'Invalid file structure':['Geçersiz dosya yapısı','ساختار فایل نامعتبر است'],'Create a product first, then add BOM items.':['Önce bir ürün oluşturun, ardından reçete kalemlerini ekleyin.','ابتدا یک محصول ایجاد کنید، سپس اقلام BOM را اضافه کنید.'],'Select a valid SKU.':['Geçerli bir SKU seçin.','یک SKU معتبر انتخاب کنید.'],'Select a destination warehouse.':['Bir hedef depo seçin.','انبار مقصد را انتخاب کنید.'],'Select a producible order.':['Üretilebilir bir sipariş seçin.','یک سفارش قابل تولید انتخاب کنید.'],'Select a QC result first.':['Önce QC sonucu seçin.','ابتدا نتیجه کنترل کیفیت را انتخاب کنید.'],'Quantity must be greater than zero.':['Miktar sıfırdan büyük olmalıdır.','مقدار باید بیشتر از صفر باشد.'],'No matching quarantine stock.':['Eşleşen karantina stoku yok.','موجودی منطبقی در قرنطینه وجود ندارد.'],'No new excess stock found.':['Yeni fazla stok bulunamadı.','موجودی مازاد جدیدی یافت نشد.'],'Materials reserved.':['Malzemeler rezerve edildi.','مواد رزرو شدند.'],'Materials issued to Shop Floor.':['Malzemeler üretim alanına çıkarıldı.','مواد به Shop Floor تحویل شدند.'],'Work order created.':['İş emri oluşturuldu.','دستور کار ایجاد شد.'],'Work order cancelled.':['İş emri iptal edildi.','دستور کار لغو شد.'],'Receipt submitted to quarantine for QC.':['Kabul QC için karantinaya gönderildi.','رسید برای کنترل کیفیت به قرنطینه ارسال شد.'],'Purchase request created from MRP shortage.':['MRP eksiğinden satın alma talebi oluşturuldu.','درخواست خرید از کسری MRP ایجاد شد.'],'QC accepted; manager approval is required before posting.':['QC kabul etti; kayıt için yönetici onayı gerekli.','کنترل کیفیت تأیید شد؛ ثبت نهایی نیازمند تأیید مدیر است.'],'NCR created; stock remains in quarantine.':['NCR oluşturuldu; stok karantinada kalır.','NCR ایجاد شد؛ موجودی در قرنطینه باقی می‌ماند.'],'Manager approved; stock posted to destination.':['Yönetici onayladı; stok hedef depoya işlendi.','مدیر تأیید کرد؛ موجودی در انبار مقصد ثبت شد.'],'Manager rejected; stock remains in quarantine under NCR.':['Yönetici reddetti; stok NCR ile karantinada kaldı.','مدیر رد کرد؛ موجودی تحت NCR در قرنطینه باقی ماند.'],'Manager approve':['Yönetici onayı','تأیید مدیر'],
  'Blocked: supplier is not approved in ASL.':['Engellendi: tedarikçi ASL listesinde onaylı değil.','مسدود: تأمین‌کننده در ASL تأیید نشده است.'],'Blocked: PR and budget must be approved.':['Engellendi: PR ve bütçe onaylı olmalıdır.','مسدود: درخواست خرید و بودجه باید تأیید شوند.'],'Blocked: valid SKU and quantity required.':['Engellendi: geçerli SKU ve miktar gerekli.','مسدود: SKU و مقدار معتبر لازم است.'],'Blocked: document, QC and credit gates are incomplete.':['Engellendi: belge, QC ve kredi kontrolleri eksik.','مسدود: کنترل سند، کیفیت یا اعتبار کامل نیست.'],'Blocked: insufficient finished-goods stock.':['Engellendi: mamul stok yetersiz.','مسدود: موجودی محصول نهایی کافی نیست.'],'Blocked: reservation, finance, OQC, picking, packing list or invoice is incomplete.':['Engellendi: rezervasyon, finans, OQC, toplama, paket listesi veya fatura eksik.','مسدود: رزرو، مالی، OQC، برداشت، لیست بسته‌بندی یا فاکتور کامل نیست.'],'Operational data is securely stored in your Hamvara cloud workspace.':['Operasyon verileri Hamvara bulut çalışma alanınızda güvenle saklanır.','داده‌های عملیاتی به‌صورت امن در فضای ابری Hamvara نگهداری می‌شوند.'],'Save error: ':['Kayıt hatası: ','خطای ذخیره‌سازی: '],'Excel import error: ':['Excel içe aktarma hatası: ','خطای ورود اکسل: '],'Error: ':['Hata: ','خطا: '],'Saved: ':['Kaydedildi: ','ذخیره شد: '],
  'APPROVED':['ONAYLANDI','تأییدشده'],'ACCEPTED':['KABUL EDİLDİ','پذیرفته‌شده'],'RELEASED':['SERBEST','آزادشده'],'SHIPPED':['SEVK EDİLDİ','ارسال‌شده'],'CLOSED':['KAPALI','بسته‌شده'],'MATCHED':['EŞLEŞTİ','تطبیق‌شده'],'COMPLETED':['TAMAMLANDI','تکمیل‌شده'],'REJECTED':['REDDEDİLDİ','ردشده'],'BLOCKED':['ENGELLİ','مسدود'],'OVERDUE':['GECİKMİŞ','سررسیدگذشته'],'CANCELLED':['İPTAL','لغوشده'],'QUALITY HOLD':['KALİTE BLOKAJI','توقف کیفی'],'PENDING':['BEKLİYOR','در انتظار'],'CONDITIONAL':['ŞARTLI','مشروط'],'DRAFT':['TASLAK','پیش‌نویس'],'PLANNED':['PLANLANDI','برنامه‌ریزی‌شده'],'IN PRODUCTION':['ÜRETİMDE','در حال تولید'],'AWAITING FQC':['FQC BEKLİYOR','در انتظار FQC'],'IN PROCESS':['İŞLEMDE','در حال پردازش'],'ON HAND':['ELDE','موجود'],'NEGATIVE':['NEGATİF','منفی'],'IN':['GİRİŞ','ورود'],'OUT':['ÇIKIŞ','خروج'],'NORMAL':['NORMAL','عادی'],'URGENT':['ACİL','فوری'],'VERY URGENT':['ÇOK ACİL','بسیار فوری'],'READY':['HAZIR','آماده'],'Validate':['Doğrula','اعتبارسنجی'],'Apply decision':['Kararı uygula','اعمال تصمیم'],'Decision applied':['Karar uygulandı','تصمیم اعمال شد'],'Await manager':['Yönetici bekleniyor','در انتظار مدیر'],'Check & reserve':['Kontrol et ve rezerve et','کنترل و رزرو'],'Recheck gates':['Kontrolleri yenile','بازبینی کنترل‌ها'],'Post shipment':['Sevkiyatı kaydet','ثبت ارسال'],'Check release':['Çıkışı kontrol et','کنترل مجوز خروج'],'Release & reserve':['Serbest bırak ve rezerve et','آزادسازی و رزرو'],'Issue to Shop Floor':['Üretim alanına çıkar','تحویل به Shop Floor'],'Complete production':['Üretimi tamamla','تکمیل تولید'],
  'Raw Materials':['Hammadde','مواد اولیه'],'Packaging':['Ambalaj','بسته‌بندی'],'Product':['Mamul Ürün','محصول'],'Quarantine':['Karantina','قرنطینه'],'Shop Floor':['Üretim Alanı','Shop Floor'],'Producible':['Üretilebilir','قابل تولید'],'Not Producible':['Üretilemez','غیرقابل تولید'],'Incomplete BOM':['Eksik Reçete','BOM ناقص'],'Sufficient':['Yeterli','کافی'],'Enter Factor':['Katsayı Gir','ضریب را وارد کنید'],'Empty':['Boş','خالی'],'Piece (ADET)':['Adet (ADET)','عدد (ADET)'],'Kilogram (KG)':['Kilogram (KG)','کیلوگرم (KG)'],'Gram (G)':['Gram (G)','گرم (G)'],'Liter (L)':['Litre (L)','لیتر (L)'],'Milliliter (ML)':['Mililitre (ML)','میلی‌لیتر (ML)'],'Meter (M)':['Metre (M)','متر (M)'],'Square Meter (M2)':['Metrekare (M2)','مترمربع (M2)'],'Cubic Meter (M3)':['Metreküp (M3)','مترمکعب (M3)'],'Pack (PAKET)':['Paket (PAKET)','بسته (PAKET)'],'Roll (RULO)':['Rulo (RULO)','رول (RULO)'],'Box (KUTU)':['Kutu (KUTU)','جعبه (KUTU)']
};

const normalizeKey=value=>String(value??'').trim().replace(/\s+/g,' ');
const SOURCE_BY_TRANSLATION=new Map();
for(const [source,pair] of Object.entries(TEXTS)){
  SOURCE_BY_TRANSLATION.set(normalizeKey(source),source);
  SOURCE_BY_TRANSLATION.set(normalizeKey(pair[0]),source);
  SOURCE_BY_TRANSLATION.set(normalizeKey(pair[1]),source);
}

const DYNAMIC_TEXT=[
  [/^Page (\d+) \/ (\d+) · rows (\d+)–(\d+) of (\d+)$/,
    m=>[`Sayfa ${m[1]} / ${m[2]} · ${m[3]}–${m[4]} / ${m[5]} satır`,`صفحه ${m[1]} از ${m[2]} · ردیف ${m[3]} تا ${m[4]} از ${m[5]}`]],
  [/^(\d+) item\(s\) below minimum stock\.$/,
    m=>[`${m[1]} kalem minimum stok altında.`,`${m[1]} قلم کمتر از حداقل موجودی است.`]],
  [/^(\d+) order item shortage\(s\)\.$/,
    m=>[`${m[1]} sipariş kaleminde eksik var.`,`${m[1]} قلم سفارش دارای کسری است.`]],
  [/^(\d+) order\(s\) have incomplete BOM factors\.$/,
    m=>[`${m[1]} siparişte reçete katsayısı eksik.`,`${m[1]} سفارش دارای ضریب مصرف ناقص در BOM است.`]],
  [/^(\d+) quality inspection\(s\) are pending\.$/,
    m=>[`${m[1]} kalite kontrolü bekliyor.`,`${m[1]} بازرسی کیفیت در انتظار است.`]],
  [/^(\d+) receipt\(s\) await manager approval\.$/,
    m=>[`${m[1]} kabul yönetici onayı bekliyor.`,`${m[1]} رسید در انتظار تأیید مدیر است.`]],
  [/^(\d+) financial approval\(s\) are pending\.$/,
    m=>[`${m[1]} finans onayı bekliyor.`,`${m[1]} تأیید مالی در انتظار است.`]],
  [/^(\d+) shipment\(s\) are blocked by process gates\.$/,
    m=>[`${m[1]} sevkiyat süreç kontrolünde engelli.`,`${m[1]} ارسال توسط کنترل‌های فرایندی مسدود شده است.`]],
  [/^Qty in (.+)$/,
    m=>[`${m[1]} miktarı`,`مقدار در ${m[1]}`]]
];

export function translateUiText(value,language){
  const raw=String(value??''),key=normalizeKey(raw),source=SOURCE_BY_TRANSLATION.get(key)||key,pair=TEXTS[source];
  let translated=language==='en'?source:language==='tr'?pair?.[0]:language==='fa'?pair?.[1]:source;
  if(!pair&&language!=='en'){
    for(const [pattern,render] of DYNAMIC_TEXT){const match=source.match(pattern);if(match){const dynamic=render(match);translated=language==='tr'?dynamic[0]:dynamic[1];break}}
  }
  if(!translated)translated=source;
  return raw.replace(raw.trim(),translated);
}

export function hasUiTranslation(value){return SOURCE_BY_TRANSLATION.has(normalizeKey(value))}
