const amount=value=>Math.round((Number(value)||0)*100)/100;
const sum=(balances,predicate)=>amount(balances.filter(predicate).reduce((total,row)=>total+row.amount,0));

export const IFRS_ENGINE={
  id:'IFRS_TFRS',name:'IFRS / TFRS Engine',presentation:'IAS 1; IFRS 18 for annual periods beginning on or after 2027-01-01',inventoryStandard:'IAS 2',impairmentReversal:true,
  validate(state){const issues=[],warnings=[];(state.skus||[]).filter(item=>item.costMethod==='LIFO').forEach(item=>issues.push({severity:'BLOCKER',code:'IAS2_LIFO',reference:item.code,message:'LIFO is prohibited under IAS 2.'}));if(!(state.accountingPeriods||[]).length)warnings.push({severity:'WARNING',code:'PERIOD_REQUIRED',reference:'',message:'Configure accounting periods before statutory reporting.'});return{issues,warnings}},
  incomeStatement(balances,periodStart=''){const revenue=sum(balances,row=>row.type==='REVENUE'),costOfSales=sum(balances,row=>row.type==='EXPENSE'&&/^5/.test(row.code)),operatingExpenses=sum(balances,row=>row.type==='EXPENSE'&&/^6/.test(row.code)),financeCosts=sum(balances,row=>row.type==='EXPENSE'&&/^7/.test(row.code)),tax=sum(balances,row=>row.type==='EXPENSE'&&/^8/.test(row.code)),operatingProfit=amount(revenue-costOfSales-operatingExpenses),profitBeforeTax=amount(operatingProfit-financeCosts);return[{statement:'Profit or loss',line:'Revenue',amount:revenue,standard:'IFRS 15'},{statement:'Profit or loss',line:'Operating expenses including cost of sales',amount:-amount(costOfSales+operatingExpenses),standard:periodStart>='2027-01-01'?'IFRS 18':'IAS 1'},{statement:'Profit or loss',line:'Operating profit',amount:operatingProfit,standard:periodStart>='2027-01-01'?'IFRS 18':'IAS 1'},{statement:'Profit or loss',line:'Finance costs',amount:-financeCosts,standard:'IFRS 9 / IFRS 18'},{statement:'Profit or loss',line:'Profit before tax',amount:profitBeforeTax,standard:'IAS 1 / IFRS 18'},{statement:'Profit or loss',line:'Income tax expense',amount:-tax,standard:'IAS 12'},{statement:'Profit or loss',line:'Profit for the period',amount:amount(profitBeforeTax-tax),standard:'IAS 1 / IFRS 18'}]},
  inventoryMeasurement(input={}){const cost=amount(input.historicalCost),nrv=amount(input.nrv),current=amount(input.carryingValue??cost),previous=amount(input.previousWriteDown),recoverable=Math.min(cost,nrv),raw=amount(recoverable-current),adjustment=raw>0?Math.min(raw,previous):raw;return{basis:'Lower of cost and NRV',targetValue:amount(current+adjustment),adjustment,canReverse:adjustment>0,standard:'IAS 2',status:adjustment<0?'WRITE_DOWN':adjustment>0?'REVERSAL':'NO_CHANGE'}}
};
