import {appendAudit} from './audit-workflow.js';
import {normalizeFinancialState} from './financial-core.js';

const uid=prefix=>`${prefix}-${globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2)}`;
const number=value=>{const result=Number(value);return Number.isFinite(result)?result:0};
const money=value=>Math.round((number(value)+Number.EPSILON)*100)/100;
const quantity=value=>Math.round((number(value)+Number.EPSILON)*1e6)/1e6;
const key=(sku,warehouse)=>`${sku}|${warehouse}`;
const metaFields=(meta={})=>({user:meta.user||'unknown',role:meta.role||'',workspace:meta.workspace||'',device:meta.device||'unknown'});

export const COST_METHODS=['FIFO','WEIGHTED_AVERAGE','STANDARD','LIFO'];

export function normalizeInventoryCostState(state){normalizeFinancialState(state);state.inventoryValuations??={};state.inventoryCostLayers??=[];state.inventoryCostMovements??=[];state.skus??=[];state.skus.forEach(item=>{item.costMethod=COST_METHODS.includes(item.costMethod)?item.costMethod:'STANDARD';item.standardCost=number(item.standardCost??item.cost)});return state}

export function setInventoryCostMethod(state,skuCode,method,meta={}){normalizeInventoryCostState(state);if(!COST_METHODS.includes(method))throw Error('Unsupported inventory cost method.');if(method==='LIFO'&&state.accountingSettings.profile!=='US_GAAP')throw Error('LIFO is only available under the US GAAP profile.');const item=state.skus.find(candidate=>candidate.code===skuCode);if(!item)throw Error('SKU was not found.');const active=Object.values(state.inventoryValuations).some(row=>row.sku===skuCode&&row.quantity!==0);if(active&&item.costMethod!==method)throw Error('Cost method cannot change while valued inventory exists.');const previous=item.costMethod;if(previous===method)return item;item.costMethod=method;appendAudit(state,{...metaFields(meta),action:'INVENTORY_COST_METHOD_CHANGED',entity:'INVENTORY_COST',reference:skuCode,details:`${previous} → ${method}`});return item}

function ensureValuation(state,skuCode,warehouse){const id=key(skuCode,warehouse);if(!state.inventoryValuations[id])state.inventoryValuations[id]={sku:skuCode,warehouse,quantity:0,value:0,averageCost:0,lastCost:0};return state.inventoryValuations[id]}
function sku(state,skuCode){const item=state.skus.find(candidate=>candidate.code===skuCode);if(!item)throw Error(`SKU ${skuCode} was not found.`);if(item.costMethod==='LIFO'&&state.accountingSettings.profile!=='US_GAAP')throw Error('LIFO is prohibited by the active IFRS/TFRS profile.');return item}
function validateMovement(input){const qty=quantity(input.qty),unitCost=money(input.unitCost);if(qty<=0)throw Error('Inventory costing quantity must be greater than zero.');if(unitCost<0)throw Error('Inventory unit cost cannot be negative.');if(!input.warehouse)throw Error('Warehouse is required for inventory costing.');return{qty,unitCost}}
function record(state,input){const movement={id:input.id||uid('COST'),date:input.date||new Date().toISOString().slice(0,10),at:input.at||new Date().toISOString(),sku:input.sku,warehouse:input.warehouse,direction:input.direction,method:input.method,quantity:input.quantity,unitCost:input.unitCost,value:input.value,reference:input.reference||'',source:input.source||'',variance:input.variance||0,layers:input.layers||[],...metaFields(input.meta)};state.inventoryCostMovements.unshift(movement);appendAudit(state,{...metaFields(input.meta),action:`INVENTORY_COST_${input.direction}`,entity:'INVENTORY_COST',reference:input.reference||input.sku,at:movement.at,details:`${input.sku} · ${input.quantity} @ ${input.unitCost} · ${input.method}`});return movement}

export function receiveInventoryCost(state,input={},meta={}){normalizeInventoryCostState(state);const item=sku(state,input.sku),{qty,unitCost}=validateMovement(input),method=input.method||item.costMethod,valuation=ensureValuation(state,input.sku,input.warehouse);if(method!==item.costMethod)throw Error('Movement method must match the SKU cost method.');let bookedUnitCost=unitCost,variance=0;if(method==='STANDARD'){bookedUnitCost=money(item.standardCost);variance=money((unitCost-bookedUnitCost)*qty)}else if(['FIFO','LIFO'].includes(method)){state.inventoryCostLayers.push({id:uid('LAYER'),sku:input.sku,warehouse:input.warehouse,date:input.date||new Date().toISOString().slice(0,10),reference:input.reference||'',originalQty:qty,remainingQty:qty,unitCost})}const bookedValue=money(qty*bookedUnitCost);valuation.quantity=quantity(valuation.quantity+qty);valuation.value=money(valuation.value+bookedValue);valuation.averageCost=valuation.quantity?money(valuation.value/valuation.quantity):0;valuation.lastCost=unitCost;return record(state,{...input,meta,direction:'IN',method,quantity:qty,unitCost:bookedUnitCost,value:bookedValue,variance})}

function consumeLayers(state,input,method,qty){const layers=state.inventoryCostLayers.filter(layer=>layer.sku===input.sku&&layer.warehouse===input.warehouse&&layer.remainingQty>0).sort((a,b)=>method==='FIFO'?a.date.localeCompare(b.date)||a.id.localeCompare(b.id):b.date.localeCompare(a.date)||b.id.localeCompare(a.id)),used=[];let remaining=qty,total=0;for(const layer of layers){if(remaining<=0)break;const take=quantity(Math.min(remaining,layer.remainingQty)),value=money(take*layer.unitCost);remaining=quantity(remaining-take);total=money(total+value);used.push({layerId:layer.id,date:layer.date,quantity:take,unitCost:layer.unitCost,value})}if(remaining>0)throw Error('Insufficient cost layers for this inventory issue.');for(const usedLayer of used){const layer=state.inventoryCostLayers.find(candidate=>candidate.id===usedLayer.layerId);layer.remainingQty=quantity(layer.remainingQty-usedLayer.quantity)}return{total,used}}

export function issueInventoryCost(state,input={},meta={}){normalizeInventoryCostState(state);const item=sku(state,input.sku),qty=quantity(input.qty),method=input.method||item.costMethod,valuation=ensureValuation(state,input.sku,input.warehouse);if(qty<=0)throw Error('Inventory costing quantity must be greater than zero.');if(method!==item.costMethod)throw Error('Movement method must match the SKU cost method.');if(valuation.quantity+1e-6<qty)throw Error('Insufficient valued inventory for this issue.');let total=0,layers=[];if(['FIFO','LIFO'].includes(method)){const result=consumeLayers(state,input,method,qty);total=result.total;layers=result.used}else if(method==='WEIGHTED_AVERAGE')total=money(qty*valuation.averageCost);else total=money(qty*item.standardCost);const unitCost=qty?money(total/qty):0;valuation.quantity=quantity(valuation.quantity-qty);valuation.value=valuation.quantity?money(Math.max(0,valuation.value-total)):0;valuation.averageCost=valuation.quantity?money(valuation.value/valuation.quantity):0;return record(state,{...input,meta,direction:'OUT',method,quantity:qty,unitCost,value:total,layers})}

export function ensureInventoryCostCoverage(state,{sku:skuCode,warehouse,physicalQuantity,unitCost,reference='COST-OPENING-MIGRATION',at=new Date().toISOString()}={},meta={}){normalizeInventoryCostState(state);const item=sku(state,skuCode),valuation=ensureValuation(state,skuCode,warehouse),missing=quantity(Math.max(0,number(physicalQuantity)-valuation.quantity));if(!missing)return null;return receiveInventoryCost(state,{sku:skuCode,warehouse,qty:missing,unitCost:number(unitCost??item.cost??item.standardCost),date:at.slice(0,10),at,reference,source:'OPENING_COST_MIGRATION'},meta)}

export function transferInventoryCost(state,input={},meta={}){normalizeInventoryCostState(state);const item=sku(state,input.sku),qty=quantity(input.qty);if(!input.destinationWarehouse||input.destinationWarehouse===input.warehouse)throw Error('A different destination warehouse is required for cost transfer.');const out=issueInventoryCost(state,{...input,qty,source:'WAREHOUSE_TRANSFER_COST'},meta),destination=ensureValuation(state,input.sku,input.destinationWarehouse);destination.quantity=quantity(destination.quantity+qty);destination.value=money(destination.value+out.value);destination.averageCost=destination.quantity?money(destination.value/destination.quantity):0;destination.lastCost=out.unitCost;const transferredLayers=[];if(['FIFO','LIFO'].includes(item.costMethod))for(const used of out.layers){const layer={id:uid('LAYER'),sku:input.sku,warehouse:input.destinationWarehouse,date:used.date,reference:input.reference||'',originalQty:used.quantity,remainingQty:used.quantity,unitCost:used.unitCost,transferSourceLayerId:used.layerId,transferSourceMovementId:out.id};state.inventoryCostLayers.push(layer);transferredLayers.push({...used,destinationLayerId:layer.id})}const incoming=record(state,{...input,meta,warehouse:input.destinationWarehouse,direction:'IN',method:item.costMethod,quantity:qty,unitCost:out.unitCost,value:out.value,layers:transferredLayers,source:'WAREHOUSE_TRANSFER_COST'});return{out,in:incoming,value:out.value,unitCost:out.unitCost,method:item.costMethod,layers:transferredLayers}}

export function reverseInventoryCostIssue(state,movementId,{reference='Cost reversal',at=new Date().toISOString()}={},meta={}){normalizeInventoryCostState(state);const original=state.inventoryCostMovements.find(item=>item.id===movementId&&item.direction==='OUT');if(!original)throw Error('Issued inventory cost movement was not found.');if(original.reversedBy)throw Error('Inventory cost movement has already been reversed.');const valuation=ensureValuation(state,original.sku,original.warehouse);for(const used of original.layers||[])if(!state.inventoryCostLayers.some(item=>item.id===used.layerId))throw Error('Original inventory cost layer was not found.');for(const used of original.layers||[]){const layer=state.inventoryCostLayers.find(item=>item.id===used.layerId);layer.remainingQty=quantity(layer.remainingQty+used.quantity)}valuation.quantity=quantity(valuation.quantity+original.quantity);valuation.value=money(valuation.value+original.value);valuation.averageCost=valuation.quantity?money(valuation.value/valuation.quantity):0;const reversal=record(state,{sku:original.sku,warehouse:original.warehouse,direction:'IN',method:original.method,quantity:original.quantity,unitCost:original.unitCost,value:original.value,reference,source:'INVENTORY_COST_REVERSAL',layers:original.layers,at,meta});original.reversedBy=reversal.id;return reversal}

export function reverseInventoryCostTransfer(state,{outMovementId,inMovementId,reference='Transfer cost reversal',at=new Date().toISOString()}={},meta={}){normalizeInventoryCostState(state);const out=state.inventoryCostMovements.find(item=>item.id===outMovementId&&item.direction==='OUT'),incoming=state.inventoryCostMovements.find(item=>item.id===inMovementId&&item.direction==='IN');if(!out||!incoming||out.reversedBy||incoming.reversedBy)throw Error('Active transfer cost movements were not found.');const source=ensureValuation(state,out.sku,out.warehouse),destination=ensureValuation(state,incoming.sku,incoming.warehouse);if(destination.quantity+1e-6<incoming.quantity||destination.value+0.01<incoming.value)throw Error('Destination valuation is insufficient for transfer reversal.');for(const used of incoming.layers||[]){const layer=state.inventoryCostLayers.find(item=>item.id===used.destinationLayerId),sourceLayer=state.inventoryCostLayers.find(item=>item.id===used.layerId);if(!layer||layer.remainingQty+1e-6<used.quantity)throw Error('Transferred cost layer is insufficient for reversal.');if(!sourceLayer)throw Error('Original source cost layer was not found.')}for(const used of incoming.layers||[]){const layer=state.inventoryCostLayers.find(item=>item.id===used.destinationLayerId),sourceLayer=state.inventoryCostLayers.find(item=>item.id===used.layerId);layer.remainingQty=quantity(layer.remainingQty-used.quantity);sourceLayer.remainingQty=quantity(sourceLayer.remainingQty+used.quantity)}destination.quantity=quantity(destination.quantity-incoming.quantity);destination.value=destination.quantity?money(destination.value-incoming.value):0;destination.averageCost=destination.quantity?money(destination.value/destination.quantity):0;source.quantity=quantity(source.quantity+out.quantity);source.value=money(source.value+out.value);source.averageCost=source.quantity?money(source.value/source.quantity):0;const reversalOut=record(state,{sku:incoming.sku,warehouse:incoming.warehouse,direction:'OUT',method:incoming.method,quantity:incoming.quantity,unitCost:incoming.unitCost,value:incoming.value,reference,source:'TRANSFER_COST_REVERSAL',layers:incoming.layers,at,meta}),reversalIn=record(state,{sku:out.sku,warehouse:out.warehouse,direction:'IN',method:out.method,quantity:out.quantity,unitCost:out.unitCost,value:out.value,reference,source:'TRANSFER_COST_REVERSAL',layers:out.layers,at,meta});out.reversedBy=reversalIn.id;incoming.reversedBy=reversalOut.id;return{out:reversalOut,in:reversalIn,value:out.value}}

export function inventoryCostReport(state,{warehouse='',skuCode=''}={}){normalizeInventoryCostState(state);return Object.values(state.inventoryValuations).filter(row=>(!warehouse||row.warehouse===warehouse)&&(!skuCode||row.sku===skuCode)).map(row=>{const item=state.skus.find(candidate=>candidate.code===row.sku)||{};return{...row,description:item.name||'',method:item.costMethod||'STANDARD',standardCost:number(item.standardCost)}})}
