(function(){'use strict';const $=s=>document.querySelector(s),config=window.HAMVARA_MRP_CONFIG||{},apiBase=String(config.apiBase||'').replace(/\/$/),params=new URLSearchParams(location.hash.slice(1)),token=params.get('token')||sessionStorage.getItem('hamvara.scan.token')||'',device=sessionStorage.getItem('hamvara.scan.device')||crypto.randomUUID(),SESSION='hamvara.scan.token';let scanner=null,expiresAt=0,lastSequence=0,pollTimer=null,busy=false;sessionStorage.setItem('hamvara.scan.device',device);if(token)sessionStorage.setItem(SESSION,token);history.replaceState(null,'',location.pathname+location.search);
async function request(path,options={}){let response;for(let attempt=0;attempt<2;attempt+=1){try{response=await fetch(apiBase+path,{...options,headers:{'Content-Type':'application/json','X-Hamvara-Scan-Token':token,'X-Hamvara-Scan-Device':device,...options.headers}});break}catch(error){if(attempt)throw new Error(`Network connection to Hamvara failed from ${location.origin}. Reopen the QR link in Safari or Chrome and check internet access.`);await new Promise(resolve=>setTimeout(resolve,500))}}let body={};try{body=await response.json()}catch{}if(!response.ok){const error=new Error(body.error||`Connection failed (${response.status}).`);error.status=response.status;throw error}return body}
function remaining(){const seconds=Math.max(0,Math.ceil((expiresAt-Date.now())/1000));$('#countdown').textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;if(!seconds)expire()}
function expire(){$('#connectionStatus').textContent='Expired';$('#connectionStatus').className='danger';$('#message').textContent='This secure connection has expired. Create a new QR on the laptop.';$('#startCamera').disabled=true;$('#sendBarcode').disabled=true;clearInterval(pollTimer);scanner?.stop().catch(()=>{})}
async function connect(){if(!token)return expire();try{const data=await request('/api/mrp/mobile-scan/session');expiresAt=Date.parse(data.session.expiresAt);$('#connectionStatus').textContent='Securely connected';$('#message').textContent='Ready. Start the camera or use a Bluetooth scanner.';remaining();setInterval(remaining,1000);pollTimer=setInterval(poll,1000)}catch(error){fail(error)}}
async function send(code){code=String(code||'').trim();if(!code||busy)return;busy=true;try{const data=await request('/api/mrp/mobile-scan/events',{method:'POST',body:JSON.stringify({code})});lastSequence=Math.max(lastSequence-1,0);$('#lastScan').className='';$('#lastScan').innerHTML=`<b>${escapeHtml(data.event.code)}</b><p>Sent to terminal · waiting for identification</p>`;$('#barcodeInput').value='';navigator.vibrate?.(100);await poll()}catch(error){fail(error)}finally{busy=false}}
async function poll(){try{const data=await request(`/api/mrp/mobile-scan/events?after=${Math.max(0,lastSequence-5)}`);for(const event of data.events){lastSequence=Math.max(lastSequence,event.sequence);if(event.sequence===lastSequence){const result=event.result,details=result?.label?`${result.kind}: ${result.code} — ${result.label}`:'Waiting for terminal identification';$('#lastScan').className=event.status.toLowerCase();$('#lastScan').innerHTML=`<b>${escapeHtml(event.code)}</b><p>${escapeHtml(details)}</p><strong>${escapeHtml(event.status)}</strong>`}}}catch(error){if([401,403,410].includes(error.status))fail(error)}}
async function startCamera(){try{if(scanner){await scanner.stop().catch(()=>{});scanner=null}scanner=new Html5Qrcode('reader');await scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:260,height:160}},async text=>{await scanner.stop().catch(()=>{});scanner=null;await send(text);$('#startCamera').textContent='Scan another barcode'})}catch(error){$('#message').textContent=`Camera unavailable: ${error.message}. Allow camera access or use scanner input.`}}
function fail(error){$('#message').textContent=error.message;$('#message').className='danger';if(error.status===410)expire()}
function escapeHtml(value){return String(value??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
$('#startCamera').onclick=startCamera;$('#sendBarcode').onclick=()=>send($('#barcodeInput').value);$('#barcodeInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();send(e.target.value)}};connect()})();
