import {appendAudit} from './audit-workflow.js';

const text=value=>String(value??'').trim();
const hash=value=>{let result=2166136261;for(const char of value){result^=char.charCodeAt(0);result=Math.imul(result,16777619)}return(result>>>0).toString(16).padStart(8,'0')};
const DOCUMENTS=[['REL-01','Release notes'],['REL-02','Deployment and rollback guide'],['REL-03','Customer handover checklist'],['REL-04','Test and acceptance evidence'],['REL-05','License and support terms'],['REL-06','Data backup and recovery instructions']];
const document=([code,name])=>({code,name,status:'MISSING',reference:'',verifiedBy:'',verifiedAt:''});
export function normalizeReleasePackages(state){state.releasePackages??=[];for(const item of state.releasePackages){item.documents??=DOCUMENTS.map(document);item.history??=[];item.status??='DRAFT'}return state}
function activeBaseline(state){return(state.operationsBaselines||[]).find(item=>item.status==='ACTIVE')}
function find(state,id){normalizeReleasePackages(state);const item=state.releasePackages.find(row=>row.id===id);if(!item)throw Error('Product release package was not found.');return item}
export function releasePackageSummary(item){const documents=item?.documents||[],complete=documents.filter(row=>row.status==='VERIFIED').length,missing=documents.length-complete;return{complete,missing,ready:documents.length===DOCUMENTS.length&&!missing&&!!item?.artifactName&&!!item?.checksum}}
export function createReleasePackage(state,{version,channel,artifactName,preparedBy,releaseDate,compatibility}={},meta={}){normalizeReleasePackages(state);const baseline=activeBaseline(state),release=text(version),track=text(channel).toUpperCase(),artifact=text(artifactName),user=text(preparedBy||meta.user),compatible=text(compatibility),date=Date.parse(releaseDate);if(!baseline)throw Error('An ACTIVE production operations baseline is required before packaging.');if(!release||!['PILOT','STABLE','LTS'].includes(track)||!artifact||!user||compatible.length<10||!Number.isFinite(date))throw Error('Version, channel, artifact, preparer, date and compatibility statement are required.');const at=meta.at||new Date().toISOString(),manifest={version:release,channel:track,artifactName:artifact,releaseDate:new Date(date).toISOString().slice(0,10),schemaVersion:state.schemaVersion||1,baselineNo:baseline.baselineNo,compatibility:compatible},item={id:`REL-${Date.now()}-${state.releasePackages.length+1}`,packageNo:`REL-${String(state.releasePackages.length+1).padStart(5,'0')}`,...manifest,preparedBy:user,manifest,checksum:hash(JSON.stringify(manifest)),status:'DRAFT',createdAt:at,documents:DOCUMENTS.map(document),history:[{action:'CREATED',at,user}]};state.releasePackages.unshift(item);appendAudit(state,{...meta,user,action:'RELEASE_PACKAGE_CREATED',entity:'RELEASE_PACKAGE',reference:item.packageNo,details:`${release} · ${track} · ${item.checksum}`});return item}
export function verifyReleaseDocument(state,id,code,{reference,verifiedBy,at=new Date().toISOString()}={}){const item=find(state,id),row=item.documents.find(entry=>entry.code===code),ref=text(reference),user=text(verifiedBy);if(item.status!=='DRAFT'||!row)throw Error('Editable release document was not found.');if(ref.length<5||!user)throw Error('Document reference and verifier are required.');Object.assign(row,{status:'VERIFIED',reference:ref,verifiedBy:user,verifiedAt:at});appendAudit(state,{action:'RELEASE_DOCUMENT_VERIFIED',entity:'RELEASE_PACKAGE',reference:`${item.packageNo}/${code}`,user,at,details:ref});return row}
export function submitReleasePackage(state,id,{submittedBy,releaseNote,at=new Date().toISOString()}={}){const item=find(state,id),summary=releasePackageSummary(item),user=text(submittedBy),note=text(releaseNote);if(item.status!=='DRAFT')throw Error('Only a draft release package can be submitted.');if(!summary.ready)throw Error(`Release package is blocked by ${summary.missing} missing document(s).`);if(!user||note.length<10)throw Error('Submitter and release note of at least 10 characters are required.');Object.assign(item,{status:'REVIEW',submittedBy:user,releaseNote:note,submittedAt:at});appendAudit(state,{action:'RELEASE_PACKAGE_SUBMITTED',entity:'RELEASE_PACKAGE',reference:item.packageNo,user,at,details:note});return item}
export function approveReleasePackage(state,id,{approvedBy,approvalNote,at=new Date().toISOString()}={}){const item=find(state,id),user=text(approvedBy),note=text(approvalNote);if(item.status!=='REVIEW')throw Error('Release package review is required.');if(!user||note.length<10)throw Error('Independent approver and approval note are required.');if([item.preparedBy,item.submittedBy].some(value=>value.toLowerCase()===user.toLowerCase()))throw Error('Release approver must be independent from preparer and submitter.');Object.assign(item,{status:'PUBLISHED',approvedBy:user,approvalNote:note,publishedAt:at});appendAudit(state,{action:'RELEASE_PACKAGE_PUBLISHED',entity:'RELEASE_PACKAGE',reference:item.packageNo,user,at,details:`${item.version} · ${item.checksum}`});return item}
export {DOCUMENTS};
